### ISSUE TITLE
Improve information about backups and pitfalls before doing an update

### ISSUE THREAD

**Issue by te-online** [owncloud/updater#105]
Some users have problems while updating, because at the moment updating still needs a bit of **preparation** (e.g. looking for app-compatibility, doing a backup...). (https://forum.owncloud.org/viewtopic.php?f=31&t=26987). The UI doesn't say anything about any preparation needed and signifies: *You can just click* **update** *and everything will work*.

As this is *not* the case, we need either make sure *that everything will work* or tell the user that he needs to be prepared for updating. Maybe we choose the second option while the first option is beeing developed in between :wink:.

This problem was identified after people having problems with the update to 8.0.2 and also discussed here. (https://github.com/owncloud/updater/issues/86#issuecomment-82371418). I think it is worth to have a closer look at it.

-------

As one first step I thought about adding a **confirmation dialogue** to the update process where the user gets to know all the risks (this information is needed here by experts!) and has to explicitly confirm that he understood them and has a backup.

### »Research«

Originally I wanted to have a look at other systems (that I know) and how they deal with it, but it showed that their update process is either more sophisticated so that no errors happen or they simply don't care.

>**WordPress**
![](https://www.liberiangeek.net/wp-content/uploads/2014/04/wordpressupgrade39_thumb.png)
Has a *slight* hint – as we have in the moved interface – to backup all files before updating.

>**Joomla**
![](https://docs.joomla.org/images/a/aa/Media_1349745128572.png)
No hint at all to do a backup...

Well, that doesn't help much...

The only interesting approach is Github's delete-repo-confirmation-dialogue:
![](https://help.github.com/assets/images/help/repository/repo-delete-confirmation.png)

------

### Possible solutions

So I made up some possible solutions:

##### 1) Confirmation dialogue
Advantages:
- easy to implement

Disadvantages
- chance of accepting it without mentally noticing it, because mechanism is common

##### 2) Confirmation with input of a fixed word
Advantages:
- chance that the risk will become very clear to the user

Disadvantages:
- a bit more work to implement
- can be learned after one time doing – with the second update the user knows what to fill in and might do it without actively knowing

##### 3) Confirmation with input of changing words (maybe the next versions number?)
Advantages:
- relative high chance that the user won't do it from procedural memory

Disadvantages:
- relative much work to implement and test and make it really »work« for users (understandable explanation of what to enter, buttons etc.) so that it doesn't confuse them

##### 4) Force users to re-enter their password or username before update is possible
Advantages:
- Procedure is well-known to users by how operating systems do important tasks

Disadvantages:
- Chances are that the user can still do it without full understanding of the consequences, when he is familiar with his password/username

----

### Next steps

If someone else finds this a good point (@VicDeo might), I would like to go on. Next step would be to *collect the information* the user has to be confronted with before updating and what of this information might be fetched automatically. After that we can think about how this might look like in the interface.

Does this go too far or in a completely wrong direction? Please tell me :smile:!

PS: I didn't use the issue template this time, I hope you understand why...

**Comment by karlitschek** [comment]
@jancborchardt @VicDeo what are you opinions?

**Comment by SamEliotFisher** [comment]
@te-online thank you for pointing out (and creating!) this issue. Great work doing research for existing solutions! It is interesting to see that, as I was not aware of all the different solutions out there.

In my opinion a mixture of the existing solutions would be best. I don't believe typing in a word will raise awareness for the possible failure of the update process. Maybe it does but I think it is building up another barrier which is not constructive and will *heavily* decrease usability and user friendliness (especially if the word even changes per update). 

Yet another very simple but effective solution astonishes me:
A button with the inscription "**I understand the consequences/risk**". One does not simply click that like an "Update now" button! This is very different.

![e706e67](https://cloud.githubusercontent.com/assets/11375752/6812938/6ded43b8-d272-11e4-8d6c-6281e66dd5d5.png)

Maybe, as I mentioned before, in a combination with an css alert box as seen here. 
 
![alertboxes](https://cloud.githubusercontent.com/assets/11375752/6813100/3a1c549c-d273-11e4-8482-64946405a27b.png)

Informing the user of the need and location of backups. 
Thanks again for your contribution, you're pointing out an important issue.

**Comment by jancborchardt** [comment]
@te-online wow, that’s some solid research and writeup! :) Have to write a longer reply to this. cc @owncloud/designers as well.

**Comment by te-online** [comment]
Great, thanks for your first feedback!

@SamEliotFisher I like the idea of the button with a different caption. It sounds like an optimized version of solution 1).

**Comment by tflidd** [comment]
@te-online : I would go for solution 1 with a confirmation process. It should be easy to show all installed 3rd party apps, so just put a page, did you verify that all your 3rd party apps are available for the new version (for upgrades) + list of apps + link where to check it. The same thing for backups...

So it's more the idea of implementing parts of the documentation (who most people read after their upgrade failed) into this update/upgrade dialog.

**Comment by enoch85** [comment]
Another idea, maybe Off Topic - is to update plugins (apps) in the background (if that´s possible) and update ownCloud as regular. A little bit like Wordpress does it.

**Comment by te-online** [comment]
@tflidd @enoch85 You have some really good points. I will try to create a first mockup of what would be displayed and how, as soon as possible.

**Comment by jancborchardt** [comment]
@te-online you’re based near Osnabrück, right? I’ll be near there end of May, I could visit you and we could work together on some of this design & dev stuff. What do you think?

**Comment by te-online** [comment]
@jancborchardt yes, that sounds like a good idea :wink: Maybe you can email me the details and I'll have a look into the calendar?

**Comment by te-online** [comment]
http://arstechnica.com/security/2015/03/mris-show-our-brains-shutting-down-when-we-see-security-prompts/
Might be interesting to read :wink:

**Comment by enoch85** [comment]
@te-online Any news here?

**Comment by te-online** [comment]
@enoch85 see https://github.com/nextcloud/updater/issues/33 for the start of a discussion about the new updater script. My hope is, that when everything goes well, the new updater will be an improvement of the whole process, can be integrated in a hassle-free way and can be used universally.
