### ISSUE TITLE
Updating ownCloud to version 8.0.2

### ISSUE THREAD

**Issue by highacid** [owncloud/updater#106]
Updating ownCloud to version 8.0.2, this may take a while.

Turned on maintenance mode
An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_xfo7be87x3apt (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_46nuacyz6eu6z (`configkey`), INDEX oc_m9b91qbwuecya (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_xfo7be87x3apt' already exists
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by RealRancor** [comment]
@karlitschek Looks to me like a dup of https://github.com/owncloud/core/issues/14916

**Comment by karlitschek** [comment]
@RealRancor Good catch :-)
