### ISSUE TITLE
Check dependencies like PHP version before the upgrade

### ISSUE THREAD

**Issue by RealRancor** [owncloud/updater#107]
Hi,

currently hard dependencies like PHP 5.4 are only checked in core:

https://github.com/owncloud/core/blob/v8.0.2/lib/private/util.php#L622-L629

Especially in the case of an upgrade from a system running OC 7.x with PHP 5.3 to OC 8.x this caused a failure of the upgrade. User often just miss to read this new dependency in the documentation and so they are stuck with a new OC8 upgrade which forces them either to roll-back an backup or to upgrade their PHP.

As the updater from OC7 for example can't know what new dependencies OC8 will bring maybe the API on https://apps.owncloud.com/updater.php?version=4x90x14x1338030373.1628x1373617342.3379xstablex could be extended to show such problematic new dependencies like PHP 5.4. This could be used by the updater app to warn the user before doing the upgrade.

**Comment by RealRancor** [comment]
Hi,

i think this is getting more importance for the OC 8.1 release which should include https://github.com/owncloud/core/pull/14540. On windows this will hard-fail, don't want to know how many installations are "stuck" with that if a windows user is just clicking on "update". :see_no_evil:

**Comment by aznewt** [comment]
Indeed, this happened to me last night: didn't read the dependencies, clicked update, installed 8.0.2 on my php 5.3.24 hosting plan. I don't have a 7.x database backup so  now having to figure out how to get back to 7.x

Please give ths enhancement ahigh priority!

**Comment by VicDeo** [comment]
@karlitschek On my opinion PHP version check is needed for OC7 only since PHP 5.4 is a hard requirement for OC8 so we can skip this for master/stable8.

I suggest to hide the content of the entire 'Update' section in this case and show a warning:
"Your server environment is not compatible with ownCloud 8. You need to update PHP to the version 5.4.0 or above".
What do you think?

**Comment by karlitschek** [comment]
@VicDeo Good idea :-)

**Comment by VicDeo** [comment]
OC8 and PHP 5.3 https://github.com/owncloud/updater/pull/117
win and 8.1 https://github.com/owncloud/updater/issues/118

**Comment by tflidd** [comment]
Would be nice to have a check if all the apps are available for the new version (during upgrades).
