### ISSUE TITLE
Type Inconsistence

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#109]
https://github.com/owncloud/updater/blob/master/templates/admin.php#L19
https://github.com/owncloud/updater/blob/master/admin.php#L34
Sometimes `$_['version']` ( `$data['versionstring']` ) is an array itself.
I bet it is connected with feed caching somehow

**Comment by MorrisJobke** [comment]
Can this be done with a check if it is a string and otherwise log an error and set it to an empty string to avoid the error message?

**Comment by VicDeo** [comment]
@MorrisJobke there is an error when caching a response in core. Most likely it is related to serialization of  SimpleXMLElement objects.
Casting it here is not a fix but a stub.

**Comment by MorrisJobke** [comment]
> @MorrisJobke there is an error when caching a response in core. Most likely it is related to serialization of SimpleXMLElement objects.

Any chance to reproduce this?

**Comment by VicDeo** [comment]
Should be fixed for 8, 8.1, 8.2 with 
https://github.com/owncloud/updater/pull/367
https://github.com/owncloud/updater/pull/368
https://github.com/owncloud/updater/pull/369
