### ISSUE TITLE
Updater Notice

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#111]
Hi RealRancor,

thanks again for your advice. How about some info included in the Update(er) page for reference and online-advice, to cut down on questions and concerns about this 'ancient fact' ???? :-)

Regards. hitam4450

PS. Version 8 is full of advice and additiponal information already, apparently the Updater is excluded from that ! :-)

**Comment by RealRancor** [comment]
He is referring to this forums thread:

https://forum.owncloud.org/viewtopic.php?f=31&t=28017

After every OC release questions like this why the updater app is not showing the new update araise.

**Comment by VicDeo** [comment]
@karlitschek I guess we need to put a notice regarding this delay to reduce a number of reports. 
Something like  `Please note that update will be available  in a day or two after its official announcement` 

Not sure about the wording though...

**Comment by karlitschek** [comment]
@VicDeo Very good idea. Maybe something like: "Updates will show up here a few days after the official announcement"
What do you think @MTRichards  ?

**Comment by MTRichards** [comment]
I would think something like:

"Updates will be available in the updater app and ownCloud admin panel within a few days of an update announcement."

**Comment by te-online** [comment]
Would be a great improvement! :+1:
