### ISSUE TITLE
Das Update ist fehlgeschlagen. Bitte überprüfe die Protokolle auf der Administratorenseite und melde dieses Problem der ownCloud-Gemeinschaft.

### ISSUE THREAD

**Issue by HMF-IT** [owncloud/updater#115]
![update](https://cloud.githubusercontent.com/assets/12269556/7489835/475f58e6-f3db-11e4-945d-6babc99bed8d.PNG)

**Comment by HMF-IT** [comment]
Wie kann ich das herausfinden?
Grüße

**Comment by karlitschek** [comment]
Sorry for the problem. Please ask this question in the owncloud forum at forum.owncloud.org. Thanks a lot.
