### ISSUE TITLE
Das Update ist fehlgeschlagen 8.0.2 > 8.0.3

### ISSUE THREAD

**Issue by Alexalter** [owncloud/updater#121]
Updates

1. Prüfen & Sichern  2. Herunterladen & Entpacken 3. Ersetzen
Hier ist Ihre Sicherung: /www/htdocs/w0131f22/owncloud/data/updater_backup/8.0.2.0-c9008e5d

Das Update ist fehlgeschlagen. Bitte überprüfen Sie die Protokolle auf der Administratorenseite und melden Sie dieses Problem der ownCloud-Gemeinschaft.

**Comment by RealRancor** [comment]
Please check your logfiles (also /data/owncloud.log) as stated in the message.

**Comment by Alexalter** [comment]
Update ist trotz installiert

**Comment by RealRancor** [comment]
@Alexalter 
Please provide more informations. With the current state it also just can be closed because no one can guess the problems here.
