### ISSUE TITLE
(OC 8.1 beta1) Updater App Update channel & repo-version

### ISSUE THREAD

**Issue by tflidd** [owncloud/updater#122]
Upgraded OC 8.1 beta1 on Debian 7 from the testing repo.

In the admin interface, you can choose an update channel. But it shows an error:
![oc_updates](https://cloud.githubusercontent.com/assets/8111200/7606117/577e1e1c-f956-11e4-89a9-adb476a5b7bb.png)

In the debian package, only the data, apps, and config-folder are writable to the webserver user. version.php is owned by root.

What is the supposed behavior of the updater app when owncloud is managed by the system's packet manager?
- only inform that there are updates
- run updates
- is not activated at all (but it was not turned off by default upon the update process)

**Comment by RealRancor** [comment]
Hi,

very likely this:

> is not activated at all (but it was not turned off by default upon the update process)

I thinks its even better if the OBS repos is not shipping the updater app at all or am i wrong?

**Comment by karlitschek** [comment]
@VicDeo Is is possible to store this in the DB?  As some kind of overwrite value? We can always write into version.php
What do you think?

**Comment by RealRancor** [comment]
Mhhh, but normally the updatecheck should be already disabled in the OBS packages according to: https://github.com/owncloud/core/issues/6980#issuecomment-52760755

**Comment by karlitschek** [comment]
True. But even in manual installations version.php is not writeable.

**Comment by RealRancor** [comment]
Why shipping the updater app in the OBS package at all as it is currently done? I think no one should need to use the updater while using an repository.

**Comment by karlitschek** [comment]
yes. in an ideal world the updater is not in the linux packages

**Comment by karlitschek** [comment]
@jnweiger FYI

**Comment by VicDeo** [comment]
@karlitschek >Is is possible to store this in the DB?

yes. Needs changing `lib/private/util.php` in core https://github.com/owncloud/core/blob/master/lib/private/util.php#L363

**Comment by karlitschek** [comment]
Great. Would be cool if you could do this :-)

**Comment by jnweiger** [comment]
owncloud-app-updater is not pulled in when installing owncloud. Apparently people still manage to get it installed. 

Fix: I'll proactively remove the updater app code and no longer provide the subpackage.

**Comment by tflidd** [comment]
I didn't install it on purpose. Possible that it was installed by default on OC 8.0.x? Initially I installed an OC 8.0.1 or OC 8.0.2 from the suse repo, updated till 8.0.3 and today I upgraded to 8.1.0 beta1.

**Comment by jnweiger** [comment]
@tflidd Yes, I think what happened, that you got owncloud-app-updater as a dependency at some point in time, and from then on the package just updated itself as newer versions became available.
I have now added a Replaces: owncloud-app-updater to the debian control file of owncloud. This should help getting rid of the package.

**Comment by VicDeo** [comment]
ok, the value is stored in DB now, but this issue is not about storing the value :confused:

**Comment by cmonteroluque** [comment]
@VicDeo what's missing then? Don't the PRs eliminate the permissions issue?

**Comment by cmonteroluque** [comment]
closing

**Comment by carlaschroder** [comment]
owncloud-app-updater is included on new clean Ubuntu installations.

**Comment by carlaschroder** [comment]
opps wrong Issue, pay no attention.

**Comment by jnweiger** [comment]
owncloud-app-updater should not be installed on new clean Ubuntu installations. That is a bug.
