### ISSUE TITLE
Channel isn't being updated in the admin page

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#126]
### Steps to reproduce
1. Enable updater app
2. Ensure apache can write in the version.php file
3. Go to the admin page and change the updater channel
4. Refresh the page

### Expected behaviour
Channel is updated

### Actual behaviour
There are no changes. Web page doesn't show any change and the version.php file remains the same

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 2

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"FYa1tNSMASYJCYABK3sz","remoteAddr":"10.40.30.21","app":"PHP","message":"Undefined variable: lastCheck at \/home\/jvillafanez\/src\/owncloud\/owncloud-oc8.1\/apps\/updater\/ajax\/channel.php#25","level":3,"time":"2015-05-21T16:42:43+00:00"}
{"reqId":"rzVvCoLnvlC42PaRNP7x","remoteAddr":"10.40.30.21","app":"PHP","message":"Array to string conversion at \/home\/jvillafanez\/src\/owncloud\/owncloud-oc8.1\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-05-21T16:42:49+00:00"}
```

Permissions should be fine (incomplete list of files in the ownCloud directory)
```
-rw-rw-r--  1 www-data    www-data        3007 May 18 08:06 public.php
-rw-rw-r--  1 www-data    www-data        3065 May 18 08:06 remote.php
-rw-rw-r--  1 www-data    www-data          26 May 18 08:06 robots.txt
drwxrwxr-x 13 www-data    www-data        4096 May 18 08:06 settings
-rw-rw-r--  1 www-data    www-data        1727 May 18 08:06 status.php
drwxrwxr-x  3 www-data    www-data        4096 May 18 08:07 themes
-rw-rw-r--  1 www-data    www-data         178 May 21 18:51 version.php

```

**Comment by cmonteroluque** [comment]
@VicDeo a look also to this one please?

**Comment by VicDeo** [comment]
Fix is in
https://github.com/owncloud/core/pull/16339 and https://github.com/owncloud/updater/issues/124 already

**Comment by cmonteroluque** [comment]
@jvillafanez @VicDeo ready to close this?

**Comment by jvillafanez** [comment]
Yep. Checked and working.
