### ISSUE TITLE
Issue with postgresql when trying to update an app

### ISSUE THREAD

**Issue by efargas** [owncloud/updater#132]
Actualizando ownCloud a la versión 8.0.3. Esto puede tardar un poco.

Modo mantenimiento activado
Actualización del esquema de base de datos revisado
Comprobada la actualización del esquema de la base de datos para aplicaciones
Base de datos actualizada
An exception occurred while executing 'ALTER TABLE oc_ocdownloader_adminsettings ALTER VAL DROP NOT NULL': SQLSTATE[42703]: Undefined column: 7 ERROR: column "val" of relation "oc_ocdownloader_adminsettings" does not exist
The update was unsuccessful. Please report this issue to the ownCloud community.

the table exists and have thr VAL column

Postgresql version 9.3.7
Ubuntu server 14.04.02

**Comment by RealRancor** [comment]
Hi,

this doesn't looks to me like an issue with the updater itself but the update mechanism in core. For this its the best to close this issue and create a new one in:

https://github.com/owncloud/core/issues

using the issue template provided here: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by VicDeo** [comment]
@efargas related to DB migration process (core) and `ocdownloader` scheme (I don't know what this app does)
Closing as unrelated to Updater. Please reopen in core as @RealRancor suggested.
