### ISSUE TITLE
[OC 8.0.3] still get Array to string conversion at /owncloud/lib/private/l10n/string.php#75 

### ISSUE THREAD

**Issue by darkclip** [owncloud/updater#133]
Steps to reproduce

    every time open update center

Expected behaviour

    nothing appears in error log

Actual behaviour

    The error shows up in log
    Error 	PHP 	Array to string conversion at /owncloud/lib/private/l10n/string.php#75 
 
Server configuration

    Operating system: centOS 6
    Web server: nginx 1.8.0
    Database: mysql
    PHP version: 5.4.41 
    ownCloud version: OC 8.0.3

Updated from an older ownCloud or fresh install

    upgraded from older version

Possible Solution

apps/updater/update.php line# 34

    $tmpl->assign('version', isset($data['versionstring']) ? $data['versionstring'] : '');

Change to

    $tmpl->assign('version', $isNewVersionAvailable ? $data['versionstring'] : '');

**Comment by karlitschek** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@darkclip your solution is just a workaround for https://github.com/owncloud/updater/issues/109

**Comment by jmeile** [comment]
After upgrading to 8.1.1 by using the updater, I'm getting this too :-(

**Comment by jmeile** [comment]
I realized that the file is different:
{"reqId":"VdIjzJfqGLFMbSIpOGbNHAAAAAY","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Array to string conversion at \/usr\/local\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-08-17T18:11:24+00:00"}

It is the updater. I disabled it and the error was gone

**Comment by VicDeo** [comment]
@jmeile really? ;) https://github.com/owncloud/core/issues/17468#issuecomment-127178124

**Comment by jmeile** [comment]
Yes, I also saw that after posting here.

So, is this an issue with php? By the way, I have version: 5.4.16-36

**Comment by jmeile** [comment]
Ok, now I see, it is an issue with: sanitizeHTML

**Comment by VicDeo** [comment]
Addressed in https://github.com/owncloud/core/pull/18921
