### ISSUE TITLE
Unable to extract package Array: unknown format

### ISSUE THREAD

**Issue by RealRancor** [owncloud/updater#134]
Hi,

we had two reported issues at the forums about this message in the past:

https://forum.owncloud.org/viewtopic.php?f=31&t=28773
https://forum.owncloud.org/viewtopic.php?f=31&t=27085

The main problem here is that the reason/problem of this message is unclear to the end-user. I think this could be improved within the updater app.

The message itself is thrown here:

https://github.com/owncloud/updater/blob/v8.0.3/lib/downloader.php#L30

Could this be caused by a status page if https://apps.owncloud.com is in maintenance mode for example which caused a redirect to a html page instead of the download package itself?

**Comment by VicDeo** [comment]
@RealRancor a good old bug in core caching part :\
It sometimes return update feed as
```
array (
   'version'  => VERSION,
   'url'  => URL,
etc
)
```
and sometimes
```
array (
   'version'  => array(VERSION),
   'url'  => array(URL),
etc
)
```

https://github.com/owncloud/updater/issues/109
