### ISSUE TITLE
Updater doesn't show update 8.0.2 -> 8.0.4

### ISSUE THREAD

**Issue by chriskloe** [owncloud/updater#135]
Hi!

I updated my ownlcoud with the updater app to 8.0.2 the last time. I didn't see any updates in my owncloud for some time now, so I got curious and manuelly checked owncloud.org. There I see 8.0.4 is the actual version but updater still doesn't show the update. How am I able to apply the update now (using the app - therefore I installed it)?

Greetings,
Christoph

**Comment by RealRancor** [comment]
Hi,

first make sure that you don't have set this config option to false in your config.php:

https://github.com/owncloud/core/blob/v8.0.4/config/config.sample.php#L429-L433

Also make sure that your installation is able to reach http://apps.owncloud.com and https://apps.owncloud.com (No firewall blocking etc.)

**Comment by chriskloe** [comment]
Hi,

I don't have this option in my config.php and a wget for test shows this result:
'[/share/Web/tmp] # wget https://apps.owncloud.com/
--2015-06-15 16:20:58--  https://apps.owncloud.com/
Resolving apps.owncloud.com... 188.138.57.103
Connecting to apps.owncloud.com|188.138.57.103|:443... connected.
ERROR: cannot verify apps.owncloud.com's certificate, issued by â/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2â:
  Unable to locally verify the issuer's authority.
To connect to apps.owncloud.com insecurely, use `--no-check-certificate'.
[/share/Web/tmp] # wget http://apps.owncloud.com/
--2015-06-15 16:21:28--  http://apps.owncloud.com/
Resolving apps.owncloud.com... 188.138.57.103
Connecting to apps.owncloud.com|188.138.57.103|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apps.owncloud.com/ [following]
--2015-06-15 16:21:28--  https://apps.owncloud.com/
Connecting to apps.owncloud.com|188.138.57.103|:443... connected.
ERROR: cannot verify apps.owncloud.com's certificate, issued by â/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2â:
  Unable to locally verify the issuer's authority.
To connect to apps.owncloud.com insecurely, use `--no-check-certificate'.
'

**Comment by RealRancor** [comment]
Hi,

yes this is an issue within your operating system/environment which is missing the intermediate certificate for the connection to the appstore. This is causing the missing infos about the update and is not a problem of the updater app itself.

OC 8.1 will ship a workaround for such systems. Until that you could try to fix your setup with https://forum.owncloud.org/viewtopic.php?f=31&t=26310&p=88393#p85771

**Comment by VicDeo** [comment]
closing, outdated server certificates is unrelated to the app.

**Comment by LukasReschke** [comment]
@VicDeo Updater is not using the ClientService from core. Thus this won't help there. At least from what I can tell from https://github.com/owncloud/updater/blob/c0b35af33672eb570373c1e5b6604fa5ead42974/lib/downloader.php#L89-L97

Might be worth to consider using `\OC\Http\Client\Client::get` which also has a `save_to` option as can be found at https://github.com/owncloud/core/blob/b585d87d9d6ccf964d10cd2e2cb1d465eb537a25/lib/private/http/client/client.php#L93-L124, this would also use streaming properly.

**Comment by VicDeo** [comment]
@LukasReschke it does, via https://github.com/owncloud/updater/blob/master/lib/app.php#L41
>updater still doesn't show the update

Means exactly that there is no data from feed

**Comment by LukasReschke** [comment]
> Means exactly that there is no data from feed

Yes. But the actual download will still fail hard with PHP 5.6 if certificates are not properly configured. - The feed fetching should be work with 8.1 though, yes.

**Comment by RealRancor** [comment]
@LukasReschke 
I don't think that the download can fail hard as the appstore is still providing the http:// link:

https://apps.owncloud.com/updater.php?version=4x90x14x1338030373.1628x1373617342.3379xstablex

without a re-direct to https:// so the problem won't happen during the download.

**Comment by LukasReschke** [comment]
@karlitschek Can we fix this? :see_no_evil:

**Comment by VicDeo** [comment]
@LukasReschke define `this` :wink:

**Comment by LukasReschke** [comment]
`define('this', 'appstore returning updates via http instead https');`

**Comment by RealRancor** [comment]
@LukasReschke 
Any additional place where the change from http:// to https:// could be requested? A closed issue within the updater app is probably not the best place.

Maybe https://github.com/owncloud/appstore-issues/issues?
