### ISSUE TITLE
upgrading to oc8.0.3 and higher from oc8

### ISSUE THREAD

**Issue by bah0071** [owncloud/updater#136]
I'm sure many people have asked this question/requested this regarding using the updater....
it's not so simple changing the permissions on all the files so the updater can work and then changing them back to maintain the security...

I think there should be a script or update app that would change the permissions of the required files so the updater works and then changes them back after the update is complete...otherwise doing upgrades would be very difficult for those of us that are not 100% technical

**Comment by VicDeo** [comment]
no problem, app is open for a new code.

**Comment by te-online** [comment]
@bah0071 You mean, if you change all folders to not writeable for the web server after each update? I never run into problems with permissions on update, but always used default permissions, though.

**Comment by bah0071** [comment]
seems it is resolved thanks!
