### ISSUE TITLE
UpdateChecker not working: Undefined variable: lastCheck -> fixed on Master, please Tag

### ISSUE THREAD

**Issue by derkostka** [owncloud/updater#142]
I Just have seen that the version delivered with the 8.1.0-RC1 is at beta2. Please Update with the next freeze to fix this Bug:

Steps to reproduce

    Go to the Admin-Settings and change the Update Channel
    Watch the Log-Output 3.

Expected behaviour

No Error
Actual behaviour

Undefined Variable thrown to Log
Server configuration

Ubuntu 15.04
Apache2
MySQL
PHP 5.6
Owncloud 8.1 RC1
ownCloud log (data/owncloud.log)

{"reqId":"VZL6A38AAAEAAG160AMAAAAF","remoteAddr":"192.168.6.128","app":"PHP","message":"Undefined variable: lastCheck at \/var\/www\/owncloud\/apps\/updater\/ajax\/channel.php#25","level":3,"time":"June 30, 2015 22:20:20"}

**Comment by derkostka** [comment]
to clarify: this seems to be no problem on master (checked the code diff just now). so consider this as a reminder not to forget for 8.1 :-)

**Comment by VicDeo** [comment]
@derkostka Thanks for the heads up.
@karlitschek we need a new tag for RC, the most recent is v8.1.0beta2 set on May 18

**Comment by VicDeo** [comment]
the message itself is fixed with https://github.com/owncloud/updater/commit/d489f1ff2b424dc1cb05cb59b427bba8635a91c8 on May 23

**Comment by karlitschek** [comment]
@VicDeo We plan to do another RC the next few hours and this one will have all the tags and bells and whistles :-)

**Comment by VicDeo** [comment]
done. Closing
