### ISSUE TITLE
Update ownCloud 8.0.4 -> 8.0.5 (-> 8.1)

### ISSUE THREAD

**Issue by floxyz** [owncloud/updater#151]
Hi,
I read that ownCloud 8.1 is available, so I wanted to update my installation via the Updater App - but it tells me only "Up to date". Currently I am running 8.0.4 on a vServer via Apache.
What can I check to find out where the problem lies? Should I look for any specific messages in the log file?

**Comment by RealRancor** [comment]
Updates via the updater app are always delayed for a few days. Ref: https://github.com/owncloud/updater/issues/111 and https://github.com/owncloud/updater/commit/3829ad6c2fe0e614fbef6ffffc99614c267c0513

**Comment by floxyz** [comment]
Ah, I thought I missed the release - but it was on the same day as 8.1.
Then it makes sense - thanks for the answer.

**Comment by christianromeni** [comment]
I'm sorry to open it up again.. But on my server the update is still not showing. Has it not been released yet? Or is there something wrong with my installation?

Greets.

**Comment by karlitschek** [comment]
should work now
