### ISSUE TITLE
Funny message

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#153]
Funny message from a couple minutes ago!

Any clue what it means ??

regards, hitam4450

![bildschirmfoto vom 2015-07-11 11 39 44](https://cloud.githubusercontent.com/assets/9738727/8633306/b98cbcc8-27c1-11e5-9c78-e4457bbdecf0.png)

**Comment by j-ed** [comment]
It might be worse to read the ownCloud documentation:
https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html

**Comment by RealRancor** [comment]
Updates via the updater app are also always delayed a few days. The updater app shipped with oC 8.0.5 / 8.1.0 will finally show this to avoid having to answer such questions after every release.

**Comment by hitam4450** [comment]
Thank you for your enriching answer and advice. I am now using OwnCloud since version 6.0 & i am quite familiar with the procedures of upgrading OwnCloud by now

I wanted to point more to the (incomplete) message Updates !  No updates, New Updates, etc ???????

Thank you very much for your guidance through "my update process" with OwnCloud!

regards, hitam4450

**Comment by RealRancor** [comment]
@hitam4450 As already written above the message was already changed in oC 8.0.5 and 8.1.0 as already discussed in your existing issue: https://github.com/owncloud/updater/issues/111

**Comment by VicDeo** [comment]
@RealRancor IIRC, it's not ported to 8.0.
https://github.com/owncloud/updater/pull/114

and I wouldn't mind if someone will interpret response like https://apps.owncloud.com/updater.php?version=8x2x14x1338030373.1628x1373617342.3379xstablex better than me. Just submit the PR.

**Comment by RealRancor** [comment]
@VicDeo Ah, sorry. Thought it was also backported to stable8 but i was wrong.

**Comment by hitam4450** [comment]
Now, after 26 days releasing OC 8.1 and OC 8.05 the updater (OC 8.04) still does not show any Updates !

This is more then funny...I think it is a mess!
Regards, hitam4450

**Comment by VicDeo** [comment]
well, you have 3 options still:
- update manually
- use your favorite distro package manager for that
- help improve web updater

**Comment by karlitschek** [comment]
The updater will be activated for 8.1.1 We found a few serious bugs in 8.1.0 that we want to fix first.

**Comment by VicDeo** [comment]
Regarding your screenshot above: it means that last request to the update server was sent on July 11 and update server reported back `there are no updates`
I don't see how this is related with the app sending the request.

**Comment by RealRancor** [comment]
> The updater will be activated for 8.1.1 We found a few serious bugs in 8.1.0 that we want to fix first.

Was this also detected for oC 8.0.5 because this version is currently also not reported to the updater. We're getting tons of questions at the forums, mailinglist, IRC and also at the owncloud.org blog about that.

**Comment by VicDeo** [comment]
Related to https://github.com/owncloud/appstore-issues/issues/4#issue-39099299

**Comment by hitam4450** [comment]
Well, the last screen-shot was taken a minute before posting!

**Comment by VicDeo** [comment]
ok, a postman is always to blame for not delivering the message that has not been sent yet.

**Comment by hitam4450** [comment]
never mind.......

**Comment by hitam4450** [comment]
@VicDeo Thanks for your advice. Manual update is like a 'new installation'.

**Comment by VicDeo** [comment]
@hitam4450 
1. backup db.
2. wget owncloud-x.y.z.zip
3. unzip owncloud-x.y.z.zip (owncloud dir is created)
4. mv owncloud owncloud-x.y.z
5. 
cp -aR old/config owncloud-x.y.z/config 
cp -aR old/data owncloud-x.y.z/data
6. ./occ upgrade
7. switch server webroot to owncloud-x.y.z

**Comment by hitam4450** [comment]
@VicDeo 
Thanks again for your advice. I'll keep it in mind for next time.

**Comment by VicDeo** [comment]
@hitam4450 I slightly updated it as `config.php` will  have a path to an old data dir. You can change path to a data dir in config.php and move it to owncloud-x.y.z at any time. E.g. after migration testing is  completed.

**Comment by VicDeo** [comment]
8.1.1 is out
