### ISSUE TITLE
Daily update channel doesn't work

### ISSUE THREAD

**Issue by karlitschek** [owncloud/updater#157]
The daily update channel doesn't work. The reason is that the ownCloud version number doesn't change every day. We have to additionally check the build number to trigger the daily updates.
For this we need to:
- Send the build number to the update server
- Trigger an update if a new build is available.

**Comment by DeepDiver1975** [comment]
@karlitschek as per our discussion last friday there is nothing to be done in the updater - right? THX

**Comment by karlitschek** [comment]
correct. this needs to be fixed in the infrastructure.

**Comment by DeepDiver1975** [comment]
> correct. this needs to be fixed in the infrastructure.

can we close this then - or do you want to keep this open as reminder for the infra fix? @karlitschek THX

**Comment by karlitschek** [comment]
let's keep it open util it is fixed

**Comment by rperezb** [comment]
hey @DeepDiver1975 is the 8.1.1 milestone right?

**Comment by DeepDiver1975** [comment]
yes

**Comment by karlitschek** [comment]
works now.
