### ISSUE TITLE
Owncloud 8.0.5 not detected by the Updater.

### ISSUE THREAD

**Issue by zubanst** [owncloud/updater#160]
Owncloud 8.0.4, Updater 0.4 plug-in enabled; cron running and OK. Although version 8.0.5 seems available since July 6, it is not detected by the Updater.

**Comment by RealRancor** [comment]
8.0.5 is not released for the updater -> not an issue with the updater itself. Ref: https://github.com/owncloud/updater/issues/153

**Comment by zubanst** [comment]
OK. Then I close the issue. Do you know when it would be released?

**Comment by RealRancor** [comment]
Unfortunately there is still no official word if and when 8.0.5 will be released. However 8.1.1 and 8.0.6 should be available in the next few days which are hopefully release the via the updater
