### ISSUE TITLE
Upgrade to OC 8.1.1 failed

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#162]
A few minutes ago i received a message that for my current OC 8.0.5 installation, that an upgrade was available.

I selected Administration --> Updater -->> update and hit the button at once!

However during the 3rd step I received the following message:

Unable to move /media/www/servers/owncloud.ibt-global.net/_oc-upgrade/8.1.1.3/core/ocs-provider to /media/www/servers/owncloud.ibt-global.net/ocs-provider
And the cursor keeps spinning ........until eternity!

What went wrong & Why ??

After refreshing the tab in FF 39 I received the possibility of hitting the update button once again!

Note: The update of the OC 8.1 test installation went flawless!
regards, hitam4450

**Comment by VicDeo** [comment]
@hitam4450 recent entries from Updater app at the Log section will be helpful

**Comment by hitam4450** [comment]
enclosed you'll find the logs:
 Error 	PHP 	rmdir(/tmp/oc_tmp_bdc0b8b70fed89541ece754acd098040): Directory not empty at /media/www/servers/owncloud.ibt-global.net/lib/private/helper.php#441 	2015-08-11T17:54:08+00:00
Error 	PHP 	rmdir(/tmp/oc_tmp_bdc0b8b70fed89541ece754acd098040/news): Directory not empty at /media/www/servers/owncloud.ibt-global.net/lib/private/helper.php#435 	2015-08-11T17:54:08+00:00
Error 	PHP 	rmdir(/tmp/oc_tmp_bdc0b8b70fed89541ece754acd098040/news/vendor): Directory not empty at /media/www/servers/owncloud.ibt-global.net/lib/private/helper.php#435

**Comment by VicDeo** [comment]
@hitam4450 Is there `ocs-provider` directory in your current OC instance. If yes, what are its permissions and owner?

**Comment by hitam4450** [comment]
FYI:
drwxr-xr-x  2 www-data www-data  4096 Aug 11 19:01 ocs-provider

**Comment by VicDeo** [comment]
@hitam There is no `ocs-provider` in OC8.0 https://github.com/owncloud/core/tree/stable8

Can you check if it's content matches OC8.1 https://github.com/owncloud/core/tree/stable8.1/ocs-provider ?

If your ownCloud still claims to be 8.0.5 at the admin page just remove `ocs-provider` dir and retry

**Comment by hitam4450** [comment]
@VicDeo Thanks for your help, but the 8.0.5 installation does not exist anymore!

Currently I use 8.1.1 for stable use and 8.1.2 for experimental and debugging!

Anyhow, many thanks for your help

regards, hitam4450

**Comment by VicDeo** [comment]
ok, closing
