### ISSUE TITLE
Upgrade zip extraction error

### ISSUE THREAD

**Issue by rockihack** [owncloud/updater#163]
I tried to upgrade my 8.0.4 instance to 8.1.1 and update process got stuck
and showed "zip extraction error".
8.1.1.3.zip was empty (0bytes)

`wget https://download.owncloud.org/community/owncloud-8.1.1.zip`
Auflösen des Hostnamen »download.owncloud.org (download.owncloud.org)«... 209.126.100.233, 144.76.105.220
Verbindungsaufbau zu download.owncloud.org (download.owncloud.org)|209.126.100.233|:443... fehlgeschlagen: Die Wartezeit für die Verbindung ist abgelaufen.

*Reason:*
- Connection errors are not properly handled
- DNS contains ip which refuses connections

*Solution:*
- Download zip manually to: `/owncloud/data/updater_backup/8.1.1.3.zip`
- Restart updater

**Comment by karlitschek** [comment]
can't reproduce. maybe a server hickup. I suggest to try again.

**Comment by rockihack** [comment]
You're right that the DNS problem was a temporary problem,
but thats not the point! I will explain it again.

1. Check for false (type sensitive)
`if (self::fetch($url)===false)`
https://github.com/owncloud/updater/blob/e0f33da2cd3e31f6723290a2d062be5375422632/lib/downloader.php#L38

2. Use of fopen *WITHOUT* checking return value...
`$result = @file_put_contents(self::$package, fopen($url, 'r'));`
https://github.com/owncloud/updater/blob/e0f33da2cd3e31f6723290a2d062be5375422632/lib/downloader.php#L101

3. Problem
Warning: fopen(https://download.owncloud.org/community/owncloud-8.1.1.zip): failed to open stream: Network is unreachable

You can see that fopen doesn't work and return *FALSE*, because the return value is not checked
it's passed to file_put_contents which returns 0 (int).
Now look at success check for self::fetch($url).
It only tests if fetch returned *FALSE*, but in this case fetch failed and returned 0!
An empty file is created and the zip extraction fails.

I already wrote "Connection errors are not properly handled" and you can't reproduce it if the network is reachable of course. Hopefully you check the return value of fopen and fix this error which implies another error and leads to an misleading error message.

**Comment by karlitschek** [comment]
@rockihack True. Do you want to help by submitting a pull request for that?

**Comment by VicDeo** [comment]
Preferably closing https://github.com/owncloud/updater/issues/140 with it ;)
As I will close it next weeks anyway

**Comment by rockihack** [comment]
Please add a error message "Network is unreachable".
I also recommend to add "network problems" to the testing guide
and/or create a unit test with a mock-object for fopen / file_put_contents
to simulate network problems.
