### ISSUE TITLE
Provide option for initiating the backup of 'user data'

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#165]
Hi,

to minimize the loss of user data & hassle to restore them because of missed backup before invoking an update of OC, it would be most advantageous to provide a tool to the administrator on the Update page:

1. To provide a button, which initiates a simple back e.g. copying the user data to a 
     different - predefined -location (hard drive, volume, Server, etc.)
2. Or to provide a push button, from where the administrator is able to invoke his favorite backup script or     
    program.

regards, hitam4450

**Comment by tflidd** [comment]
There is a backup app (only for the database so far): https://apps.owncloud.com/content/show.php/OwnBackup?content=170674

There are so many good tools for backups, I don't know if it is worth investing time in programming a solution in php.

**Comment by RealRancor** [comment]
An "Updater" app should never be responsible for something like an Backup in my opinion. :see_no_evil:

**Comment by te-online** [comment]
@hitam4450 Well, your ideas/descriptions are more than understandable and legitimate. But as @RealRancor and @tflidd stated the updater is not responsible for the task of backups. This is a separate task, accomplished ideally by a different app. That a backup of the core files is done can only be seen as a *nice extra*.

I'm not sure if we should add this as a »in-the-future-maybe-/-maybe-not-let's-see-enhancement« or just close this one and focus on the main functionality. @hitam4450 Maybe you could input your ideas at the existing backup app (https://github.com/pbek/ownbackup)?

**Comment by DeepDiver1975** [comment]
out of scope of the updater
