### ISSUE TITLE
When Owncloud update is available Owncloud instance should send an email to the admin. 

### ISSUE THREAD

**Issue by farson2003** [owncloud/updater#167]
Suggestion:
When Owncloud update is available Owncloud instance should send an email to the admin.

**Comment by RealRancor** [comment]
@farson2003: Why create an issue in core and also here? https://github.com/owncloud/core/issues/18646 One should be enough as this is also a duplicate of https://github.com/owncloud/core/issues/17373

**Comment by farson2003** [comment]
This issue here is definetely not a duplicate of owncloud/core#17373

What I am addressing here is not an email notification for an Owncloud application, but for an update of Owncloud itself (i.e. 8.0.0 to 8.0.1. and so on).

Hope that is understandable.

**Comment by RealRancor** [comment]
Ah, sorry. You're right. But as core is handling available updates (the updater app even might not be installed on many installs) you should re-open in https://github.com/owncloud/core/issues

**Comment by farson2003** [comment]
Reopened here: https://github.com/owncloud/core/issues/18696
