### ISSUE TITLE
app directory not found after update

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#169]
I wanted to activate the weather app in OC 8.1.2 - but i received the following message:
(see enclosed screen shot)
![oc8 1 2 b](https://cloud.githubusercontent.com/assets/9738727/9633931/81cff8ca-518f-11e5-8cf2-ffc56fa42a18.png)
regards, hitam4450

**Comment by VicDeo** [comment]
@hitam4450 great. please contact the app vendor and ask him to repack the app.
Its package doesn't contain a directory that has the same name as an app titled.
`owncloud-weather-1.2.0` should be just `weather`

**Comment by RealRancor** [comment]
@hitam4450 Btw. the updater app is not responsible for updating/activating apps.

**Comment by hitam4450** [comment]
Well, if not the updater  app - which app is responsible and takes care of  updating / activating apps??

**Comment by RealRancor** [comment]
This is the job of https://github.com/owncloud/core/

**Comment by hitam4450** [comment]
Thank you for highlighting me!

Since i am only an OC user and not a developer, i am not yet familiar with the internals, yet !    :-)
regards, hitam4450

**Comment by RealRancor** [comment]
In case of the updater app you can also have a look at its description what the app itself is doing: https://github.com/owncloud/updater/blob/master/README.md

**Comment by nerzhul** [comment]
Hello i will host my package out of github, this cause issues

**Comment by VicDeo** [comment]
@nerzhul you can upload a properly packed zip as a release binary https://help.github.com/articles/creating-releases/
