### ISSUE TITLE
Iterative update

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#17]
@schiesbn is suggesting that for people who use the updater app, the update should be iterative: 6.0.1 then 6.0.2 then 6.0.3, etc to make sure that all update scripts run in the correct order because some scripts might only run for example between 6.0.2 and 6.0.3.

This is mostly assuming that the updater app is used by less tech-savvy people.
Such iterative update path is not possible when using distro package managers.

I'm not convinced that it's a good idea and think that update code needs to support update paths like 6.0.1 to 6.0.4.

But let's discuss @karlitschek

**Comment by te-online** [comment]
So, this can be closed?

**Comment by RealRancor** [comment]
@te-online Yes, i think this could be closed as this just needs to be fixed at updater url level as discussed in https://github.com/owncloud/appstore-issues/issues/4

**Comment by VicDeo** [comment]
@PVince81 closing this issue as it is better to implement on the update server side

**Comment by RealRancor** [comment]
@VicDeo Its already implemented at the update server side: https://github.com/owncloud/appstore-issues/issues/4 :-)
