### ISSUE TITLE
layout on admin page not optimal

### ISSUE THREAD

**Issue by karlitschek** [owncloud/updater#170]
The layout of the updater app on the admin page is a bit over complicated and messy. It should be only one section and only show the information and buttons that are currently necessary.
Also the grey  background is ugly. ;-)

![order](https://cloud.githubusercontent.com/assets/867445/9655464/634047aa-5231-11e5-8a86-475c467d7eec.jpg)

**Comment by karlitschek** [comment]
@VicDeo @jancborchardt can you help?

**Comment by hitam4450** [comment]
I certainly agrre to the suggestion!  :-)

regards, hitam4450

**Comment by jancborchardt** [comment]
@te-online @VicDeo do you want to improve that here? The backups part should only be a h3 and no extra section div as to not separate it so much from the update part.

**Comment by raghunayyar** [comment]
Can take care of this over the weekend. Looking for some quick fixes. ;)

**Comment by jancborchardt** [comment]
Great stuff @raghunayyar – perfect to focus on the quick fixes for 8.2! :)

**Comment by te-online** [comment]
@jancborchardt @raghunayyar Well, are you sure? I think I created this as an extra section, because it is an extra task. But proof me wrong :wink:

**Comment by jancborchardt** [comment]
@te-online it’s done by the same app, and apparently very related since one says »Updater-Backups«. ;) Hence it should be in the same section layout-wise.

**Comment by te-online** [comment]
@jancborchardt If you say so :wink: 
Seriously: I am okay with combining it :+1:

**Comment by te-online** [comment]
> The layout of the updater app on the admin page is a bit over complicated and messy. It should be only one section and only show the information and buttons that are currently necessary.
Also the grey background is ugly. ;-)

@karlitschek It was me responsible for the ugly background :smile:
The aim was to make sure the user reads the note (see #105), my aim was not to make it ugly – which is obviously true.

@jancborchardt Call me too lazy to search, but you probably know it: Is there a go to place in the documentation that speaks about available formatting options for the backend? I'm always lost if things get more complicated than a heading and a paragraph. And obviously I don't want to introduce different stylings each time.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/updater/pull/171 – @raghunayyar good work! :)
