### ISSUE TITLE
Reduce amount of text in updater settings section to make it easier to understand

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/updater#172]
Similar to https://github.com/owncloud/updater/issues/170

There’s still a lot of text in the updater section:
![u](https://cloud.githubusercontent.com/assets/867445/9800510/52cba180-57db-11e5-82bf-befa536ac75d.jpg)

We should think about how to reduce that and make it simpler. @owncloud/designers @te-online @VicDeo thoughts?

For example:
* the »Please note update is possible only to a version greater than the current one etc…« block of text can be cut and made into a tooltip of an »i« info button next to the dropdown.
* same for the »Updates will be available within a few days bla bla … if we need that clarification at all
* the whole updater backup note is strange – what is the backup function good for if a separate backup should be done anyway? Sure it could fail, but yeah …

**Comment by karlitschek** [comment]
Yes. I agree!

**Comment by jancborchardt** [comment]
Setting to 8.2 cause we’re ambitious. @VicDeo @te-online does anyone of you want to work on that? :)

**Comment by VicDeo** [comment]
@jancborchardt I'm busy with core before freeze.
As for `same for the »Updates will be available within a few days bla bla … if we need that clarification at all` I will left you with a pleasure to respond to each and every `WHY? I? DON'T? SEE? UPDATE?` on your own. ;)
They are appearing after each release here and in core

**Comment by VicDeo** [comment]
latest are
https://github.com/owncloud/updater/issues/153
https://github.com/owncloud/updater/issues/156
https://github.com/owncloud/updater/issues/160

**Comment by jancborchardt** [comment]
@VicDeo ah ok! Then still we can reword to:

> (Updates will be available a few days after the update announcement.)

In parentheses, on the same line as the »Up to date.« And the info about »Last checked on 9 September etc« can be a tooltip on the »Up to date.« text. Ok?

**Comment by te-online** [comment]
@jancborchardt @karlitschek I would love to reword the messages and also make them a bit more fun to read (a bit less technical). I'll see what I can do today or tomorrow. I think your suggestion in https://github.com/owncloud/updater/issues/172#issuecomment-139578590 is a really good start.

Concerning the **note** @jancborchardt: It it very important to understand that an updater backup does not include any owncloud-storage-data! In my opinion, this has to be absolutely clear, because you would expect the feature to do a **complete** backup otherwise (see https://github.com/owncloud/updater/issues/165). By the way: I introduced that here #40 and no-one complained – yet, I agree that there is too much text in general.

**Comment by te-online** [comment]
@karlitschek @jancborchardt @VicDeo 
What do you think about this? (Please ignore that I did this mockup with 8.1 where there are still two separate sections. :wink:)

<img width="835" alt="bildschirmfoto 2015-09-12 um 11 46 12" src="https://cloud.githubusercontent.com/assets/4127167/9830966/3132a612-5944-11e5-8bbe-2ac67814c9cc.png">

I would like to add the »Checked on...« and maybe the »Backup directory« as a tooltip. Is there any visual hint you could place for that? The »i« is always for the links to documentation, I think?

**Comment by karlitschek** [comment]
nice improvement IMHO!  :+1:

**Comment by karlitschek** [comment]
what do you think @VicDeo @jancborchardt ?

**Comment by jancborchardt** [comment]
@te-online yess, awesome! :) Is there a pull request?

**Comment by te-online** [comment]
@jancborchardt No, but I will create one. :+1:  

Do you think people translating can catch up on so many changes at once – and do you think the information are in general accurate? 

And one last thing: Do you know anything about the tooltips I mentioned?

**Comment by cmonteroluque** [comment]
@VicDeo can you review the PR please?

**Comment by cmonteroluque** [comment]
can we close this one?

**Comment by te-online** [comment]
I hope so.
