### ISSUE TITLE
Show notification of major versions also

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/updater#186]
I'm on v8.1.3 with the updater app installed and enabled. Version 8.2 has been out for 2 weeks, and yet I see no notification. My server can wget from https://apps.owncloud.com/updater.php?version=4x90x14x1338030373.1628x1373617342.3379xstablex just fine.

My understanding is that the updater app is only for upgrading point releases, and so I'm guessing it doesn't show notifications of major releases.

It seems to me though that if a user sees "Your installation is up to date" though that they would expect that there aren't any more recent major releases. Accordingly I suggest that major releases still get a notification, even if we just say something like "ownCloud upgrade x.y is available! (This version requires a manual upgrade)"

**Comment by RealRancor** [comment]
@Bugsbane 

> Major updates are delayed up to one month until they are served by the updater application.

https://github.com/owncloud/updater/issues/183

**Comment by VicDeo** [comment]
This is a common issue that is appearing again and again. 
Updater has no `lib_astral.so` so it just queries the core which sends a request to the update server.
This is neither a bug not a lack of feature. The decision when to make an announcement via web UI is out of responsibility of this app.
