### ISSUE TITLE
Unable to move /srv/http/owncloud/_oc-upgrade/8.2.1.4/core/resources to /srv/http/owncloud/resources

### ISSUE THREAD

**Issue by HLFH** [owncloud/updater#189]
Hi,

When I'm trying to upgrade from 8.2.0 to 8.2.1, I got the following issue:
![upgrade](https://cloud.githubusercontent.com/assets/2359059/11277332/72474586-8ee6-11e5-9c18-aac38bb2ec61.PNG)

And also with "Something went wrong for core. Rolling back." in the logs.

Thanks,
HLFH

**Comment by Gurkengewuerz** [comment]
Same here

**Comment by VicDeo** [comment]
Does `/srv/http/owncloud/resources` exist?

**Comment by HLFH** [comment]
@VicDeo Yes `/srv/http/owncloud/resources` exists.

**Comment by Commifreak** [comment]
Exactly same here!

```
root@s1:/opt/owncloud_data# cat owncloud.log 

{"reqId":"IRfO4gsXNA0TWhSMCHcc","remoteAddr":"79.249.156.26","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-11-19T23:22:27+00:00"}
{"reqId":"lmV9NfC+K6qzpzmVLhjP","remoteAddr":"79.249.156.26","app":"PHP","message":"rename(\/var\/customers\/webs\/kluthr\/cloud.kluthr.de\/_oc-upgrade\/8.2.1.4\/core\/resources,\/var\/customers\/webs\/kluthr\/cloud.kluthr.de\/resources): Directory not empty at \/var\/customers\/webs\/kluthr\/cloud.kluthr.de\/apps\/updater\/lib\/helper.php#52","level":3,"time":"2015-11-19T23:22:27+00:00"}
{"reqId":"lmV9NfC+K6qzpzmVLhjP","remoteAddr":"79.249.156.26","app":"updater","message":"Something went wrong for core. Rolling back.","level":3,"time":"2015-11-19T23:22:27+00:00"}
{"reqId":"lmV9NfC+K6qzpzmVLhjP","remoteAddr":"79.249.156.26","app":"updater","message":"Unable to move \/var\/customers\/webs\/kluthr\/cloud.kluthr.de\/_oc-upgrade\/8.2.1.4\/core\/resources to \/var\/customers\/webs\/kluthr\/cloud.kluthr.de\/resources","level":3,"time":"2015-11-19T23:22:29+00:00"}
{"reqId":"lmV9NfC+K6qzpzmVLhjP","remoteAddr":"79.249.156.26","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-11-19T23:22:29+00:00"}
```

The underlaying v8.2 installation was fresh from zip (manual upgrade, only settings copied).

resources exist, it has a folder named config in it.

```
root@s1:/var/customers/webs/kluthr/cloud.kluthr.de/resources# find
.
./config
./config/ca-bundle.crt
./config/mimetypemapping.dist.json
./config/mimetypealiases.dist.json
```

**Comment by ollihart** [comment]
same problem this morning. Solution: Simply empty subfolder "resesources" (or  make a copy of ressources and then empty ressources) and then the update runs smoothly

regards ...

**Comment by PVince81** [comment]
The resources folder already existed in 8.2.0 and also exists in 8.2.1, so not sure why it would fail here.

However I see that it did **not** exist in 8.1 and was possibly added recently.
@VicDeo does the updater app have a list of known folders ? Maybe this folder is missing there ?

**Comment by mistersixt** [comment]
When trying to empty the resources folder as suggested by "ollihart" I get a warning that no internet connection can be found, so I moved back the config folder to the resources folder, the warning then disappears, but I no longer get an update notification, it is saying that I am on the latest stable version with 8.2.0.

Any ideas or hints?

Thanks, Joerg.

**Comment by RealRancor** [comment]
@PVince81 Yes, the updater has a list of files and folders here:

https://github.com/owncloud/updater/blob/v8.2.1/lib/files.json#L1-L29

Strange that the resources folder is in there.

**Comment by chazz9R** [comment]
Go To oc dir/apps/updater/lib
open files.json and add under

8.1 the directory "resources".

Then it works.

**Comment by JB1985** [comment]
@chazz9R 

thanks! Its working!

**Comment by PVince81** [comment]
@VicDeo can we make this permanent for 8.1.5, if that makes sense ?

**Comment by Gurkengewuerz** [comment]
@chazz9R
thanks! works without problems

**Comment by RealRancor** [comment]
@PVince81 From what i can see the /resources folder is not included in 8.1.x so the questions is more why is it needed that this folder is added to the files.json for 8.1.

**Comment by VicDeo** [comment]
@RealRancor and the answer is https://github.com/owncloud/updater/issues/191

**Comment by VicDeo** [comment]
Fix is simple https://github.com/owncloud/updater/pull/192/files

**Comment by JaoNoctus** [comment]
Thanks! It works!

> Go To oc dir/apps/updater/lib
> open files.json and add under
> 8.1 the directory "resources"

**Comment by Paul-Reed** [comment]
OK found files.json  
What exactly do I add? - "resources", "/resources" or the full path from root  
Paul

**Comment by RealRancor** [comment]
@Paul-Reed You just need this fix: https://github.com/owncloud/updater/pull/192/files without modifying the files.json.

**Comment by Paul-Reed** [comment]
@RealRancor Thanks, I edited the file as per https://github.com/owncloud/updater/pull/192/files and re-run the upgrade which went well this time - no errors.

**Comment by Rouzax** [comment]
@RealRancor, not really sure what I should do with the core.php file, should I replace that in my current install and if so were?

**Comment by RealRancor** [comment]
@Rouzax You just need to edit the /path/to/owncloud/apps/updater/lib/location/core.php and make the changes from https://github.com/owncloud/updater/pull/192/files

**Comment by aurelien1402** [comment]
Thanks @ollihart it did the trick! Just empty the folder /owncloud/resources fixed the problem.

**Comment by damianetienne** [comment]
Thanks @Paul-Reed this seems to be the solution.

**Comment by boyan-sharic** [comment]
@chazz9R 
Thank you, it works.

**Comment by Ark74** [comment]
If you use the php install script, this issue happens everytime you make a new oc instance.

Does the fix in https://github.com/owncloud/updater/pull/192/files will hit the php script?

**Comment by madmas** [comment]
@VicDeo thanks a lot, that patch worked :+1:

**Comment by Gurkengewuerz** [comment]
Same Error again with owncloud 8.2.1 to 8.2.2

**Comment by RealRancor** [comment]
@Gurkengewuerz Which is normal as the fix was only shipped within the 8.2.2 version of the updater app.

**Comment by hitam4450** [comment]
Error is still available.......... :tired face:

**Comment by RealRancor** [comment]
@hitam4450 It help to read all comments, especially the one above yours ;-)

**Comment by hitam4450** [comment]
Thanks for your advice ! :smile:
The solution offered from @chazz9R made it work smoothly!

**Comment by rgasparfin** [comment]
@chazz9R 
Nice ! It worked for me.

Thanks a lot. =)

**Comment by janvlug** [comment]
Today, I ran into this issue, so should it really have the close status?

**Comment by VicDeo** [comment]
@janvlug Fix https://github.com/owncloud/updater/pull/191/files
