### ISSUE TITLE
"Error PHP Array to string conversion"

### ISSUE THREAD

**Issue by terokorp** [owncloud/updater#193]
at file https://github.com/owncloud/updater/blob/master/controller/admincontroller.php#L52 $feed['versionstring'] is empty array and suposed to be string. That causing PHP error at https://github.com/owncloud/core/blob/master/lib/private/template/functions.php#L36
( caled at https://github.com/owncloud/updater/blob/master/templates/admin.php#L23 )

ownCloud 8.2.1 (stable)

**Comment by terokorp** [comment]
Maybe related to #184

**Comment by VicDeo** [comment]
Closing as a duplicate of https://github.com/owncloud/updater/issues/133
