### ISSUE TITLE
Check downloaded archive with GPG.

### ISSUE THREAD

**Issue by ypid** [owncloud/updater#194]
See https://github.com/jchaney/owncloud/pull/12 for details. Every good sysadmin should check signatures. I am going to disable usage of the updater in [jchaney/owncloud](https://github.com/jchaney/owncloud) (but for [a different reason](https://github.com/jchaney/owncloud/issues/37)).

**Comment by VicDeo** [comment]
@ypid TBD soon. Not for entire package but for extracted sources.
 See https://github.com/owncloud/core/pull/22170
