### ISSUE TITLE
Can't open updater when asset-pipeline.enabled

### ISSUE THREAD

**Issue by codebucketdev** [owncloud/updater#195]
Hello,

I have installed ownCloud version 8.2 and today I got a notification about a new update to 8.2.1, so I went to the Admin page to update ownCloud to 8.2.1, but because I have the option asset-pipeline enabled, the update section on the admin page is broken (see issues on owncloud/core, there is a lot of them) and cant click on it to update. 

So, how can I update ownCloud now? Is there perhaps a URL to the update app?

**Comment by karlitschek** [comment]
please see owncloud.org/support for several places to ask this question. thanks a lot.

**Comment by RealRancor** [comment]
Also a dup of https://github.com/owncloud/updater/issues/184
