### ISSUE TITLE
No backup files listed 

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/updater#197]
@peterkahl reported in [core](https://github.com/owncloud/core/issues/20721):

> OS 8.2.1 shows no backups, although they exist in the exact same directory.
![no-backups](https://cloud.githubusercontent.com/assets/2703373/11387410/1f863590-9365-11e5-887e-9514cdaf9bd5.png)

**Comment by VicDeo** [comment]
might be related to #184

**Comment by VicDeo** [comment]
@peterkahl is it still reproducible?

**Comment by peterkahl** [comment]
Related to #184. Since I dsabled the setting described in #184, the issue has gone.

**Comment by VicDeo** [comment]
@peterkahl thanks, than  https://github.com/owncloud/updater/issues/184 should fix it regardless the `pipeline` option state

**Comment by VicDeo** [comment]
oops I mean https://github.com/owncloud/updater/pull/198

**Comment by peterkahl** [comment]
My version is 8.2.2, so I need to try re-enabling the pipeline setting. Thanks!

**Comment by VicDeo** [comment]
@peterkahl please let me know if it works now

**Comment by peterkahl** [comment]
Yes. I have set
```
'asset-pipeline.enabled' => true
```
and verified that the backup files are listed now with OC 8.2.2.2.
Thanks.

**Comment by VicDeo** [comment]
Thanks, closing then
