### ISSUE TITLE
Updater should be able to execute external (own) sript

### ISSUE THREAD

**Issue by hitam4450** [owncloud/updater#202]
Hello Developer community of OwnCloud,

How about the idea, to provide a possibility that the Updater provides a possibility to execute an external (own) script (e.g. php, shell, perl, etc) at a given point of the update process??

I am looking forward to discussing with you!

Have a Nice, relaxing Sunday!

regards, hitam4450

**Comment by mmattel** [comment]
:+1:

I extend this to a pre and a post script possibility
Because we have to:
- set proper permissions pre running the update
- reset proper permissions when the update has finished

**And** thinking that we may have to use superuser rights, we may want to ask in a field in the admin page for the superusers password which we pass to the script...

**Comment by VicDeo** [comment]
It will be possible to wrap CLI application call inside own bash (or any other) script

**Comment by mmattel** [comment]
@VicDeo 
For sure beeing to stupid, but would you mid to describe how / where this can be done. I have not found a description for. The updater app does not give me a place where to add external pre/post scripts...

**Comment by VicDeo** [comment]
via CLI:
```
preupgradescript.sh
sudo -u wwwrun php /path/to/owncloud/updater/application.php 
postupgradescript.sh
```

**Comment by mmattel** [comment]
Thx, got that.
But is there also a way to define the scripts you want to pre/post run when you use the updater app via the browser?

**Comment by mmattel** [comment]
Because when checking for a build, I am able to start the update process from there, and at this point I need to run the scripts manually from a shell = parallel administration...

**Comment by DeepDiver1975** [comment]
This needs really in depth thinking - we would need different handlings depending on the execution mode: web vs cli.

I'm not really convinced
