### ISSUE TITLE
Seagate PersonalCloud v6 -> v8 / Manual install with .rbw (Ruby on Windows)?

### ISSUE THREAD

**Issue by greenlib** [owncloud/updater#209]
I have a Seagate PersonalCloud, and it provided a one-touch install for ownCloud, which installed v6. I'm getting the yellow alert bar, which says that v8 is available.

I went to the Updater and tried to update, but I got the (apparently common) notification:
"Upgrade is not possible. Make sure that your webserver has write access to the following files and directories:"

I looked at the download from the Seagate website, and it's a FILE.RBW (Ruby on Windows) file, if you want to install it manually. However, the FILE.RBW is apparently preset with v6 - it doesn't even give you the option to update to v8. I also can't update from the Seagate PersonalCloud UI, which uses 192.168.2.7. It just doesn't even say that there's an update available, so I'm trying to update it manually, without a FILE.RBW being available.

I don't know Ruby. Do I have to learn Ruby, and then take ownCloud v8 and... Rubify... it, or is there a v8 .RBW already available somewhere, that I can just import into my Seagate PCloud and reinstall? When opening the drive from My Computer, and even choosing to view the hidden files, I don't see the installation of the PCloud, so I can only think of .RBW being my only available option, or am I wrong?

**Comment by VicDeo** [comment]
Unfortunately I have no idea how to upgrade in your particular case. I'm not familiar with this kind of distribution (packing PHP code into rbw).

**Comment by karlitschek** [comment]
This is a packaging issue on the Seagate side. Nothing wer can fix in ownCloud here. Please contact Seagate or the packager.
