### ISSUE TITLE
Updater tries to skip major versions (8.0)

### ISSUE THREAD

**Issue by varesa** [owncloud/updater#210]
I was running a 8.0.4 instance and got a nice notification to upgrade to 8.2. I tried running the wizard but it failed since 8.0 -> 8.2 is an invalid upgrade path. 

I'm not sure if this is fixed in a later version but the updater should not try to skip major versions.

**Comment by RealRancor** [comment]
Nothing what can be done on updater app side. See https://github.com/owncloud/appstore-issues/issues/4

**Comment by RealRancor** [comment]
See also this duplicate: https://github.com/owncloud/updater/issues/30

**Comment by nalt** [comment]
@RealRancor: Why is there nothing that can be done on the updater app? I would say it is certainly a bug in the updater if it propses an operation which will inevitably fail. #4 has been open for a long time now, so maybe it is simpler to do a check in the updater app.

**Comment by RealRancor** [comment]
@nalt 

> No. Supporting this means storing a list of all owncloud packages already released somewhere.
That's why https://github.com/owncloud/appstore-issues/issues/4 was opened more than a year ago.
Feed should not propose a package that is not suitable for update (imho).

from https://github.com/owncloud/core/issues/22129#issuecomment-179871811 describes this quite good.

**Comment by nalt** [comment]
I agree, the feed should not propose incompatible versions. So, until that happens, let's just call self_destroy() in our update routine ;-)

**Comment by VicDeo** [comment]
New update server is waiting to be merged. (in another repo). It will deliver  compatible versions only.

I came to updater-specific solution not long time ago but it is not straightaway so I'm happy that the issue will be resolved on a proper side.
