### ISSUE TITLE
Integrate updater further into Versions section

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/updater#212]
Now that we simplified the updater further and further, it's time that we put it directly into the versions section where it belongs.

The reasoning being that when your version is up to date (most of the time this will be the case), the app will simply display a message »up to date« next to the version in the Version section.

When there is an update, the message could be »Version 8.2.3 available« and a button »Update« next to it. On click, the section could expand to what it is now.

cc @karlitschek @te-online @VicDeo

**Comment by te-online** [comment]
@jancborchardt Great plan! :wink: But isn't the version section part of core?

**Comment by jancborchardt** [comment]
Yes it is. The updater should hook in there. How can we make that happen @DeepDiver1975 @karlitschek?

**Comment by DeepDiver1975** [comment]
But this is something we need to build into core - the updater has no integration point into core with respect to this feature request.

**Comment by jancborchardt** [comment]
Reopened in core at https://github.com/owncloud/core/issues/21691
