### ISSUE TITLE
Updater makes automatically an backup all 1 hours 

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/updater#218]
Hello, 

ownbackup makes all 1 hours automatically an backup. I don't know why. 

*Server*

Owncloud 8.2.2 
Php 5.5.9
mysql 

This is the log entry for this event:

Sicherheits- & Einrichtungswarnungen

All checks passed.
Teilen 
Anwendungen erlauben, die Share-API zu benutzen
Benutzern erlauben, Inhalte über Links zu teilen
Passwortschutz erzwingen
Öffentliches Hochladen erlauben
Benutzern erlauben, E-Mail-Benachrichtigungen für freigegebene Dateien zu senden
Standardablaufdatum einstellen
Weiterverteilen erlauben
Benutzer auf das Teilen innerhalb ihrer Gruppen beschränken
Benutzern erlauben, E-Mail-Benachrichtigungen für freigegebene Dateien an andere Benutzer zu senden
Gruppen von Freigaben ausschließen
Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.
Federated-Cloud-Sharing 
 Benutzern auf diesem Server das Senden von Freigaben an andere Server erlauben
 Benutzern auf diesem Server das Empfangen von Freigaben von anderen Servern erlauben	
Externer Speicher

Ordnername	Externer Speicher	Authentication	Konfiguration	Verfügbar für	 	 
 
Ordnername
 			

Externen Speicher für Benutzer aktivieren
Erlauben Sie Benutzern, folgende externe Speicher einzubinden
FTP 
WebDAV 
ownCloud 
SFTP 
Amazon S3 
Dropbox 
Google Drive 
Openstack-Objektspeicher 
SMB / CIFS 
Dateibehandlung

Maximale Upload-Größe 
1 GB
 (maximal möglich:2 GB) 
With PHP-FPM this value may take up to 5 minutes to take effect after saving.	
Speichern
Kontakte

 LDAP-Backend aktivieren
LDAP-Backend für die Kontakte-Anwendungen aktivieren 
Warnung: LDAP-Backend ist im Beta-Modus, mit Vorsichtsmaßnahmen verwenden
Dokumente

MS Word Unterstützung (benötigt OpenOffice/LibreOffice)
 Lokal
OpenOffice/LibreOffice ist auf diesem Server installiert. Der Pfad zur Binärdatei wird über preview_libreoffice_path in der config.php bereit gestellt.
 Extern
OpenOffice/LibreOffice ist auf einem externen Server installiert und läuft dort als Formatfilter-Server
 Deaktiviert
Keine MS Word Unterstützung

Übernehmen und Testen
News

 ownCloud-Cron für Aktualisierungen nutzen
Deaktivieren Sie dies, wenn Sie einen eigenen Updater sowie den Python-Updater aus der App laufen lassen
Säuberungssintervall
Minimum an Sekunden, nachdem gelöschte Feeds und Ordner aus der Datenbank entfernt werden; Werte unter 60 Sekunden werden ignoriert

60
Maximale Anzahl an einzulesende Feeds
Definiert die maximale Anzahl an Artikeln, die pro Feed gelesen und bei einem Säuberungsauftrag nicht aus der Datenbank gelöscht werden; wenn ältere Artikel nach dem Lesen erhalten bleiben sollen, erhöhen Sie diesen Wert; negative Werte sowie -1 deaktiviert diese Funktion komplett

200
Maximale Anzahl Weiterleitungen
Anzahl Weiterleitungen die der Feed-Sammler folgen soll

10
Maximale Seitengröße des Feeds
Maximale Feedgröße in Bytes. Wenn die RSS/Atom-Seite größer als dieser Wert ist, wird die Aktualisierung abgebrochen

104857600
Zeitüberschreitung Feed-Sammler
Maximale Anzahl Sekunden zum Laden eines RSS- oder Atom-Feeds; wenn dies länger dauert, wird die Aktualisierung abgebrochen.

60
Service-URL entdecken
Falls angegeben, wird die URL dieses Dienstes zur Feed-Anzeige innerhalb des Explore-Feed-Bereichs abgefragt. Lassen Sie dieses Feld unausgefüllt, um auf den eingebauten Explore-Dienst zurückzugreifen.

ocDownloader

Leave fields blank to reset a setting value
YouTube DL Binary Path 
/usr/local/bin/youtube-dl
Proxy settings
Proxy Address 
http://
Proxy Port  
8080
If no authentication is required by your proxy, leave the following fields blank
Proxy User  
Username
 Proxy Password  
Password
Only use proxy settings with YouTube-DL ? 
General settings
Check for updates ?  
WARNING !! Switching from ARIA2 to another downloader engine will remove all current downloads from ARIA2
Which downloader do you want to use ?  Available protocols: HTTP(S) / FTP(S) / YouTube
Max download speed ?  
10000
KB/s (empty or 0 : unlimited, default : unlimited)
Allow protocols for users (except for members of the admin group)
Allow HTTP ?  
Allow FTP ?  
Allow YouTube ?  
Allow BitTorrent ? No
OwnBackup

Your backups

Select the backup you want to restore tables from.
 Create Backup
Shorten

Which type of URL shortener to use:

The URL that contains the index.php file for the shortener. If you are unaware of what this file is, please read the installation instructions.

https://cloud.smartdroidblog.de
Mail-Vorlagen

Theme

Vorlage

Cron  Letzte Cron-Job-Ausführung: Vor 1 Minute.  
 AJAX
Eine Aufgabe bei jedem Laden der Seite ausführen
 Webcron
cron.php ist als Webcron-Dienst registriert, der die cron.php alle 15 Minuten per HTTP aufruft.
 Cron
Benutzen Sie den systemeigenen Cron-Dienst, um die cron.php alle 15 Minuten aufzurufen.
Serverseitige Verschlüsselung 
Serverseitige Verschlüsselung aktivieren 
Standard-Verschlüsselungs-Modul auswählen:

 Default encryption module 
Wiederherstellungsschlüssel deaktivieren	
Der Wiederherstellungsschlüssel ist ein zusätzlicher Verschlüsselungsschlüssel, der zum Verschlüsseln von Dateien benutzt wird. Er erlaubt die Wiederherstellung von Benutzerdateien auch dann, wenn der Benutzer sein Passwort vergessen hat.	

Wiederherstellungschlüsselpasswort
 
Passwort für den Wiederherstellungsschlüssel wiederholen
 Wiederherstellungsschlüssel deaktivieren

Wiederherstellungsschlüsselpasswort ändern	

Altes Passwort für den Wiederherstellungsschlüssel

Neues Passwort für den Wiederherstellungsschlüssel
 
Neues Passwort für den Wiederherstellungsschlüssel wiederholen
 Passwort ändern
E-Mail-Server 
Dies wird für das Senden von Benachrichtigungen verwendet.
Sendemodus  Verschlüsselung 
Absenderadresse 
cloud-email
@ 
smartdroidblog.de
Authentifizierungsmethode   Authentifizierung benötigt
Serveradresse 
smtp.strato.de
 :  
Port
Zugangsdaten 
Cloud-email@smartdroidblog.de
 
••••••••••••
 Anmeldeinformationen speichern

E-Mail-Einstellungen testen  E-Mail senden
Log

Log-Level 
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2016-01-23T15:00:02+01:00
Info	ownbackup	ownbackup removed backup 1453449602	2016-01-23T14:30:19+01:00
Info	ownbackup	ownbackup created a backup to '/mnt/usb/ocdata/ownbackup/1453555802'	2016-01-23T14:30:19+01:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2016-01-23T14:30:02+01:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2016-01-23T14:00:02+01:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	
2016-01-23T13:30:02+01:00
Info	ownbackup	ownbackup removed backup 1453445102	2016-01-23T13:15:19+01:00
Info	ownbackup	ownbackup created a backup to '/mnt/usb/ocdata/ownbackup/1453551302'	2016-01-23T13:15:19+01:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted
2016-01-23T13:00:02+01:00
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	
2016-01-23T12:30:01+01:00
Info	ownbackup	ownbackup removed backup 1453440602	
2016-01-23T12:15:19+01:00
Info	ownbackup	ownbackup created a backup to '/mnt/usb/ocdata/ownbackup/1453547701'

Is that normal?

**Comment by RealRancor** [comment]
Hi,

> Info ownbackup ownbackup removed backup

this is a 3rdparty app not related to the updater app here.

**Comment by VicDeo** [comment]
@Happyfeet01 if you are talking about https://apps.owncloud.com/content/show.php/OwnBackup?content=170674
please reopen in https://github.com/pbek/ownbackup/issues

It has nothing to do with updater app
