### ISSUE TITLE
No app feedback when logging is disabled (permission denied in updater/update.log)

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#223]
### Steps to reproduce
1. Run `php application.php` in owncloud/updater directory (dummy user barely knows how to run the app :smile: )
2. Run `sudo -u www-data php updater/application.php` from the owncloud folder, as expected

### Expected behaviour
Either the application aborts or shows feedback about what is being done

### Actual behaviour
The application continues without giving feedback to the user

Example trace:
```
PHP Warning:  fopen(updater/update.log): failed to open stream: Permission denied in /opt/owncloud/updater/app/config/container.php on line 92
[Warning] Failed to init logger. Logging is disabled.
updater is not writable
[Warning] Failed to init logger. Logging is disabled.
updater is not writable
ownCloud updater 1.0 - CLI based ownCloud server upgrades
[Warning] Failed to init logger. Logging is disabled.
updater is not writable
Checking system health.
 - file permissions are ok.
[Warning] Failed to init logger. Logging is disabled.
updater is not writable
Current version is 9.0.0.10
ownCloud daily is found online
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1

Done
```

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** daily-master (OC 9, Feb 8th)

**Updated from an older ownCloud or fresh install:** fresh install

Pinging @carlaschroder in case this isn't documented how the app is supposed to be executed

**Comment by carlaschroder** [comment]
@jvillafanez I had no idea the Updater app had a CLI. When did this happen?

**Comment by VicDeo** [comment]
@carlaschroder not a long time ago. It will happen for 9.0
https://github.com/owncloud/core/issues/18721

**Comment by karlitschek** [comment]
@carlaschroder This is the new piece in 9.0

**Comment by VicDeo** [comment]
> Expected behaviour
Either the application aborts or shows feedback about what is being done

It does:
[Warning] Failed to init logger. Logging is disabled.
updater is not writable

It just needs to be cleared that __directory__ updater is not writable (asking to set proper permissions for it) and may be log to stdout as a fallback for this case

**Comment by carlaschroder** [comment]
Cool.

**Comment by DeepDiver1975** [comment]
> It just needs to be cleared that directory updater is not writable (asking to set proper permissions for it) and may be log to stdout as a fallback for this case

@VicDeo we might want to add a question here to the user and in addition make sure the console print out only happens once
