### ISSUE TITLE
Download errors in the package aren't shown

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#224]
### Steps to reproduce
1. Setup a different updater server, so the update package can't be downloaded (check notes below)
2. Run the updater

### Expected behaviour
Updater should check the http code and verify the contents of the downloaded package in order to show an accurate error message

### Actual behaviour
Updater doesn't show an error, and it seems that the update went fine (even thougth the 404 error)

```
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.0.0.10
30.0.0 pre alpha is found online
What would you do next?
  [0] download
  [1] upgrade
  [2] abort
 > 1
Downloaded 100% (309 of 309)
Done
```

### Notes

This could happen if the "official" update server or download server is temporary down, or somehow there are some errors in the server

To setup a different server:

1. Create a folder in your own ownCloud server, in the base directory of the server (let's call it update-server)
2. Create an index.php file inside with the following content (it's enough for testing):

    ```
    <?xml version="1.0" ?>
<owncloud>
  <version>30.0.0</version>
  <versionstring>30.0.0 pre alpha</versionstring>
  <url>http://localhost/owncloud-fake.tar.bz2</url>
  <web>http://www.google.com</web>
</owncloud>
    ```
3. Modify https://github.com/owncloud/updater/blob/master/src/Utils/Fetcher.php#L29 to point to your server (http://localhost/update-server should be enough)

**Comment by VicDeo** [comment]
@jvillafanez FYI the shortest way to broke the feed is to add a garbage string here https://github.com/owncloud/updater/blob/master/src/Utils/Feed.php#L108

Many thanks for testing!
