### ISSUE TITLE
Nag screen from notifications in Web UI

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#245]
Notifications carry on polling OC admin page after updater is loaded

/ocs/v2.php/apps/notifications/api/v1/notifications?format=json
![nag](https://cloud.githubusercontent.com/assets/991300/13081011/30398e38-d4dc-11e5-8111-dcc45638cfcc.png)

**Comment by karlitschek** [comment]
@LukasReschke What do you think?

**Comment by VicDeo** [comment]
I might shoot myself in the foot with that, but I suggest to filter AJAX requests with URLs that don't match endpoint URL
https://github.com/owncloud/updater/pull/246/files
