### ISSUE TITLE
Some small design issues

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/updater#250]
@VicDeo from the screenshot you posted:

![updater](https://cloud.githubusercontent.com/assets/991300/13255844/23eb8352-da59-11e5-93e9-737aa680d5f5.png)

- [x] please remove the version number from the title (see header)
- [x] in the sidebar, »Upgrade« should be »Update«. We should stick to the word »update« and never use »upgrade« anywhere.
- [x] remove all the borders and boxes around the text. Whitespace is enough
- [x] for the checkmark, do you use the icon-checkmark-color?
- [x] the green color should not be used for text as it’s too light. Simply having it black works

**Comment by VicDeo** [comment]
@jancborchardt just to be clear, this is a standalone app now. 
Which means it reuses no code/resources from core. See https://github.com/owncloud/core/issues/18721

I stole some markup from core admin page in order for it to look similar.

**Comment by karlitschek** [comment]
Thanks @VicDeo This looks good. Would be great if you could incorporate the style fixes from @jancborchardt Do you think this is possible?
Thanks

**Comment by VicDeo** [comment]
@karlitschek not sure about green color, it's coming from Symfony/Console and still should be colored in CLI mode

**Comment by karlitschek** [comment]
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
@VicDeo checkmark icon copied from core is correct, thanks!
In CLI mode the text could be colored, but here it just is too much. The colored icon is enough.

**Comment by VicDeo** [comment]
@jancborchardt  I don't want to touch this part just before RC, because output is the same for CLI and web mode. 

For web mode it is processed with regular expressions and I don't want introduce new issues because I still have some other things to fix.

**Comment by cmonteroluque** [comment]
@VicDeo let's move the rest for 9.0.1 perhaps, if not 9.0

**Comment by jancborchardt** [comment]
Fixed via #251, we can review more afterwards.
