### ISSUE TITLE
Misleading error when no token is specified

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/updater#253]
When browsing `/updater` and having the secret not configured:

```
updater.secret is undefined in config/config.php. Please define a strong secret using bcrypt("SecretToken").
```

I needed to ask Lukas that there is an input field for that password in the admin section. Why not directly mention this then in the error message. ;)

cc @vicdeo @karlitschek

**Comment by LukasReschke** [comment]
> I needed to ask Lukas that there is an input field for that password in the admin section. Why not directly mention this then in the error message. ;)

No. There is no input field. It's a button that you just need to press ;)

**Comment by MorrisJobke** [comment]
> No. There is no input field. It's a button that you just need to press ;)

Found it :)

Clicking it just opens the updater. Why is there then a login page? I'm confused. When I can't specify a password myself - then also type in a password makes no sense. Or missed I some documentation about how to generate something like this:

```
'updater.secret' => '$2y$10$.tfQY8Jn8mKIBUFYnUEgZ.mr2bCm20NXNxbMS1OE5W0IN68vxtm4y',
```

with my own password?

**Comment by LukasReschke** [comment]
> Clicking it just opens the updater. Why is there then a login page? I'm confused. When I can't specify a password myself - then also type in a password makes no sense. Or missed I some documentation about how to generate something like this:

In case ownCloud doesn't load one can specify their own BCrypt hash (which is what the error message basically says) in config.php and use the plain text.

**Comment by LukasReschke** [comment]
So this is more something in case of disaster recovery where manual interaction is anyways required. If you have suggestions to reword that, any input welcome :wink:

**Comment by LukasReschke** [comment]
Suggestion:

> <code>updater.secret</code> is undefined in config/config.php. Please define a strong secret in your config file. To generate it use <code>php -r 'echo password_hash("MyStrongSecretDoUseYourOwn!", PASSWORD_DEFAULT);'</code> on your CLI and use the resulting hash. In case ownCloud is accessible you may also access the updater via the admin menu.

**Comment by karlitschek** [comment]
I agree with @LukasReschke This is a situation that shouldn't happen in normal circumstances. Message is fine.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/updater/pull/255
