### ISSUE TITLE
[NEw updater] Updater code updates itself during upgrade but restoring to a previous checkpoint keeps the new code

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#258]
### Steps to reproduce
1. Install ownCloud 9.0RC1
2. Modify https://github.com/owncloud/updater/blob/master/src/Utils/Fetcher.php#L29 to point to another valid server (and where we can update from) (*)
3. Update to a newer version with the updater
4. Verify the new version is installed successfully
5. Verify the updater code changed (*)
6. Restore to the previous checkpoint
7. Check the updater code again

### Expected behaviour
???

### Actual behaviour
At point 7, the updater code is the new one (from the new version) not the old one

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0RC1 updating to a future version

(*) This probably can be reproducible adding a comment in the Fetcher, without modifying the target url
At point 7, the updater code is the new one (from the new version) not the old one

I don't know if it's a good idea that the updater update itself (probably it's fine) but keeping the new updater after restoring a previous checkpoint doesn't look good.

No idea about the consecuences of restoring an old updater version or keeping the new one, but it's something to check.

**Comment by rperezb** [comment]
@DeepDiver1975 @PVince81 your input appreciated

**Comment by PVince81** [comment]
You forgot to include the updater expert @VicDeo

**Comment by PVince81** [comment]
> I don't know if it's a good idea that the updater update itself (probably it's fine) but keeping the new updater after restoring a previous checkpoint doesn't look good.

Back then when I asked @VicDeo he said it should be fine, and the old updater code also did that.

**Comment by rperezb** [comment]
heheeh I assumed that he is checking this repo by default, he is the *one* for the updater :relaxed:

**Comment by VicDeo** [comment]
@rperezb yep:)

**Comment by VicDeo** [comment]
well, I consider this to be a feature since it makes possible to  retry with updated updater :wink:

**Comment by DeepDiver1975** [comment]
But updating the updater code base while executing will result in the exact same issues as we had with the old updater where the code was relying on owncloud core.

We better NOT update the updater code but have an explicit command which allows updating the updater explicit
