### ISSUE TITLE
[New updater] Checkpoints aren't deleted after restoring them

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#259]
### Steps to reproduce
1. Install ownCloud 9.0.0RC1 (or maybe a previous version)
2. Update to a newer version
3. Check that the update is successful and that you have a new checkpoint created
4. Restore the checkpoint

### Expected behaviour
The checkpoint is deleted if it's successfully restored

### Actual behaviour
The checkpoint is left there.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0RC1

**Comment by PVince81** [comment]
Not sure if medium or high. It's basically just wasting space ?

Does the checkpoint use a unique folder name or is there a risk of overwrite if you redo the operation ?

**Comment by VicDeo** [comment]
@PVince81 unique.
