### ISSUE TITLE
oC 9.0 RC1: proc_open required

### ISSUE THREAD

**Issue by vanMacG** [owncloud/updater#261]
# The new updater requires proc_open function to be enabled.
On many shared hosters this function is disabled. Is this function really used or only "included" by symfony? Can the updater run without the function or is there a workaround?

owncloud/updater/index.php produces this error:
````
Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.' in /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/vendor/symfony/process/Process.php:144 Stack trace: #0 /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/src/Utils/OccRunner.php(45): Symfony\Component\Process\Process->__construct('php /www/htdocs...') #1 /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/src/Utils/OccRunner.php(56): Owncloud\Updater\Utils\OccRunner->run('--no-warnings c...') #2 /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/src/Utils/ConfigReader.php(106): Owncloud\Updater\Utils\OccRunner->runJson('config:list --p...') #3 /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/src/Utils/ConfigReader.php(50): Owncloud\Updater\Utils\ConfigReader->load() #4 /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/src/Controller/IndexController.php(96): Owncloud\Updater\Utils\ConfigReader->init() #5 /www/htdocs/ in /www/htdocs/w0069a6f/testing/oc9rc1/owncloud/updater/vendor/symfony/process/Process.php on line 144

**Comment by VicDeo** [comment]
@vanMacG sadly `proc_open` is a hard requirement of  `symfony/process`

**Comment by karlitschek** [comment]
@VicDeo Can we check for proc_open and show a better error message?
@DeepDiver1975

**Comment by vanMacG** [comment]
I know that shared hoster are not your favorite hosting solutions for ownCloud, but people do use it. I worry that many will struggle on this...

Nevertheless, when I have to do a manual upgrade, will this work? Aka how does the db get updated? Also with the "new updater" or is this an independent function without proc_open?

**Comment by LukasReschke** [comment]
> @vanMacG sadly proc_open is a hard requirement of symfony/process

What about http://symfony.com/doc/current/cookbook/console/command_in_controller.html as fallback?

**Comment by DeepDiver1975** [comment]
This is why we need https://github.com/owncloud/core/issues/21985

**Comment by DeepDiver1975** [comment]
Or we have a shortened processing path for the web updater where the need of interaction using occ is not required.

@VicDeo where is occ required as of today?

**Comment by VicDeo** [comment]
@DeepDiver1975 in short it is used nearly everywhere (except dealing with checkpoints)

**Comment by vanMacG** [comment]
What doesn't make sense from a users pov is: "There was a web updater which mainly did the job. Now there is a web updater which is just a nice gui for occ-cli?"
I'm sorry for the rough sounding and exaggerating! I don't want to degrade the work which was done here but that's the result for many users on shared hosters... :-/

**Comment by DeepDiver1975** [comment]
We have to enhance the web Updater for sure.
Next Version will Focus on this

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/21985 which brings the web executor.
