### ISSUE TITLE
Is Updater supposed to be in top-level dir?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/updater#262]
In ownCloud 9.0.0 RC1 the Updater app is in `owncloud/updater` instead of `owncloud/apps/updater`. And it is absent from the Apps page. Is this how it's supposed to be?

Also, there is a permissions problem with running the Updater CLI. The admin manual recommends using the following script to set strong ownCloud permissions:

````
#!/bin/bash
ocpath='/var/www/owncloud'
htuser='www-data'
htgroup='www-data'
rootuser='root'

printf "Creating possible missing Directories\n"
mkdir -p $ocpath/data
mkdir -p $ocpath/assets

printf "chmod Files and Directories\n"
find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750

printf "chown Directories\n"
chown -R ${rootuser}:${htgroup} ${ocpath}/
chown -R ${htuser}:${htgroup} ${ocpath}/apps/
chown -R ${htuser}:${htgroup} ${ocpath}/config/
chown -R ${htuser}:${htgroup} ${ocpath}/data/
chown -R ${htuser}:${htgroup} ${ocpath}/themes/
chown -R ${htuser}:${htgroup} ${ocpath}/assets/

chmod +x ${ocpath}/occ

printf "chmod/chown .htaccess\n"
if [ -f ${ocpath}/.htaccess ]
 then
  chmod 0644 ${ocpath}/.htaccess
  chown ${rootuser}:${htgroup} ${ocpath}/.htaccess
fi
if [ -f ${ocpath}/data/.htaccess ]
 then
  chmod 0644 ${ocpath}/data/.htaccess
  chown ${rootuser}:${htgroup} ${ocpath}/data/.htaccess
fi
````

However, this sets owncloud/updater to `drwxr-x---  7 root     www-data`, which means that running updater CLI commands as the HTTP user will not work, as the HTTP group has no write permissions to owncloud/updater. Should I adjust the script to make owncloud/updater writeable for the HTTP group, or chown owncloud/updater to `http-user:http-group`?

The manual page also advices temporarily chown-ing  the entire owncloud directory to `http-user:http-group` before running Updater. Is this still true for 9.0?

Manual page is here: https://doc.owncloud.org/server/9.0/admin_manual/maintenance/update.html

@VicDeo @cmonteroluque @MTRichards

**Comment by VicDeo** [comment]
> However, this sets owncloud/updater to drwxr-x--- 7 root www-data, which means that running updater CLI commands as the HTTP user will not work, as the HTTP group has no write permissions to owncloud/updater. Should I adjust the script to make owncloud/updater writeable for the HTTP group, or chown owncloud/updater to http-user:http-group

Update detection will work (with no logging) but for the whole update process to work it is necessary to chown everything back as per:

>The manual page also advices temporarily chown-ing the entire owncloud directory to http-user:http-group before running Updater. Is this still true for 9.0?

Yes. At least for all files and folders that belong to ownCloud (some hosters/users are used to extra items into server webroot dir, so there can be unrelated to oC items )

**Comment by carlaschroder** [comment]
Thanks @VicDeo!
