### ISSUE TITLE
Invalid password/updater.secret + Login UI broken

### ISSUE THREAD

**Issue by vanMacG** [owncloud/updater#263]
### Steps to reproduce
1. Install oC 9.0 RC2
2. Switch to Release-Channel "daily" to get an update notification
3. Click on button to Update Center

### Expected behaviour
When I directly access owncloud/updater/index.php login page looks as follow:
![updater1](https://cloud.githubusercontent.com/assets/8269814/13548409/14eaf442-e2f0-11e5-805e-e9eba55a9a56.PNG)

### Actual behaviour
when clicking the link from admin-panel it looks like this:
![updater2](https://cloud.githubusercontent.com/assets/8269814/13548414/2df1cbd2-e2f0-11e5-850e-5a34a9b9ab45.PNG)

It's both with Firefox and Chrome.

### Server configuration
**Operating system**: Linux dd27002 3.2.0-98-generic #138-Ubuntu SMP Mon Jan 11 12:33:01 UTC 2016 x86_64 

**Web server:** Apache

**Database:** SQLite

**PHP version:** 7.0.2

**ownCloud version:** ownCloud 9.0.0 RC2

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** RC2.zip

### Client configuration
**Browser:** Firefox 44.0.2 & Chrome 49.0.2623.75 m

**Operating system:** Windows 7

**Comment by vanMacG** [comment]
Ok, this has something to do with a login-error.
When directly accessing the updater and page looks ok, after entering the secret I get the same broken site (and UI) as when accessing through admin-panel...

**Comment by vanMacG** [comment]
I removed some characters from updater.secret for security reason. I removed only letters and numbers, maybe the special-characters are the problem?

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ockrkkdcwj9i',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.eu',
  ),
  'datadirectory' => '/www/htdocs/w0069a6f/testing/oc9rc2/owncloud/data',
  'overwrite.cli.url' => 'http://xxx.eu/testing/oc9rc2/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.17',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.secret' => '$2y$10$S3.Hntw/Ylp[...]xO.Bn[...]eRIm',
);

**Comment by vanMacG** [comment]
Sorry for spaming this issue with comments, but things are realy getting strange here...
Everytime I try to access the updater (aka click the link in admin-panel), the updater.secret value in config.php gets changed/overwritten.
Now it's: 'updater.secret' => '$2y$10$B0Szju.ubAI6o3ogby[...]QOq',

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by karlitschek** [comment]
@VicDeo

**Comment by LukasReschke** [comment]
Very strange. This works fine for me locally here. So what I did:

1. Install http://download.owncloud.org/community/testing/owncloud-9.0.0RC2.tar.bz2
2. Change to daily channel in admin menu
3. Clear cookies and relogin so that the new version is certainly displayed
4. Click open updater
5. Updater is displayed properly here.

> Everytime I try to access the updater (aka click the link in admin-panel), the updater.secret value in config.php gets changed/overwritten.

This is the expected behaviour.

<hr/>

Any chance that you could grant me administrative access to this instance of yours? That would help debugging _a lot_. You can find my mail address in my profile.

**Comment by LukasReschke** [comment]
Ok. It's the famous "CGI does not pass HTTP_AUTHORIZATION header" issue we also always enjoy in core… Let me think of a workaround……

**Comment by LukasReschke** [comment]
Fixes are at:

- stable9: https://github.com/owncloud/updater/pull/266 / https://github.com/owncloud/core/pull/22889
- master: https://github.com/owncloud/updater/pull/265 / https://github.com/owncloud/core/pull/22888

Thanks a lot @vanMacG for the instance to the affected instance. Helped a lot :rocket: 

@karlitschek I'd highly recommend 9.0 here as this affects the usability of the updater app for people using PHP in CGI mode.

**Comment by vanMacG** [comment]
@LukasReschke You're welcome!

**Comment by karlitschek** [comment]
Another one.
Please backport to 9.0.0 :+1:
