### ISSUE TITLE
Updating to daily release fails on 9.0.0 RC2

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#264]
In the step "Updating apps" the following exception is thrown.

```
 [Symfony\Component\Process\Exception\ProcessFailedException] 
 The command "php /Users/lukasreschke/Documents/Programming/update/owncloud/occ upgrade" failed. 
 Exit Code: 5(Unknown error) 
 Output: 
 ================ 
 ownCloud or one of the apps require upgrade - only a limited number of commands are available 
 You may use your browser or the occ upgrade command to do the upgrade 
 Set log level to debug 
 Turned on maintenance mode 
 Checking whether the database schema can be updated (this can take a long time depending on the database size) 
 Checked database schema update 
 Checking updates of apps 
 Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size) 
 Checked database schema update for apps 
 Updating database schema 
 Updated database 
 Exception: files can't be disabled. 
 Update failed 
 Maintenance mode is kept active 
 Reset log level 
 Error Output: 
 ================ 
 
```

**Comment by LukasReschke** [comment]
Setting to sev1-critical until this is debugged… On it…

**Comment by LukasReschke** [comment]
Cool. This is a bug in core … GNAAAAH…

**Comment by LukasReschke** [comment]
```
➜  ~ php /Users/lukasreschke/Documents/Programming/update/owncloud/occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Exception: files can't be disabled.
Update failed
Maintenance mode is kept active
Reset log level
```

**Comment by LukasReschke** [comment]
Ok. This seems to be caused by the fact that apps are updated after the system, so what happens here is:

1. The updater updates core. The version.php is now to 9.1
2. The updater updates the apps. Some of the apps have a maximum and minimum requirement set for 9.1 such as files (see https://github.com/owncloud/core/blob/a98f5c03dc4e60dcd511c4b50639878e531c5119/lib/private/updater.php#L470-L503)
3. :bomb: 

This is not a super imminent bug for 9.0.0 as from what I can tell it only affects updates to 9.1.0 (or daily) but not to 9.0.x. But should be fixed anyways…

**Comment by LukasReschke** [comment]
cc @VicDeo

**Comment by LukasReschke** [comment]
@karlitschek This means that the "daily" channel is basically broken as-is, it will result in a broken ownCloud. I'd suggest that we take one of the following actions:

1. Remove the option to choose daily in 9.0.0 (purely cosmetical one-liner)
2. Deliver 9.0 dailies instead of master dailies for the daily channel
3. Make sure the updater can perform these kinds of updates properly.

Of course, 3 is the superior goal but I'm not super convinced that we can fix this until 9.0.0, but until 9.0.1 might be certainly possible.

My personal suggestion would be to go with 2 in the short term and for 9.0.1 go to 3.

Thoughts?

**Comment by karlitschek** [comment]
Agreed. Let's go with  option 2 because of the limited time. 
I changed the daily channel to deliver https://download.owncloud.org/community/owncloud-daily-stable9.tar.bz2

**Comment by karlitschek** [comment]
@cmholton FYI

**Comment by karlitschek** [comment]
@cmonteroluque FYI

**Comment by DeepDiver1975** [comment]
@LukasReschke can you please reevaluate this? THX
