### ISSUE TITLE
Use PHP to BZIP extract instead of using tar from shell

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#267]
https://github.com/owncloud/updater/blob/bc9018f190037eeb05c6f01f40ba44c7b4f091f9/src/Utils/BzipExtractor.php#L45 uses `tar` from CLI to extract the folder instead of a PHP library.

Using a PHP library would make this whole stuff way more portable. I just encountered an instance where this was missing here :)

cc @VicDeo

**Comment by DeepDiver1975** [comment]
Same applies to zip

**Comment by VicDeo** [comment]
@DeepDiver1975
Regarding zip:  isn't `ZipArchive` a hard requirement? https://github.com/owncloud/core/blob/master/lib/private/util.php#L727

Currently there is a fallback in case shell extraction has been failed https://github.com/owncloud/updater/blob/master/src/Utils/ZipExtractor.php#L42

**Comment by DeepDiver1975** [comment]
> Regarding zip: isn't ZipArchive a hard requirement? https://github.com/owncloud/core/blob/master/lib/private/util.php#L727
> 
> Currently there is a fallback in case shell extraction has been failed https://github.com/owncloud/updater/blob/master/src/Utils/ZipExtractor.php#L42

True - should we reevaluate these requirements on startup of the updater?

**Comment by VicDeo** [comment]
@DeepDiver1975 
it depends on the feed content so  it is worth to make it a soft requirement.
There is no sense in failing to start when feed is `tar.bz2` and `ZipArchive` is missing.
And vice versa missing `bz2`  extension make no difference for `zip` package extraction.

**Comment by DeepDiver1975** [comment]
Well - we control the feed and the feed holds either zip or bz2.

We need a hard requirement if none of them are extractable

**Comment by VicDeo** [comment]
@DeepDiver1975 the current feed implementation contains not bz2 and zip simultaneously but bz2 for daily channel and zip for other channels.

**Comment by DeepDiver1975** [comment]
Oh ... a bit messy ...

@karlitschek any special reason for this mix of archive formats?

@VicDeo given the current situation both zip and bz2 are hard requirements then which need to be tested. Preferable we use shell and a php based implementation as fallback

**Comment by karlitschek** [comment]
O.K. Ley's switch everything to .zip. will be done later today

**Comment by DeepDiver1975** [comment]
THX @karlitschek 

@VicDeo we can drop then anything related to tar - which will invalidate this issue.
#313 is also no longer required then from my pov as soon as we declare ZipArchive as hard requirement (in case shall tools are not available or not accessible)

**Comment by DeepDiver1975** [comment]
@VicDeo objections?

**Comment by VicDeo** [comment]
@DeepDiver1975 I'm all for it

**Comment by karlitschek** [comment]
it is switched over to zip now

**Comment by karlitschek** [comment]
updater for 9.0.1 is now activated and an additional check is implemented so that ownCloud < 8.2 don't get the upgrade
