### ISSUE TITLE
Date of checkpoint/backup missing

### ISSUE THREAD

**Issue by vanMacG** [owncloud/updater#268]
I just noticed a small ui-bug. In the table of checkpoints there is a 2nd column "Done on", but it's empty.

![updater3](https://cloud.githubusercontent.com/assets/8269814/13557163/5fd22390-e3ea-11e5-8a63-0de3508d8345.PNG)

The backup is created in /data/updater-data/checkpoint/ and no error is shown, so only the date is missing.

**Comment by LukasReschke** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@vanMacG Thanks, fixed with https://github.com/owncloud/updater/issues/275
