### ISSUE TITLE
PHP Fatal Error after upgrading from OC 8.2 to 9.0

### ISSUE THREAD

**Issue by StormCh** [owncloud/updater#269]
Hi Folks, I do have a big problem. After upgrading my oc server from 8.2.2 to 9.0 this error appears after a second command of "sudo -u www-data php occ upgrade":
PHP Fatal error: Cannot redeclare class OC_L10N in /var/www/owncloud/lib/private/l10n.php on line 42

Could you please help me!

**Comment by VicDeo** [comment]
@StormCh how did you upgrade?

**Comment by VicDeo** [comment]
Anyway, it looks like you still have some 8.2 files left  under `lib` directory.
At least `lib/private/l10n.php`  should be removed since it is no longer exists in 9.0

**Comment by StormCh** [comment]
I upgrade the manual way, downloading the .tar unpacking and copying to owncloud-folder and use the manual commands via terminal

**Comment by StormCh** [comment]
I removed the `lib/private/l10n.php`. The upgrade command results in `owncloud already latest version`, but the website shows:

> Interner Servierfehler
> Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
> Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.
> Weitere Details können im Serverprotokoll gefunden werden.

**Comment by StormCh** [comment]
Command `sudo -u www-data php console.php files:scan --all` results in 0 Files and Folders

**Comment by VicDeo** [comment]
@StormCh `l10n.php` is not the only I guess
Please try the following:
1. move all directories except `data` and `config` to a temporary location.
2. copy `config` and `data` somewhere
3. Extract 9.0 and copy it's files to your old oC dir

**Comment by StormCh** [comment]
Ok, this was working for me. Thanxx
Now it says:

> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - core
> 	- INVALID_HASH
> 		- .htaccess
> 	- EXTRA_FILE
> 		- .mailmap
> 		- .tag
> 		- indie.json

**Comment by VicDeo** [comment]
@StormCh does web interface work?
These files are probably excluded from 9.0 release and can be safely removed
        - .mailmap
        - .tag
        - indie.json

**Comment by StormCh** [comment]
Yes, the web interface is working, also the desktop clients. I did delete the files, but it still says 
`Es gab Probleme mit dem Code - Integritätsprüfung. Mehr Informationen…` now 
only this file 
```
- core
	- INVALID_HASH
		- .htaccess
```
is shown as a problem

**Comment by VicDeo** [comment]
@StormCh most likely .htaccess remained after 8.2. Backup it and replace with one from 9.0 package.

**Comment by StormCh** [comment]
Thanxx a lot, now it is working fine

**Comment by VicDeo** [comment]
@StormCh no problem :)
