### ISSUE TITLE
Cannot log in after upgrade from 8.1.6 to 8.2.2

### ISSUE THREAD

**Issue by conan0276** [owncloud/updater#273]
I did an upgrade to 8.1.6 which worked perfectly (old version was 8.1.3).
After that the admin interface provided the possibility to upgrade to 8.2.2. This upgrade works but after that I cannot log in any more. 

The owncloud.log-file does not contain any errors. Resetting the password with occ does not work either. The apache-log does also contain no errors.

I tried the update from 8.1.6 to 8.2.2 twice once to the "stable" update channel and once to "productive". Both result in the same behaviour as described above.

Versions:
PHP 5.6.11-1ubuntu3.1 (cli)
Ubuntu Wily / Kernel  4.2.0-30-generic 
Apache/2.4.12 (Ubuntu)

**Comment by VicDeo** [comment]
@LukasReschke Did we change anything with cookies for 8.2?

**Comment by VicDeo** [comment]
@conan0276 Do you have that instance right now?

**Comment by conan0276** [comment]
I went back to the state where I have the 8.1.6 version running (that one works for the moment). It is running in my local net. Not accessible via internet at the moment. What do you need?

**Comment by VicDeo** [comment]
@conan0276 Given that your ownCloud doesn't use any custom user backend and custom theme 
it might be related to cookies/sessions

**Comment by conan0276** [comment]
Yeeeaaaaah. That's it!!! Started another browser (konqueror) and now I can log in. You are telling me that I kept reinstalling owncloud for two hours now only because of a session-thing (*AAAAAAHHHH*). 

OK, now I can boldly go for 9.0. Thank you!!!!

**Comment by VicDeo** [comment]
@conan0276 I'm cosing the issue as resolved. Please reopen if it is not.
