### ISSUE TITLE
Update notification error post 9.0 upgrade

### ISSUE THREAD

**Issue by jl-678** [owncloud/updater#278]
Hi,

I apologize if this is not the right place the post and will submit elsewhere if that makes sense.  Anyway, I just did a clean upgrade to 9.0 with no plugins or apps in place.  (I unzipped 9.0 and copied the folder to my web directory and then copied my config file and ran occ update.)

Everything is running smoothly except I see the following error in the OC admin console log:

`Error	PHP	Undefined index: newVersionString at /path/to/owncloud/apps/updatenotification/templates/admin.php#8	2016-03-11T21:42:38+00:00`

This error appears in the log every time I open the admin window.  The issue was resolved by disabling the "Update Notification" plugin, but something seems off since UN is an official plugin.

Thank you.

**Comment by RealRancor** [comment]
Hi,

thats a duplicate of https://github.com/owncloud/core/issues/22999 and https://github.com/owncloud/core/issues/22917 which gets fixed with 9.0.1

The issue tracker here is for the updater app itself where updatenotification is a core app.

**Comment by jl-678** [comment]
Thank you!  I am closing the issue.
