### ISSUE TITLE
Make new releases immediately available on the 'stable' channel (as part of the release process)

### ISSUE THREAD

**Issue by brevilo** [owncloud/updater#279]
As a follow-up to https://github.com/owncloud/updater/issues/183 I'd really like to see the release process improved such that a 'stable' channel release is made an integral part. Release availability on the 'production' channel can certainly be delayed a few days for safety reasons but please keep 'stable' in sync with official announcements - this way admins can chose their tactic and would be enabled to deploy important bug/security fixes as soon as they are available.

This discussion is so old and won't end until the process gets improved/fixed. Please, the compromise outlined above should make everyone happy...

Thanks

**Comment by RealRancor** [comment]
@brevilo This is not an issue within the updater app as it only provides the versions which it gets provided by the update server. It is not possible to "fix" this in the updater app. Try to push this either to:

https://mailman.owncloud.org/mailman/listinfo/devel

or:

https://github.com/owncloud/appstore-issues/issues (Where the update server is located).

**Comment by RealRancor** [comment]
This is only possible if the process of releasing updates are fixed. Maybe @karlitschek or @cmonteroluque can help here?

**Comment by brevilo** [comment]
FYI, this targets the process not the updater app itself. I reported it here since the very part of the process in question affects mainly the updater, not releases in general. So yes, hopefully these guys can help getting this part fixed/improved.

**Comment by karlitschek** [comment]
So the idea is to make releases available in the stable channel once we think that it works well for most users. So this is a manual process. Unfortunately 9.0.0 is less bug free as hoped. So for now I think that we can out this into stable aka activate the updater for 9.0.1

**Comment by RealRancor** [comment]
@karlitschek I think it is more about the issue that 8.2.3 is not yet available via the updater app.

**Comment by brevilo** [comment]
Erm, this is how it works today, right? But where's the difference compared to production then? My point, and that of many others for that matter, is that stable updater releases should be made available when a release gets released, immediately. Why having beta or RC releases if they can't be trusted for the stable release? If a release get's released as stable it should down to the admin whether or not to wait. Again, if you don't trust the stable release announcement, please hold of the update on the production for a few days/weeks, but not in the stable channel. This particularly important for the security related content of a release.

**Comment by brevilo** [comment]
Yes, this is mainly about 8.2.3 which is already over a week "late".

I'm trying to settle this issue since, as you know, it comes up after each and every release. It should really be settled once and for all and I haven't yet heard any real reason why the process shouldn't be improved as outline above.

**Comment by RealRancor** [comment]
From my experience/PoV 8.2.3 is quite "stable" and should be released via the updater. oC 9.0.0 is another topic and currently doesn't fit into:

> This channel delivers the latest feature releases ready for home users at minimal risk.

https://owncloud.org/release-channels/

**Comment by brevilo** [comment]
Fair enough, this is where the process should incorporate policies for major/minor/revision updates respectively...

**Comment by karlitschek** [comment]
good point. @jospoortvliet @LukasReschke What do you think?

**Comment by LukasReschke** [comment]
> good point. @jospoortvliet @LukasReschke What do you think?

:+1: 

On a side note, that requires me finishing https://github.com/owncloud/administration-internal/pull/12. Otherwise we will deliver wrong updates for 9.0.x from what I can tell.

**Comment by brevilo** [comment]
So, should we reopen this issue then...? :grinning:

**Comment by RealRancor** [comment]
Probably not as it is not an issue within the updater. Its only one of the two affected components (updater app and core update notification) of this broken process.

**Comment by brevilo** [comment]
Fine with me but please open a new one then, referencing this one. We don't wan't to lose this chance :+1:

**Comment by RealRancor** [comment]
@brevilo You might want to raise this again in https://mailman.owncloud.org/mailman/listinfo/devel

The issue tracker of the updater app is really not the correct place to discuss this. :-)

**Comment by brevilo** [comment]
Ok, will try to "make" time for it. In the meantime, @karlitschek could you please release 8.2.3, at least on stable...? Thanks

**Comment by karlitschek** [comment]
done

**Comment by brevilo** [comment]
Thank you

**Comment by jospoortvliet** [comment]
FYI we're working on the upgrade server, making it able to offer different versions to different users depending on the ownCloud version they are on and the release channel they have picked. This should help with this in the future.
