### ISSUE TITLE
Updater breaks OC leaving apps empty

### ISSUE THREAD

**Issue by Phiber2000** [owncloud/updater#280]
Commit 6c88f76b18f00935415eb4c7999ade5446dea07d breaks OC completely.
What happens:

- "apps" directory is moved to "__apps"
- empty "apps" dir is created
- updater runs (with empty apps dir)
- updater doesn't report updating apps
- "apps" stays empty
- "__apps" stays untouched

--> owncloud broken with empty "apps" dir

**Comment by LukasReschke** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@Phiber2000 this commit was tested manually before merging.
 I don't see how an empty app directory can break the upgrade process.

**Comment by VicDeo** [comment]
ah, you probably mean that this step needs to be reverted on failure. Very true.

**Comment by Phiber2000** [comment]
I did this manually about 20 times!
It's only succeeding if apps dir isn't present while core upgrade - or removing those 4 new lines.
Tested with daily-stable9.

**Comment by Phiber2000** [comment]
Don't ask me why - but the moving back from "__apps" to "apps" isn't executed.

**Comment by Phiber2000** [comment]
After some further eval I can say, that the commit itself isn't the problem:
It seems, that `$plain = $this->occRunner->run('upgrade');` leads to an exit of the try block without being catched.

**Comment by Phiber2000** [comment]
You were totally right: 

> ah, you probably mean that this step needs to be reverted on failure. Very true.

Because:
```
exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "php /media/data0/owncloud/occ upgrade" failed.
Exit Code: 3(Unknown error)

Output:
================
ownCloud is already latest version
```

**Comment by Phiber2000** [comment]
@VicDeo It would be nice, to hear your opinion about the commit #281, too!
