### ISSUE TITLE
PHP Fatal error:  Cannot declare class OC_L10N, because the name is already in use in lib/private/l10n.php on line 42

### ISSUE THREAD

**Issue by rakshazi** [owncloud/updater#285]
### Steps to reproduce
1. Install OwnCloud 8.2.3
2. Manually upgrade to OwnCloud 9.0 (copy files)
3. Run `occ upgrade`

### Expected behaviour
Upgrade finished successful

### Actual behaviour
PHP Fatal error:  Cannot declare class OC_L10N, because the name is already in use in lib/private/l10n.php on line 42 (CLI)
503 error (browser)

### Server configuration
**Operating system**: 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Web server:**
nginx/1.9.12

**Database:**
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 7.0.4-6+deb.sury.org~trusty+5 (cli) ( NTS )

**ownCloud version:** (see ownCloud admin page)
~~~php
$OC_Version = array(9,0,0,19);
$OC_VersionString = '9.0.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-03-08T13:56:30+00:00 81f694d83e8246d9b6482b773c8bdca675c51828';
~~~

**Updated from an older ownCloud or fresh install:**
Updated from OwnCloud 8.2.3

**Where did you install ownCloud from:**
Manual install from zip archive https://download.owncloud.org/community/owncloud-9.0.0.zip
**Signing status (ownCloud 9.0 and above):**
Can't access to admin panel

**List of activated apps:**
Enabled:
  - dav: true
  - encryption: 1.2.0
  - federatedfilesharing: true
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - gallery: 14.5.0
  - notifications: 0.1.0
  - templateeditor: 0.1

**The content of config/config.php:**
```php
{
    "system": {
        "instanceid": "ocqdnosy0c6b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "svart.xyz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/svart.xyz",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Tiraspol",
        "logdateformat": "d.m.Y - H:i:s",
        "log_rotate_size": 1048576,
        "installed": true,
        "loglevel": 0,
        "enable_previews": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": true,
        "app.mail.server-side-cache.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "app.mail.imaplog.enabled": false,
        "theme": "",
        "maintenance": true,
        "singleuser": false,
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** console

**Operating system:** doesn't matter

#### Web server error log

doesn't matter

#### ownCloud log (data/owncloud.log)
{"reqId":"DzpJEehRygdpSvBpqGQ\/","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"21.03.2016 - 07:30:01","method":"--","url":"--"}
{"reqId":"uO+7QXp78ztCOIMs9IWW","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"21.03.2016 - 07:45:01","method":"--","url":"--"}
{"reqId":"742iVSnTLv19Gmo8kOPh","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 9.0.0.19","level":0,"time":"21.03.2016 - 07:57:33","method":"--","url":"--"}
{"reqId":"742iVSnTLv19Gmo8kOPh","remoteAddr":"","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 07:57:56","method":"--","url":"--"}
{"reqId":"2LDTZekPIh1h3jQ2HHMk","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 9.0.0.19","level":0,"time":"21.03.2016 - 07:59:44","method":"--","url":"--"}
{"reqId":"2LDTZekPIh1h3jQ2HHMk","remoteAddr":"","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 07:59:58","method":"--","url":"--"}
{"reqId":"1b8nJIiLgShJxTGf7f7V","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"21.03.2016 - 08:00:01","method":"--","url":"--"}
{"reqId":"Zs8vDwO+TNCb0z5Zy6Xp","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 9.0.0.19","level":0,"time":"21.03.2016 - 08:00:54","method":"--","url":"--"}
{"reqId":"Zs8vDwO+TNCb0z5Zy6Xp","remoteAddr":"","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:01:03","method":"--","url":"--"}
{"reqId":"VmAU1fIKArIOIjJFpsN2","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 9.0.0.19","level":0,"time":"21.03.2016 - 08:01:35","method":"--","url":"--"}
{"reqId":"VmAU1fIKArIOIjJFpsN2","remoteAddr":"","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:01:46","method":"--","url":"--"}
{"reqId":"iuDKU\/LDy+JVbQv42Dxg","remoteAddr":"213.5.20.201","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:02:54","method":"GET","url":"\/"}
{"reqId":"WotTweVKN3D9K6H0CMMm","remoteAddr":"213.5.20.201","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:03:22","method":"GET","url":"\/"}
{"reqId":"WGPP55zXZsJW3SxTsW3O","remoteAddr":"213.5.20.201","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:03:37","method":"GET","url":"\/"}
{"reqId":"Yo9aNoKvBnTFUjxat6EB","remoteAddr":"213.5.20.201","app":"PHP","message":"Cannot declare class OC_L10N, because the name is already in use at \/var\/www\/owncloud\/lib\/private\/l10n.php#42","level":3,"time":"21.03.2016 - 08:03:39","method":"GET","url":"\/"}
{"reqId":"yYd0kppYfqWVH+480Fzd","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"21.03.2016 - 08:15:02","method":"--","url":"--"}

#### Browser log

doesn't matter

**Comment by VicDeo** [comment]
@rakshazi one should not `copy`, but `remove everything except data and config directories`
or follow the documentation
https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by rakshazi** [comment]
@VicDeo thank you, it works!

pS: I copied files from new release, because it worked for major and minor releases before
