### ISSUE TITLE
Updater Font

### ISSUE THREAD

**Issue by aspdye** [owncloud/updater#288]

**Comment by DeepDiver1975** [comment]
@jancborchardt I guess you need to have a close look here over all .... THX

**Comment by jancborchardt** [comment]
@aspdye can you show a screenshot of where this happens?

@DeepDiver1975 how can I best invoke the new updater over and over again to test?

**Comment by DeepDiver1975** [comment]
> how can I best invoke the new updater over and over again to test?

@VicDeo please provide debugging steps - THX

**Comment by aspdye** [comment]
Here is the screenshot @jancborchardt :wink: 
<img width="843" alt="bild1" src="https://cloud.githubusercontent.com/assets/12893462/14348548/83475494-fcbd-11e5-821f-0e33a1678c4e.png">

**Comment by jancborchardt** [comment]
@VicDeo is the fonts.css not loaded here? The rest of the styles seem available.

**Comment by DeepDiver1975** [comment]
@jancborchardt we shall not share any files between core and the updater - if we need font.css - copy it over

**Comment by VicDeo** [comment]
https://github.com/owncloud/updater/blob/master/pub/css/main.css#L54

**Comment by DeepDiver1975** [comment]
let's address this for 9.2

@VicDeo we might simply copy over the file https://github.com/owncloud/core/blob/master/core/css/fonts.css

**Comment by PVince81** [comment]
PRs  welcome
