### ISSUE TITLE
Updater app does not move/rename __apps/ directory back to apps/ (update via browser)

### ISSUE THREAD

**Issue by mmattel** [owncloud/updater#291]
As follow up problem of
owncloud/core#23469
owncloud/updater/issues/290

When running the updater via the browser, the updater moves/renames the apps/ directory to __apps/, but not back. Because there is an empty apps/ directory, the instance behaves dead after upgrading. After manually fixing this (renaming __apps/ to apps/) the instance is back alive again.

**Comment by VicDeo** [comment]
@mmattel duplicate of https://github.com/owncloud/updater/issues/280

Fixed with
https://github.com/owncloud/updater/pull/281
https://github.com/owncloud/updater/issues/282

**Comment by mmattel** [comment]
Thanks
