### ISSUE TITLE
Core maintenance and release integration

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#295]
> DeepDiver1975 commented a day ago
> Are we going to maintain stable branches in here?
> Does that make sense?
> 
> The updater will have to work with any past and any future version of owncloud core.
> 
> From my understanding there should be one stable version which can be pulled (somehow) to get the latest version.
> 
> Just asking - since this is all lacking a bit of concept and I want to wrap my brain around this ...

**Comment by VicDeo** [comment]
@cmonteroluque @PVince81 @DeepDiver1975 
the question is 'should we follow our standard branching model or ship updater from master with all OC versions starting from 9.0'

The latter was suggested by Thomas and looks  reasonable to me because it cuts off time on backporting stuff.
Let's discuss.

**Comment by cmonteroluque** [comment]
we will open it up early next week. I like Thomas' suggesting in principle and unless there are any good reasons not to. @VicDeo @DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
We need to rethink this for 9.2 - for the time being we follow the standard branching model

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/updater/issues/409
