### ISSUE TITLE
Not a clear message in cli and web if owncloud is not installed

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/updater#297]
![bildschirmfoto von 2016-04-06 21-18-13](https://cloud.githubusercontent.com/assets/1005065/14329723/1941a3ae-fc3d-11e5-8df9-456a3be86942.png)

Action items:
- verify if cloud is installed
- display message in console to the user if not

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo is this still an issue ? If yes, please set severity.
