### ISSUE TITLE
reenable shipped apps is not working

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/updater#301]
- the array $this->disabledApps is never set
- even if - how is the state preserved between two invocations of the upgrade application?

**Comment by VicDeo** [comment]
> the array $this->disabledApps is never set

true

> even if - how is the state preserved between two invocations of the upgrade application?

it is serialized into the session:
https://github.com/owncloud/updater/blob/master/src/Command/DisableNotShippedAppsCommand.php#L42

**Comment by DeepDiver1975** [comment]
> it is serialized into the session:

using the session in a cli command?

**Comment by DeepDiver1975** [comment]
reoping until open question is answered

**Comment by Croydon** [comment]
Please fix this. It is really annoying to enable apps after every single update.

**Comment by Croydon** [comment]
Discussion: https://github.com/owncloud/core/issues/18312

**Comment by VicDeo** [comment]
@DeepDiver1975 yes, for CLI too

**Comment by DeepDiver1975** [comment]
This was not a serious question. Using sessions in cli mode is non sense

**Comment by VicDeo** [comment]
@DeepDiver1975 ok, then it uses `Registry` singleton in the scope of `upgrade:start` command to obtain persistence in CLI mode https://github.com/owncloud/updater/blob/master/src/Command/StartCommand.php

**Comment by VicDeo** [comment]
@DeepDiver1975 tested migration stable9->master with 
https://github.com/owncloud/updater/pull/307
https://github.com/owncloud/updater/pull/346
https://github.com/owncloud/updater/pull/347
applied

all apps (shipped/not shipped) are being reenabled correctly
