### ISSUE TITLE
clear separation of updater responsibilities vs core responsibilities

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/updater#304]
# Background:
- only core and the used apps can tightly manage their upgrade process
- giving the updater a too fine granular control over the individual steps I see us being blocked in the future with respect to enhancing core's mechanism
- finally: core has to upgrade itself properly without the updater app
# Updater Responsibilities:
- download new versions
- create checkpoints
- respect upgrade channels
- guide the overall process
- inform the user about the upgrade
# Core Responsibilities:
- occ upgrade and ajax/upgrade remain the master entry points for the upgrade process
- the upgrade will be split into the requires more fine granular sub steps:
1. Repair and cleanup (pre upgrade, DB collations update, ..) [danger, might take long]
2. db schema upgrade simulated (optionally, can be done online in advance)
3. disable 3rdparty/no shipped apps
4. db schema upgrade real [danger, might take long]
5. execute core upgrade scripts [danger, might take long]
6. upgrade shipped apps [danger, might take long] - schema migration &  app upgrade scripts
7. try reenable, download and upgrade 3rdparty/non shipped apps. (one app after another)
8. repair and cleanup step 1 (post upgrade, repair legacy storage, ..) [danger, might take long]

_Will move to core once discussion is final_
# Core Upgrade Changes:
- [ ] occ:upgrade will execute all sub steps 
- [ ] each step can be executed by itself
- [ ] all substeps will be exposed to the updater so that it can call them step by step
- [ ] all upgrade steps can be executed even if we are already in maintenance mode
- [ ] new method is required to ensure only one upgrade process is triggered

_maybe worth an issue on it's own_
# webui integration of core and updater
- core/ajax/update renders core templates :angry: 
- updater should consume a json based api to trigger and query for the current processing state
- core's own update ui should consume the json api
- no eventsource please :angry: 
##

**Comment by DeepDiver1975** [comment]
@karlitschek

**Comment by karlitschek** [comment]
looks good!

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/23913

**Comment by cmonteroluque** [comment]
how does this match with https://github.com/owncloud/updater/issues/204?

**Comment by DeepDiver1975** [comment]
I will merge the idea into this ticket.

**Comment by VicDeo** [comment]
@DeepDiver1975 there should be a room for integrity check as well.
Before or After or Before-n-After the process.

If it is done before the upgrade, integrity check cache should be flushed at the end of upgrade.

**Comment by VicDeo** [comment]
@DeepDiver1975 should substeps be invoked as a parameter passed to 
occ upgrade or as a new commands?

**Comment by DeepDiver1975** [comment]
We will add subtasks of occ upgrade. But this is out of scope for 9.1

**Comment by PVince81** [comment]
moving to backlog, needs rescheduling and scoping
