### ISSUE TITLE
Manual Import of Update Packages 

### ISSUE THREAD

**Issue by aspdye** [owncloud/updater#309]
Would be nice to have the possibility to feed the updater with new ownCloud Versions before the servers are feeding the updater :wink:

**Comment by VicDeo** [comment]
@aspdye Well, 
1. setup your own update server https://github.com/owncloud/administration/tree/master/update-server

2. override a server URL in config.php:
```
/**
 * URL that ownCloud should use to look for updates
 */
'updater.server.url' => 'https://updates.owncloud.com/server/',
```
3. Unlock new releases anytime :)
