### ISSUE TITLE
3rdparty folder not overwritten on update

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#316]
Ref https://github.com/owncloud/core/issues/23857#issuecomment-209290295

**Comment by LukasReschke** [comment]
It is missing in the array at https://github.com/owncloud/updater/blob/f2023372c602d199990ed8b399d8972afed02745/src/Utils/Locator.php#L53-L86

@VicDeo Any reason why this is excluded there? We need to update the folder on updates as well.

cc @karlitschek @jospoortvliet @DeepDiver1975

**Comment by LukasReschke** [comment]
Also how is this gonna work if in a future release we add new files or a folder somewhere? :confused:

**Comment by DeepDiver1975** [comment]
> It is missing in the array at https://github.com/owncloud/updater/blob/f2023372c602d199990ed8b399d8972afed02745/src/Utils/Locator.php#L53-L86

maybe related to the fact that the 3rdparty folder can live in a different location?

**Comment by VicDeo** [comment]
@DeepDiver1975 
> maybe related to the fact that the 3rdparty folder can live in a different location?

true. 
IIRC we agreed to drop this feature as it seems to be never used.
