### ISSUE TITLE
updater/update.log has to be stored in the data folder

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#317]
The updater/update.log file should NOT be publicly accessible as it leaks information and also breaks code signing. It needs to be stored in the data folder.

Ref https://github.com/owncloud/core/issues/23857#issuecomment-209312462

cc @karlitschek @jospoortvliet @VicDeo

**Comment by LukasReschke** [comment]
https://github.com/owncloud/updater/blob/62ce3ec4c4fac87c8263460491a016d5e8d959dc/app/config/container.php#L91 should use `$CONFIG['datadirectory']`.

**Comment by karlitschek** [comment]
agreed. I think I mentioned this in the past too that this should go into the data directory
