### ISSUE TITLE
getExtractionBaseDir should be deleted before code signature is verified

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#318]
Alternatively it should be extracted to a folder like `data/`. Otherwise this causes code signing errors.

Ref https://github.com/owncloud/core/issues/23857#issuecomment-209312462

cc @VicDeo

**Comment by VicDeo** [comment]
`data` can be on a different partition and PHP can not move directories across partitions (a known bug)

**Comment by LukasReschke** [comment]
*sigh*

Guess then we need "just" make sure that the code integrity is later verified again.

**Comment by VicDeo** [comment]
`_oc_upgrade` is removed in case of successful upgrade.

**Comment by LukasReschke** [comment]
Yes. But I somehow still saw this in the code signing errors. 

Is the code signing check performed after or before the folder is removed?

**Comment by VicDeo** [comment]
@LukasReschke 
>Is the code signing check performed after or before the folder is removed?

 it is performed with any `occ upgrade` and `occ upgrade` is invoked separately for core and every app

**Comment by VicDeo** [comment]
@LukasReschke was `_oc_upgrade` directory removed at the end of update process for the system in question?

**Comment by LukasReschke** [comment]
The problem seems the following:

1. Updater creates _oc_upgrade
2. Updater updates core
3. Integrity check is performed
4. Updater updates apps
5. Updater deletes _oc_upgrade

So the integrity check performed at step 3 will fail. Can we move the extraction dir to the data folder or make sure to rerun the integrity check as last step? 

Personally I'd prefer doing the extraction in an extracted dir. Anyways, for 9.0.2 we will probably just whitelist some folders for the sake of having a proper updater experience as discussed with @DeepDiver1975. For 9.1.x I'd appreciate some more thoughts on this.

**Comment by LukasReschke** [comment]
Whitelist and some more exceptions in the code checker code it is *sigh* 🙈
