### ISSUE TITLE
Make sure offered version is a version we can upgrade too

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#323]
If running updater from older version or the upgrade would result in skipping versions, do not offer it.

Quoting @karlitschek:

> In the future we should improve the logic further so that always the upgrade to the latest version is offered where upgrade is possible.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/administration-internal/pull/12 does exactly that 😉

**Comment by karlitschek** [comment]
yes. coming soon ;-)

**Comment by RealRancor** [comment]
Btw. also a duplicate of https://github.com/owncloud/appstore-issues/issues/4 :-)

**Comment by RealRancor** [comment]
@PVince81 @LukasReschke @karlitschek This one can be closed as https://github.com/owncloud/appstore-issues/issues/4 was implemented.

**Comment by LukasReschke** [comment]
Thank you, @RealRancor. Done :)
