### ISSUE TITLE
update to 8.2.1 was unsuccessful

### ISSUE THREAD

**Issue by ollyphobie** [owncloud/updater#328]
And now? an update doesn't work again. I don't know what to do now.

"Aktualisiere ownCloud auf Version 8.2.1. Dies könnte eine Weile dauern.

Update vorbereiten
Log-Level auf Debug gesetzt - aktuelles Level: "Warning"
Wartungsmodus eingeschaltet
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community."

**Comment by VicDeo** [comment]
@ollyphobie https://github.com/owncloud/core/issues/22362#issuecomment-183644634

**Comment by RealRancor** [comment]
@VicDeo I think this one can be closed? Not an issue of the updater app but the well known https://github.com/owncloud/appstore-issues/issues/4

**Comment by VicDeo** [comment]
Linking to https://github.com/owncloud/administration-internal/issues/13#issuecomment-216860799

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/administration-internal/issues/12
