### ISSUE TITLE
More spinners

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#330]
When you see this:
![updater-confusion](https://cloud.githubusercontent.com/assets/277525/14813790/a2ab3252-0ba3-11e6-970a-f6f50ad8b7b5.png)

You ask:
- is it doing anything ?
- do I need to input something or click the button at the bottom ?

Suggestions:
- [ ] hide/disable the bottom part while the upgrade is running
- [ ] add spinners behind each step while they are running

The only hint I had that it was still working was that my laptop fan was loud and `top` showed activity.

@jancborchardt @VicDeo

**Comment by PVince81** [comment]
Okay, looks like there are spinners, but due to this bug https://github.com/owncloud/updater/issues/331 the updater got stuck between two steps it seems.

Would still be good to at least grey out the bottom backup block.

**Comment by PVince81** [comment]
Spinner is missing when updating apps

**Comment by jancborchardt** [comment]
Yeah, there definitely should always be a spinner for the current step – I thought this was the case?

**Comment by VicDeo** [comment]
Part of #389
