### ISSUE TITLE
Move __apps into data folder

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/updater#332]
https://github.com/owncloud/updater/blob/8b971f9631aa6a6015ead3b48c7d8c72c24860f2/src/Command/ExecuteCoreUpgradeScriptsCommand.php#L106

Related to https://github.com/owncloud/updater/issues/331

**Comment by VicDeo** [comment]
@LukasReschke I'd say in other manner:
either allow to disable these apps https://github.com/owncloud/core/blob/master/core/shipped.json#L41
or *do not* try to disable these apps when they have incompatible versions.

`__apps` would not be needed in this case.

**Comment by LukasReschke** [comment]
So what is the __apps folder? Is it for storing incompatible app versions?

**Comment by VicDeo** [comment]
@LukasReschke not, it's for not dying in unsuccessful attempts to disable "incompatible" `files` app (and other apps from the list above)

**Comment by PVince81** [comment]
Can we do this in the next release instead and focus on the other problems ?

If you agree, please move to 9.0.3.
