### ISSUE TITLE
Redirect to OC / provide link after successful upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#344]
After a successful upgrade, there are no instructions or steps.

It would be nice to have a link like in the original update screen.
Suggestions:
1) After the "Done" step, add a link "Go back to ownCloud" that links to the main or admin page of the ownCloud instance

2) Make the cloud logo on the top-left link back to ownCloud

@owncloud/designers

**Comment by MorrisJobke** [comment]
> After a successful upgrade, there are no instructions or steps.

But on successful update following will happen:

1) there was a warning: A little text shows up that says "There was a warning - you need to refresh manual or click here (link to ownCloud)"
2) there was no warning: A little text shows up that says "The upgrade went fine. The page will reload soon and you could continue to use ownCloud"

Or am I wrong?

**Comment by PVince81** [comment]
@MorrisJobke the updater web UI doesn't show the progress as we used to:

![updater-success](https://cloud.githubusercontent.com/assets/277525/14953796/3c239082-106d-11e6-9458-f3cb797971a1.png)

**Comment by MorrisJobke** [comment]
Ah...sorry ... I missed this. I thought that this is about the stuff that is in core. Then nevermind my comment.

**Comment by jancborchardt** [comment]
If there are no errors whatsoever, would an automatic redirect be ok? Otherwise yeah, there should ideally both be a button »Back to ownCloud« (without the word »Go« in front) as well as a linkified logo in the top left.

**Comment by VicDeo** [comment]
Part of  https://github.com/owncloud/updater/issues/389
