### ISSUE TITLE
Wrong WebUI behaviour for stable channel. 'Open updater' button does not appear

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#364]
![updaterbe](https://cloud.githubusercontent.com/assets/10596560/16948284/2befbde2-4db4-11e6-8603-ae487161b6df.gif)

**Comment by davitol** [comment]
@VicDeo @PVince81

**Comment by PVince81** [comment]
This is likely because the channel switch event doesn't trigger update check. Maybe the update check is even done on the PHP side instead of ajax.

**Comment by PVince81** [comment]
Indeed, it seems that 9.0.2 doesn't even bother checking for updates when on the stable channel.
I checked the access_log and it doesn't call the update server.

**Comment by PVince81** [comment]
@davitol not a bug.

The reason is because we used the new config setting "updater.server.url" which doesn't exist in OC 9.0.2. I believe it was added in 9.0.3.

To test 9.0.2 updates with the test update server you need to use the magic sed command.

Can you confirm ?

**Comment by davitol** [comment]
@PVince81 This issue was produced due to I test adding update.server.url in config.php command and I also used the "magic sed command". If i remove the update.server.url from the config.php file it works fine, so let's close it
