### ISSUE TITLE
9.0.3 (daily) to 9.1.0 - Updater App unresponsive

### ISSUE THREAD

**Issue by necrevistonnezr** [owncloud/updater#365]
I'm on ownCloud 9.0.3 (daily) Build:2016-06-29T09:50:42+00:00, self-hosted, PHP 7, PostgreSQL.
After the security warning today, I logged into my owncloud. 
Updater app shows "owncloud 9.1.0 available".
Started the updater app in the admin section.
What I get is an unresponsive updater screen without any formatting (see attached screenshot). No link or button is working. 

![fireshot capture 10](https://cloud.githubusercontent.com/assets/8191935/16956201/cf5db808-4dd7-11e6-9d12-fec1afbcf08a.png)

**Comment by VicDeo** [comment]
@necrevistonnezr please reopen if the link above doesn't apply to you and if the issue is still reproducible with ownCloud 10.0.0+
