### ISSUE TITLE
Updater sometimes deletes core apps

### ISSUE THREAD

**Issue by Pazu** [owncloud/updater#37]
I have, on more than one occasion, found core apps such as files_trashbin and files_versions missing after using the updater.

I updated from 7.0.1 to 7.0.2 on 2014-08-30T08:30 and subsequently discovered the apps/files_versions directory was completely missing. There is *nothing* in owncloud.log about the update, much less anything having gone wrong.

The only indication was an error because code in files_trashbin depended on files_versions being present, and those errors began shortly after the update took place (see https://github.com/owncloud/core/issues/11387).

1) the Updater app should do *some* logging
2) how could such an important directory be deleted and not replaced during update?

**Comment by VicDeo** [comment]
@Pazu I'm not afraid to look like a slowpoke but your webserver error log might have an information on timeout.

**Comment by Pazu** [comment]
@VicDeo I've been waiting for this to recur, but it hasn't, yet. I'm presently on 7.0.3, and will probably be migrating to 8.0.3 once that's out.

**Comment by VicDeo** [comment]
@Pazu please let me know whether this is still an issue.

**Comment by VicDeo** [comment]
Closing due to lack of feedback. Please reopen if this is still an issue.
