### ISSUE TITLE
Updater no longer works updating from 8.2.7 to 9.0.5

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#378]
Using this PR for updating https://github.com/owncloud/administration-internal/pull/32

Update from ~~8.0.7~~  8.2.7 to 9.0.5. --> After the update, the apps section looks like this:

![screen shot 2016-09-21 at 12 57 58](https://cloud.githubusercontent.com/assets/10596560/18709096/9acb0484-7ffe-11e6-8f40-5b8d8f61c831.png)

The following error appears if I try to update via daily channel again:
![screen shot 2016-09-21 at 13 17 57](https://cloud.githubusercontent.com/assets/10596560/18709066/741da094-7ffe-11e6-9a5e-6b8e7f821547.png)

running sudo -u www-data ./occ config:list

```
 "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
```
@VicDeo @PVince81  any idea? Do not hesitate to ping me via IRC or GitHub and I'll share my testing environment

**Comment by PVince81** [comment]
Hmm, I thought we forced updating from 8.0.7 to 8.0.15 first

**Comment by PVince81** [comment]
Which channel did you use that allowed you to skip 8.0.15 ?

**Comment by davitol** [comment]
@PVince81 Typo when I wrote the issue. The scenario was 8.2.7 (stable) to 9.0.5 via daily channel. Sorry for the mistake 😞

**Comment by VicDeo** [comment]
Updater app should be disabled for 9.0 because there is a standalone updater there (which is not an app)

**Comment by VicDeo** [comment]
@davitol does patching with https://github.com/owncloud/core/pull/26031/files help?

**Comment by davitol** [comment]
> @davitol does patching with https://github.com/owncloud/core/pull/26031/files help?

@VicDeo That patch is for master 9.2 version and the problem appears after upgrading to 9.0.5.
I don't know how can I apply that patch to my server

**Comment by VicDeo** [comment]
@davitol basically what you need is to replace
```
		if (!in_array($this->request->getRemoteAddress(), ['::1', '127.0.0.1', 'localhost'])) {
```

with 
```
 		$allowedHosts = ['::1', '127.0.0.1', 'localhost'];
 		if (isset($this->request->server['SERVER_ADDR'])){
 			array_push($allowedHosts, $this->request->server['SERVER_ADDR']);
 		}
 
 		if (!in_array($this->request->getRemoteAddress(), $allowedHosts)) {
```
in core/Controller/OccController.php validateRequest

**Comment by davitol** [comment]
@VicDeo Replaced and the problem keeps happening

**Comment by VicDeo** [comment]
@davitol can you please also change https://github.com/owncloud/core/blob/stable9/core/controller/occcontroller.php#L113
to `$e->getMessage(),`  to see a real reason instead of 'Not allowed'?

**Comment by davitol** [comment]
> @davitol can you please also change https://github.com/owncloud/core/blob/stable9/core/controller/occcontroller.php#L113
> to $e->getMessage(), to see a real reason instead of 'Not allowed'?

![screen shot 2016-10-04 at 12 28 30](https://cloud.githubusercontent.com/assets/10596560/19070982/25b1ec8c-8a2e-11e6-920b-b2d9447006eb.png)

**Comment by PVince81** [comment]
@VicDeo I suspect that this won't work in all setups. This is because sometimes the remote host name in one network is not the same as in another network. So when calling `getRemoteUser()` from the request it might not always return the same name as seen from the outside.

**Comment by VicDeo** [comment]
@PVince true. doesn't work for docker containers at least.
I will add fallback to localhost

**Comment by PVince81** [comment]
@VicDeo will you add the fallback to the backports or do it separately ?

**Comment by VicDeo** [comment]
@PVince81 I think it's better test it at once

**Comment by PVince81** [comment]
@davitol @VicDeo solved ?

**Comment by davitol** [comment]
@PVince81 @VicDeo 8.2.7 to 9.0.5. via daily channel no longer has the 'Web executor is not allowed...' issue, but it has the following integrity check problems:

```
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [provisioning_api] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by PVince81** [comment]
does the error disappear if you continue updating to the latest ?

it is likely because you updated from 8.2.7 instead of 8.2.8

**Comment by davitol** [comment]
> it is likely because you updated from 8.2.7 instead of 8.2.8

It also happens updating from 8.2.8 via daily channel to 9.0.5. Continuing updating the 9.0.5 to 9.1.1 via beta channel the integrity check warnings are no longer shown.

**Comment by davitol** [comment]
@VicDeo @PVince81 due to Web executor is not allowed...' issue is no longer happening I feel OK about closing this issue
