### ISSUE TITLE
Web updater must use localhost when calling occ http endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#390]
### Steps

1. Set up ownCloud **without** using "localhost", make sure to use a proper host name: ex: "http://example.com/owncloud"
1. Set up a local update server that delivers 9.1.1 on the beta channel (or any channel)
1. Set up OC 9.0.5 or 9.1.0
1. Change config.php to point to the update server
1. Switch the channel to make OC get the 9.1.1 update
1. Run the update

### Expected result
Update can be started

### Actual result
Start button does not appear but error instead:
```
 
 [UnexpectedValueException] 
 Could not parse a response for config:list. Please check if the current shell user can run occ command. Raw output: 
 Not allowed 
 
```

A bit of debugging shows that the updater code is trying to connect to "example.com" instead of "localhost", so the OccController in core will receive "example.com" as remote host and will deny the update.

Side note: it would be good to have a way to disable occ web update and force CLI occ update instead if allowed to bypass such bugs.

@VicDeo please have a look.
CC @davitol 

Any workarounds ? This is blocking the publication of the 9.1.1 update.
Maybe we can publish it but tell people to use the occ CLI updater instead for this one update.

Thanks.

**Comment by PVince81** [comment]
or a quick patch for 9.1.0 to force it to localhost ?

**Comment by VicDeo** [comment]
@PVince81 Does patching `OccController::validateRequest` according to  https://github.com/owncloud/core/pull/26031/files#diff-1b29c3a8398e3ed87e772fb50a729633L125 help?

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/updater/issues/378
