### ISSUE TITLE
Trying to update via CLI to daily version if you are already in daily produces an error

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#392]
Running in oC daily-master

```
php updater/application.php upgrade:start
```

![screen shot 2016-10-04 at 17 12 34](https://cloud.githubusercontent.com/assets/10596560/19079975/ca049542-8a55-11e6-832f-482406c9ccbf.png)

and the server is no longer available:

![screen shot 2016-10-04 at 17 14 35](https://cloud.githubusercontent.com/assets/10596560/19080040/141fbb34-8a56-11e6-9905-d18b9f4eef81.png)

I guess it should not be allowed to run this command if you are already in daily version?

@VicDeo @PVince81

**Comment by VicDeo** [comment]
@davitol 
>I guess it should not be allowed to run this command if you are already in daily version?

Nope, it's ok.

It looks like  you've just tried to install an older  daily over more recent one.

**Comment by VicDeo** [comment]
@davitol  update server misconfiguration
We provide owncloud-daily-master.zip for 9.1.x
http://updates.owncloud.com/server//?version=9x1x4x0x5x6xdailyxdailyxdas

and owncloud-daily-stable9.1.zip for 9.2 :boom: 
http://updates.owncloud.com/server//?version=9x2x0x0x5x6xdailyxdailyxdas

**Comment by PVince81** [comment]
the new update server will deliver stable releases on the daily channel until OC reaches master, in which case it delivers daily master

**Comment by PVince81** [comment]
@VicDeo @davitol new updater (undeployed) was adjusted.

**Comment by davitol** [comment]
Let's close this issue then? :+1: Checked and it works with the new updater

**Comment by PVince81** [comment]
Thanks
