### ISSUE TITLE
Trying to update from 9.1.1 to daily version via CLI does not work

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#393]
running 
```
sudo -u www-data php updater/application.php upgrade:start
```
and trying to update to daily version I got this message:

```
[RuntimeException]                               
  Cannot override frozen service "utils.docLink". 
```

@VicDeo @PVince81

**Comment by davitol** [comment]
Also at least for 9.1.0

**Comment by VicDeo** [comment]
@davitol pushed to https://github.com/owncloud/updater/issues/394

**Comment by PVince81** [comment]
@davitol is 9.0.4 affected as well ?

**Comment by VicDeo** [comment]
@PVince81 no, doclink was added since 9.1

**Comment by VicDeo** [comment]
Closing as fixed with https://github.com/owncloud/updater/pull/394
