### ISSUE TITLE
Cannot update via webUI from 9.1.1. to daily 

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#397]
![screen shot 2016-10-13 at 13 56 24](https://cloud.githubusercontent.com/assets/10596560/19348394/f6a40886-914d-11e6-9cfa-eb4a4fc29529.png)
Applying the following patch to log the reason of the failure --> https://github.com/owncloud/core/pull/26277

I got in owncloud.log:

```
{"reqId":"LUPJWlCQ8mFArHTnlIiZ","remoteAddr":"172.17.0.1","app":"core","message":"Invalid request to occ controller. Details: \"Web executor is not allowed to run from a host 172.17.0.1\"","level":2,"time":"2016-10-13T12:03:02+00:00","method":"POST","url":"\/index.php\/occ\/config:list","user":"--"}
```
@VicDeo @PVince81

**Comment by VicDeo** [comment]
@davitol the same with https://github.com/owncloud/updater/issues/378
The fix is forward port https://github.com/owncloud/updater/pull/395/commits/f93993ff5f2759054c4875e58dd2bb7d5543bec4 to stable9.1

**Comment by davitol** [comment]
@VicDeo https://github.com/owncloud/updater/pull/395 solves the issue for CLI and webUI, but the one related to 9.1 that is https://github.com/owncloud/updater/pull/394 does not fix the webUI issue. This PR only fixes the CLI update

**Comment by VicDeo** [comment]
@davitol exactly, but for a docker environment you need a forward port of https://github.com/owncloud/updater/pull/395/commits/f93993ff5f2759054c4875e58dd2bb7d5543bec4 to stable9.1 which has been pushed just now as https://github.com/owncloud/updater/pull/395

**Comment by VicDeo** [comment]
@davitol Thanks for testing
 btw,  while porting the fix i spotted PHP 5.4-specific issue  :cactus:

**Comment by PVince81** [comment]
@davitol solved ?

**Comment by davitol** [comment]
> btw, while porting the fix i spotted PHP 5.4-specific issue

@VicDeo did you file an issue with that stuff? If you did, please let me know which is.



> @davitol solved ?

@PVince81 Yes, it is solved with https://github.com/owncloud/updater/pull/398 modifications, but that PR is pending to have a patch that will apply on top of v9.1.1 :+1:

**Comment by VicDeo** [comment]
@davitol No, I didn't. Just pushed a fix at once https://github.com/owncloud/updater/pull/399

**Comment by VicDeo** [comment]
stable9.1/master needs more than just forwardporting stable9 changes according to my recent tests.

**Comment by PVince81** [comment]
Ok, so I guess this ticket can be closed now ?

**Comment by davitol** [comment]
@PVince81 Yes, Iet's close it
