### ISSUE TITLE
Properly update docs

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#402]
### Steps:

1. Setup owncloud-daily-master in a folder "owncloudtest-daily"
1. Setup owncloud-daily-stable9.1 in another folder "owncloudtest"
1. While testing had to patch according to https://github.com/owncloud/updater/pull/400, but likely unrelated
1. Update "owncloudtest" to daily master (need editing "version.php" and changing the build date to a past date and possibly a patched update server)

### Expected result
Updated build is 100% like a new install, or at least have all files.

### Actual result
Documentation and theme not updated properly.

This is the diff:
```
Only in owncloudtest-daily: COPYING
Binary files owncloudtest/data/admin/files/ownCloud Manual.pdf and owncloudtest-daily/data/admin/files/ownCloud Manual.pdf differ
Only in owncloudtest/data: update.log
Only in owncloudtest/data: updater-data
diff -r owncloudtest/themes/example/defaults.php owncloudtest-daily/themes/example/defaults.php
142c142
<               return $this->getDocBaseUrl() . '/server/9.1/go.php?to=' . $key;
---
>               return $this->getDocBaseUrl() . '/server/9.2/go.php?to=' . $key;
```

I wonder whether we ever updated the theme, if we didn't then it would explain issues like https://github.com/owncloud/core/issues/26451

@VicDeo @davitol

**Comment by RealRancor** [comment]
> I wonder whether we ever updated the theme,

AFAIK themes where never updated. Thats why they are disabled during each update / upgrade.

**Comment by PVince81** [comment]
Ah yes, indeed. That code is only the default theme.
And now I see that the PDF file is from the data dir.

Non-issue => closing

**Comment by PVince81** [comment]
Ah wait, the "COPYING" file remains.
