### ISSUE TITLE
Check version once again after package extraction

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#406]
To prevent https://github.com/owncloud/updater/pull/401#issuecomment-255055213

**Comment by PVince81** [comment]
will this need backports ? if set, please set label

**Comment by PVince81** [comment]
@VicDeo any update ? Important for 9.2 I guess ? What about backports ?

**Comment by VicDeo** [comment]
@PVince81  it was reproducible in the wild only during our internal testing.  A misconfigured update server is required for reproduction.
From the other side  an additional protection measure is always good. So I'm for backporting.

**Comment by PVince81** [comment]
@VicDeo if backport properly done (I can't see/find it), please remove backport label

**Comment by VicDeo** [comment]
@PVince81 It is in 10+ but has been not ported to stable9.1. 
Given that since 2017-07-21 stable9.1 reached `security-only` phase I think it is not worth an effort.
