### ISSUE TITLE
8.2.8 updater doesn't update provisioning_api app

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#410]
### Steps

1. Install 8.2.8 from tarball
1. Update to 9.0.4 (used a patched update server with stable channel)
1. Check app version for "provisioning_api"

### Expected result
App is updated to version 0.4.1 and contains a signature file.

### Actual result
App is not updated, still on version 0.3.0.
The reason why the integrity check doesn't find it was raised here: https://github.com/owncloud/core/issues/26463

This ticket here is about fixing the OC 8.2 update to properly update the provisioning_api app.

@VicDeo @davitol

**Comment by PVince81** [comment]
Note: as long as we don't fix this we can't provide a stable update from 8.2 to 9.0 in the updater !

**Comment by VicDeo** [comment]
@PVince81 sadly it isalready fixed with https://github.com/owncloud/updater/pull/384

**Comment by VicDeo** [comment]
I'll retest with 8.2.9RC2

**Comment by VicDeo** [comment]
@PVince81 @davitol
Not reproducible on my side with 8.2.9RC2 anymore.
 I guess this can be closed?
