### ISSUE TITLE
No update detected with OC 9.1.0.15

### ISSUE THREAD

**Issue by 1Fopresta** [owncloud/updater#411]
Hi, with OC 9.1.0.15, when i use sudo -u www-data php updater/application.php upgrade:detect, i obtain this result : 
Current version is 9.1.0.15
No updates found online

Test with channel stable

Php version is 7.0.8

**Comment by PVince81** [comment]
Note: at this time there should be at least an update to 9.1.1 proposed. (9.1.2 update is being tested currently and will appear later)

@VicDeo

**Comment by VicDeo** [comment]
@1Fopresta does this help?
https://github.com/owncloud/updater/pull/388/files

**Comment by martinclaus** [comment]
I have the same issue with the same version of OC.
@VicDeo Your proposed patch did not help, still not finding any update.

**Comment by VicDeo** [comment]
@PVince81 server hiccup?
9.0 feed (correct): http://updates.owncloud.com/server//?version=9x0x0x15x5x6xstablexxdas
9.1 feed (empty): http://updates.owncloud.com/server//?version=9x1x0x15x5x6xstablexxdas

**Comment by PVince81** [comment]
@crrodriguez is there any kind of caching on that server ?

**Comment by crrodriguez** [comment]
@PVince81 not that I am aware of..

**Comment by 1Fopresta** [comment]
Ok, it is not a bug of the updater because the 9.1 feed is empty.
Now, why this feed is empty ? The version 9.1.1 arrived the 20 september and the version 9.1.2 arrived the 8 novembre ?

**Comment by PVince81** [comment]
9.1.2 wasn't deployed yet to the server (needs QA testing first). But the update server must already deliver 9.1.1, not an empty feed.

**Comment by VicDeo** [comment]
@1Fopresta feed has been updated, 9.1.2 is online please retry

**Comment by VicDeo** [comment]
@1Fopresta as you are on 9.1.0 please check this post https://central.owncloud.org/t/patches-for-known-update-issues-from-version-9-0-4-9-0-5-9-1-0-9-1-1/3549 before updating

**Comment by VicDeo** [comment]
Closing as fixed. Please reopen if it is not

**Comment by 1Fopresta** [comment]
Hi, sorry for the delay.
Everything works (with the patch https://central.owncloud.org/t/patches-for-known-update-issues-from-version-9-0-4-9-0-5-9-1-0-9-1-1/3549)
All my servers on 9.1.0 are now on 9.1.2

Thanks all :)
