### ISSUE TITLE
Updater »Unable to move«: ownCloud 8.1.4. -> 8.1.11 

### ISSUE THREAD

**Issue by zooomak** [owncloud/updater#415]
Hi,
yes, I'm very late ;-) I have trouble updating my ownCloud.
Error and log attached. 

Could you help here please?
Thanks a million!

_Error message of updater (UI):_
**Update fehlgeschlagen.Unable to move /www/htdocs/PAGE/cloud.PAGE.de/_oc-upgrade/8.1.11/core/core to /www/htdocs/PAGE/cloud.PAGE.de/core**

_Log:_
```
- opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/PAGE/cloud.PAGE.de/lib/private/tempmanager.php#179	
- Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	
- rename(/www/htdocs/PAGE/cloud.PAGE.de/_oc-upgrade/8.1.11/core/core,/www/htdocs/PAGE/cloud.PAGE.de/core): Directory not empty at /www/htdocs/PAGE/cloud.PAGE.de/apps/updater/lib/helper.php#45
- in_array() expects parameter 2 to be array, null given at /www/htdocs/PAGE/cloud.PAGE.de/apps/updater/lib/location/core.php#35	
- Undefined index: 8.1 at /www/htdocs/PAGE/cloud.PAGE.de/apps/updater/lib/location/core.php#26	
- Success: 3rdparty	
- Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0
```	

Beste, Tobi

**Comment by VicDeo** [comment]
@zooomak 
1. Please start with replacing your `apps/updater` with the most recent version for stable8.1 
https://github.com/owncloud/updater/archive/v8.1.12.zip

2. According to 
```
- opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/PAGE/cloud.PAGE.de/lib/private/tempmanager.php#179
```

 your ownCloud can't work with temporary files due to environment misconfiguration.
According to PHP settings `/tmp`is claimed to be a temp dir but this dir is not writable for user that is used to run PHP scripts

**Comment by zooomak** [comment]
Perfect, thanks for your quick help. Much appreciated!

**Comment by zooomak** [comment]
Now I was maybe getting too hungry.
Trying to upgrade to version 9 with Updater app. Result Error 500, white page.

Log file says:
`{"reqId":"WMFzkFUNmYwAABsFYWsXXXN","remoteAddr":"178.19.000.174","app":"PHP","message":"Class 'OCA\\Updater\\App' not found at \/www\/htdocs\/domain\/cloud.domain.de\/apps\/updater-8.1.\/appinfo\/app.php#16","level":3,"time":"2017-03-09T15:24:00+00:00","method":"GET","url":"\/cloud.domain.de\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"Username"}
`
No I'm confused ;-)
Do you maybe have another idea here?

**Comment by VicDeo** [comment]
@zooomak you need to  rename `updater-8.1.` to `updater`

**Comment by VicDeo** [comment]
@zooomak is it working now?

**Comment by zooomak** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hi, haft way...
Thanks for coming back here.

I have a notification to update to 9.0.8 (from 9.0.6).
When I hit the update button in the updater app, there is no reaction.

Beste, Tobi

 



VicDeo schrieb am 21.03.2017 20:03:


@zooomak is it working now?

**Comment by VicDeo** [comment]
I'm closing this issue as soon as everything except unresponsive button was addressed. 
Unresponsive 'Update' button is tracked here https://github.com/owncloud/updater/issues/453
