### ISSUE TITLE
Cannot update via webUI from oC 9.1.5 to oCX RC4

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#421]
![screen shot 2017-04-25 at 13 07 06](https://cloud.githubusercontent.com/assets/10596560/25382945/1b9fd566-29ba-11e7-8d04-f98de76259c4.png)

**Server logs**

```{"reqId":"5bXNpSKrb8WDAwdT9kNY","level":3,"time":"2017-04-25T10:55:10+00:00","remoteAddr":"::1","user":"--","app":"index","method":"POST","url":"\/index.php\/occ\/upgrade","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM `accounts` WHERE `lower_user_id` = :dcValue1' with params [\\\"\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.accounts' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM `...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(252): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(285): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(379): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/AccountMapper.php(59): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(151): OC\\\\User\\\\AccountMapper->getByUid(NULL)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Group\\\/Manager.php(420): OC\\\\User\\\\Manager->get(NULL)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/user.php(326): OC\\\\Group\\\\Manager->inGroup(NULL, 'admin')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(450): OC_User::isAdminUser(NULL)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(354): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->isAdminUser()\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->OC\\\\AppFramework\\\\DependencyInjection\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(389): Pimple\\\\Container->offsetGet('SecurityMiddlew...')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->OC\\\\AppFramework\\\\DependencyInjection\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(334): Pimple\\\\Container->offsetGet('MiddlewareDispa...')\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->OC\\\\AppFramework\\\\DependencyInjection\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(90): Pimple\\\\Container->offsetGet('Dispatcher')\\n#17 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'execute', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/opt\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match('\\\/occ\\\/upgrade')\\n#21 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}"}```

**Apps list**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

@VicDeo

**Comment by PVince81** [comment]
@VicDeo solved ?

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/core/pull/27965 in RC4
