### ISSUE TITLE
Updater from 9.1.5.2 doesn't show upgrade to 10.0.0

### ISSUE THREAD

**Issue by HenningSchulz** [owncloud/updater#423]
Hi!
I'm on the stable feed but my updater says:

> Current version is 9.1.5.2
> No updates found online.

When I switch to beta it says 10.0.0 is available. Am I doing something wrong or is 10 not in the stable feed right now? owncloud.org says stable feed is at 10.0.0

Thank you!

**Comment by VicDeo** [comment]
@HenningSchulz 
Right now cross version updates are allowed from 8.2.11 to 9.0.9 for daily channel.
9.0.x to 9.1.x and 9.1.x to 10.0.x are disabled on purpose.

**Comment by VicDeo** [comment]
9.1.6 to 10.0.3 is unlocked for the stable channel now.
