### ISSUE TITLE
Cannot update via webUI from 10.0.0 to 10.0.2. The button of the UI seems useless

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#429]
Clicking on 'open updater' button, the updater is not launched. 

![screen shot 2017-06-02 at 10 01 29](https://cloud.githubusercontent.com/assets/10596560/26716990/ece515ee-477b-11e7-8b8f-7868aa9362f3.png)

Note: No logs in owncloud.log

@VicDeo

**Comment by VicDeo** [comment]
@davitol yes. unfortunately.

it's already fixed in 10.0.1 
Here is hotfix for 10.0.0 https://central.owncloud.org/t/patches-for-known-update-issues-from-version-10-0-0/7911
