### ISSUE TITLE
No updates for 'ownCloud 9.0.10 (production)'

### ISSUE THREAD

**Issue by MasterCassim** [owncloud/updater#431]
The updater app does not show any updates for my ownCloud version:

'ownCloud 9.0.10 (production)'
'Your version is up to date.'

There are no updates to 9.1 or 10.0; what can I do?

**Comment by VicDeo** [comment]
@MasterCassim 9.0.10 is the most recent version for 9.0
I expect that we will allow 9.0 to 9.1 migration at the stable (not production) channel soon.

Right now only manual migration is possible.

**Comment by MasterCassim** [comment]
Is there any way I can find out which is the most recent version? or which updates are allowed?

**Comment by VicDeo** [comment]
@MasterCassim I'm not sure I understand you question correctly. 
This page contains most recent releases https://owncloud.org/changelog/

Manual upgrade is described here https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html

In general it is always recommended to migrate to the latest dot release first and then to the latest dot for the next major release. (e.g. 9.0.5 to 9.0.10 and then to 9.1.6. Given that 9.0.10 is the most recent 9.0 release and 9.1.6 is the most recent 9.1 release)
Additionally 10.0.2 could be upgraded directly from 9.0.10 skipping 9.1.6

As soon as you have 9.0.10 and it is currently the last dot release for 9.0.x you are free to choose 9.1.6 or 10.0.2 as a target.

P.s. I should warn you that 10.0.x uses brand new appstore so it has less 3rdparty apps available right now.

**Comment by MasterCassim** [comment]
I mean where can I find the versions which are supported by the updater app. I'm not a big fan of manual updates :) never did one

**Comment by VicDeo** [comment]
@MasterCassim you can temporary switch to `beta` channel to get 9.1.6 
I've just  checked - it is serving `9.1.6` release  for `9.0.10` right now

**Comment by VicDeo** [comment]
@MasterCassim don't forget to backup your database before update ;)
Also please switch back to `production` channel after update - once we have real betas we will push them to this channel again.

**Comment by MasterCassim** [comment]
Cool; I'll try that tomorrow, thanks. I'm currently on stable, don't know why the version is showing 'production'. Where did you check that 9.1.6 is served for 9.0.10? Is there a list somewhere in this repo?

**Comment by VicDeo** [comment]
@MasterCassim TBH I've upgraded my personal 9.0.10 to check this :) 

it is possible to check the channels in this file
https://github.com/owncloud/administration/blob/master/update-server/config/config.php

**Comment by VicDeo** [comment]
9.0 to 9.1 is possible via `stable`  channel now.
Given that 9.0 is close to EOL we will unock it for `production` channel soon
