### ISSUE TITLE
Upgrade -> Maintenance Mode -> Disable apps 

### ISSUE THREAD

**Issue by voroyam** [owncloud/updater#481]
Many users on central report that they are left with a broken instance if they upgrade their ownCloud with the web updater.

The reason for it are apps, that are not part of core. These apps have to be disabled before upgrading.

To circumvent this, I suggest a check, before the upgrade process, after you click on the upgrade button.

If the check finds a problematic app - it would display a warning, maybe a link to the apps section to disable the app in the web UI.

As it is right now, from my pow, community users will probably stop using / upgrading ownCloud if it breaks every time they want a new version. Every fifth topic I read in central is about web upgrading.

**Comment by PVince81** [comment]
@VicDeo thoughts on this ?

This might be because we stopped disabling third party apps automatically as part of `occ upgrade`: https://github.com/owncloud/core/pull/27730

Not sure how the updater could find problematic apps apart from checking if their "max-version" matches. And even then, they'd get automatically disabled during `occ upgrade` phase of web updater, unless that part is not reached due to other app related issues.

**Comment by PVince81** [comment]
@voroyam do you have some links about the many update cases related to problematic apps ? maybe we can find a pattern in said apps that could help with "problematic app detection"

**Comment by voroyam** [comment]
@PVince81 I would have to search central for specific cases, but I could do this.

In my experience it's always the template editor, since it was part of core and then became non core.

My suggestion would be that we create a new tag, core app, and filter apps that do not have this tag.

**Comment by PVince81** [comment]
Hmmm, so the template editor is a special case then. We might need a specific fix for this one case if it's troublesome. Some other apps will also be removed from the core bundle so the issue would appear for other former core apps as well.

**Comment by voroyam** [comment]
the latest one:

https://central.owncloud.org/t/cannot-login-after-upgrade-to-10-0-0-9/15306

**Comment by voroyam** [comment]
ownCloud broken because of PHP dependencies:

https://central.owncloud.org/t/missing-depenency-in-owncloud-files-10-0-9-1-2-noarch-rpm/15589

**Comment by voroyam** [comment]
> Don't know what central is

it's the new user forum.

https://central.owncloud.org/
