### ISSUE TITLE
ownCloud 7.0.2 -> 7.0.3 update failed unclearly

### ISSUE THREAD

**Issue by equaeghe** [owncloud/updater#50]
![failed_owncloud_update](https://cloud.githubusercontent.com/assets/601177/5134278/dadd5f48-710c-11e4-93df-d6c085b714d2.png)

There is *no* log entry from the time I tried this update.

On a previous failed try, I got:

    Backup creation failed. Check permissions.

No indication about *which* permissions and how to change them. So I Googled, not finding much concrete about the permissions except for [a blog](https://www.techbeast.net/2014/08/31/owncloud-permissions-error-upgrade/) which advised doing

    chown -R www-data:www-data owncloud

which gave me more lines than my ssh history of `operation not permitted`.

After this, I nevertheless tried the updater again (hoping there had been some successful pre-historical `chown`s). The result is the screenshot above.

Please advise on further action. (I guess the bug I'm reporting is the lack of concretely useful feedback when the update fails.)

**EDIT:** I tried it again, got the same error message, went to refresh the list of backups... and then the update started and seems to have finished correctly. Strange, but nice outcome; so no advice on further action is needed.

**Comment by equaeghe** [comment]
@VicDeo: The 7.0.3 to 7.0.4 update went smoothly, so I have no further input at this time. (I prefer not to do the manual file replace as I have preciously little time to manage my ownCloud instance.)

**Comment by DeepDiver1975** [comment]
case closed from my pov
