### ISSUE TITLE
[decouple] Updater 1.0.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#510]
https://github.com/owncloud/updater/releases/tag/v1.0.0RC1

to be tested as part of 10.2 RC1 QA

@patrickjahns FYI

**Comment by VicDeo** [comment]
:see_no_evil:

**Comment by VicDeo** [comment]
in this case updatenotification app should check for updater presence before redirecting to it.

**Comment by PVince81** [comment]
@VicDeo we'll still bundle it for now in the release script.

we can talk about full debundling later on if we want to support separate updates for the updater... interesting concept...

**Comment by VicDeo** [comment]
@PVince81 we can download updater from the update server and remove it after the update :ghost:

**Comment by PVince81** [comment]
Test plan here: https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Updater.md
