### ISSUE TITLE
Updater 1.0.1

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#525]
### Reason

- Release needed for https://github.com/owncloud/updater/pull/521 https://github.com/owncloud/updater/pull/522 https://github.com/owncloud/updater/pull/523 https://github.com/owncloud/updater/pull/524 
https://github.com/owncloud/updater/pull/526
https://github.com/owncloud/updater/pull/527  
https://github.com/owncloud/updater/pull/528

- [x] update version to 1.0.1 in https://github.com/owncloud/updater/blob/1b1db6100298f333618f467e3b07a6ac2dcecf4f/app/config/container.php#L158

**Comment by micbar** [comment]
@davitol RC1 in https://github.com/owncloud/updater/releases/tag/v1.0.1RC1

**Comment by davitol** [comment]
> @davitol RC1 in https://github.com/owncloud/updater/releases/tag/v1.0.1RC1

Tarball tested and LGTM (10.2.1 to 10.3.0 in different scenarios)

**Comment by micbar** [comment]
Final in https://github.com/owncloud/updater/releases/tag/v1.0.1

**Comment by VicDeo** [comment]
Released with OC 10.3.2
