### ISSUE TITLE
updater fails to update 7.0.2 to 7.0.3 at extraction

### ISSUE THREAD

**Issue by chriskloe** [owncloud/updater#53]
Message on screen: 

"Empfangen des Paketes fehlgeschlagen

Das Update ist fehlgeschlagen. Bitte überprüfen Sie die Logs auf der Administratorseite und melden Sie dieses Problem an die ownCloud Gemeinschaft."

Messages in log:
Error 	updater 	/share/Web/e0fe98582f33fefdf2ca9cc0411c748c.zip extraction error 	2014-11-21T20:22:47+00:00
Error 	updater 	Retrieving http://download.owncloud.org/community/owncloud-7.0.3.zip 	2014-11-21T20:22:47+00:00
Error 	PHP 	ZipArchive::extractTo() [<a href='ziparchive.extractto'>ziparchive.extractto</a>]: Invalid or unitialized Zip object at /share/MD0_DATA/Web/owncloud/lib/private/archive/zip.php#135 	2014-11-21T20:22:46+00:00 

Maybe it would also be a good idea to keep the chapter "update" in the docs since there's no documented alternative way to update.
Maybe also updating (and also upgrading) using occ including backup would be a great idea.....

**Comment by VicDeo** [comment]
@chriskloe 
Closing as resolved. Feel free to open a new issue if needed :)
