### ISSUE TITLE
Convert CI to drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/updater#582]
Travis no longer works.

- [x] activate drone for this repo (I have emailed sysadmin to get that done) - done
- [x] remove Travis from the "required" CI in GitHub settings
- [x] convert CI to use drone
- [x] do code coverage and analysis with SonarCloud #588 
- [x] enable `codestyle` #589 
- [x]  `phan` #590 
- [x] and `phpstan` #590

**Comment by micbar** [comment]
Good work, please move on @phil-davis

**Comment by phil-davis** [comment]
@micbar can you remove `continuous-integration/travis-ci` from the required CI results - I guess that is in the GitHub repo settings.

**Comment by phil-davis** [comment]
The basic part has been done in PR #583 

@jasson99 now try to enable the other things like SonarCloud, code-style, phan, phpstan. (not all in one PR!) If they are easy to enable, and we do not have to edit/fix "too much" code then it would be useful to have these tools running in CI, like they do in other repos.

**Comment by phil-davis** [comment]
We have SonarCloud running. Next week @jasson99 can try code-style, phpstan and phan - if those are easy then we may as well have them running in this repo to standardize like other repos.

**Comment by phil-davis** [comment]
All done :rocket:
