### ISSUE TITLE
atualização do owncloud para a versão atual

### ISSUE THREAD

**Issue by cirineu23** [owncloud/updater#595]
estou a usar o owncloud 8.2 no serviço, mais estou com dificuldade de atualizar para a versão recente para poder ser compatível com o cloud do telemóvel [
![image](https://user-images.githubusercontent.com/78731875/118646446-1ea6d100-b7d8-11eb-89aa-e6263ebbfc40.png)
](url)

**Comment by VicDeo** [comment]
sorry, it's hard for me to translate Portuguese without being able to copy it.
