### ISSUE TITLE
Updater deletes valuable unknown items in DocRoot

### ISSUE THREAD

**Issue by timreeves** [owncloud/updater#64]
I just updated two installations from 7.0.1 to 7.0.4, i.e. I was using a fairly old version of the updater so cannot say if the problems noted here still exist - but I rather expect that the second one does.
* I got only empty messages when things went wrong, same as picture in [issue 50](https://github.com/owncloud/updater/issues/50)
* The updater moves anything unknown in the docroot into its backup directory and leaves it there. This is very annoying - my nginx "owncloud.conf" disappeared, as did a directory "external", under which I keep various external local storage elements. I do this because it allows me to have an empty open_basedir, which is prerequisite for something (I think something in Sabre / Pear, can't remember exactly). So I think that the default action to leave anything unrecognised where it is would be much more user-friendly! At the moment I have to release the external local storages, move my "external" directory out of the docroot, and after the update move it back and reconnect them in ownClouds admin area. What a drag...
Apart from such smallish annoyances I'm a great fan of ownCloud and use it heavily - many many thanks to all involved!

**Comment by te-online** [comment]
Isn't it even worse? For me on update every folder in docroot gets removed, that is not oc-related. I had to restore folders from backups some times after updates.

Unfortunately, I can't see any problems from the code, because actually the updater only touches 3rdparty, core and apps directory.

**Comment by te-online** [comment]
Okay, it seems to me, that a whitelist is created in apps/updater/lib/files.json. I didn't find out yet when and how it is created so that we could trigger the creation again before updating (would that be possible?).

**Comment by VicDeo** [comment]
>I got only empty messages when things went wrong, same as picture in issue 50
Fixed since 7.0.3

>The updater moves anything unknown in the docroot into its backup directory and leaves it there. 
Fixed for OC8 in master

**Comment by te-online** [comment]
Great :+1: 

>>The updater moves anything unknown in the docroot into its backup directory and leaves it there. 

> Fixed for OC8 in master

Just to be certain: Does that mean all folders in docroot stay in place?

**Comment by VicDeo** [comment]
@te-online yes. See changes in  `lib/location/core.php` https://github.com/owncloud/updater/pull/57/files for details

**Comment by te-online** [comment]
Good, thanks :-)

**Comment by VicDeo** [comment]
Closing as fixed in OC8
