### ISSUE TITLE
Problem in OC 8 alpha 1

### ISSUE THREAD

**Issue by canepan** [owncloud/updater#66]
When I try to open the updater app, I get:

> Fatal error: Call to a member function getValue() on a non-object in *&lt;htdocs&gt;*/owncloud8a1/lib/private/updater.php on line 84

**Comment by karlitschek** [comment]
@VicDeo Can you have a look please?

**Comment by te-online** [comment]
The vars for the constructor ($config and $httphelper) seem to miss here https://github.com/owncloud/core/blob/master/lib/private/updater.php#L46

I found, that you could replace *$this->config->* with *\OC_Config::* or *\OC_AppConfig::* – I'm not quite sure – as it can be seen later in the code. Sorry for guessing on a low level :D. I'm not familiar with that kind of programming and e.g. I don't understand how this works with updater only calling

```
$updater = new \OC\Updater();
```
https://github.com/owncloud/updater/blob/master/update.php#L27

But I want to learn more about it :) Is this some kind of global variable magic? Very curious about the solution for this one.
