### ISSUE TITLE
Release updater 1.1.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/updater#713]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #711 made code changes needed for Symfony 5

Note: the change in that PR also works fine with server core 10.12 and before, so there should be no need to bump the core min-version.

The app can be released any time before 10.13 - it should work fine with any of the recent oC10 core releases.

**Comment by jnweiger** [comment]
https://github.com/owncloud/updater/releases/download/v1.1.0-rc.1/updater-v1.1.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
@phil-davis I don't think I can make a release for this.
- It does not have an appinfo/info.xml and cannot be installed with core 10.12.2
- what exactly would this app do? I don't find any clear dcumentation around here.
- I am not even sure it is a proper app.

**Comment by phil-davis** [comment]
I don't know the history of this app. It previously had releases tagged v10.1.0 v10.1.1 so somehow it used to "go with" core releases. Then there was a 1.0.0 release https://github.com/owncloud/updater/releases/tag/v1.0.0 in 2019.

I have just maintained CI so that the unit tests etc keep passing. I don't know who actually uses this app. So maybe archive it?

**Comment by iasdeoupxe** [comment]
#726 / owncloud/core#41057: app seems to be still used

**Comment by VicDeo** [comment]
@jnweiger  it's not an **ownCloud app**. It's a standalone web upgrade subsystem. 
To stress this out it is located not in the apps folder but in a separate `updater` directory of the release package.

**Comment by VicDeo** [comment]
As I see owncloud-complete-20231009.zip includes all the changes from https://github.com/owncloud/updater/pull/711 so basically release was done.

**Comment by sfadschm** [comment]
> #726 / owncloud/core#41057: app seems to be still used

How else would we update Owncloud Core on a live server? This is also where the admin panel guides us when a new version is available.

**Comment by iasdeoupxe** [comment]
> How else would we update Owncloud Core on a live server?

Manual update is the way to go / recommended:

https://doc.owncloud.com/server/10.13/admin_manual/maintenance/upgrading/upgrade.html#upgrade-options

Same page also says about the updater:

> This is not the recommended upgrade procedure, as builtin core upgrade scripts are error prone.

**Comment by sfadschm** [comment]
Fair enough, I totally forgot about the manual path as this was never an option with my setup.

However, to contribute to the discussion, I believe there are plenty of admins using the updater to do the task, be it out of laziness or because someone is not so prone with scripting or the command line.

That being said, technically, I would say #711 is a breaking change and should be fixed. See #726.

**Comment by iasdeoupxe** [comment]
While i agree that this should be fixed:

Keep in mind that even if some one of ownCloud is fixing this issue your current installation is AFAICT still having the updater in the current broken state and a fix is only included in the next ownCloud version. So i wouldn't wait until some one of them is fixing the issue.

**Comment by phil-davis** [comment]
https://download.owncloud.com/server/stable/owncloud-latest.tar.bz2 has an `updater` folder with the current real code of the updater repo from 2023-07-14 - good.
This commit bumped the version:
https://github.com/owncloud/updater/commit/ee951f01abf0b0734de7cde76de7215cc6f964db

Note: commits since then are only vendor dependency bumps, none of which are really important. They are not in `updater/vendor` of the latest core 10.13.4 tarball. So the updater code is not being routinely updated into each core release tarball. I suppose that @jnweiger did some explicit action to provide 1.1.0 to the core release in July 2023.

Closing this issue - this has been effectively "released". Installations will get the "release" after they upgrade to a recent release. There is no automated/scripted way to update the updater in a existing older installation. So it can be a bit of a catch-22 if someone needs the updated updater in order to update!

**Comment by iasdeoupxe** [comment]
Some related notes:

I have raised owncloud/core#41149 and suggested to disable the (Web-)Updater by default.

> it's not an ownCloud app. It's a standalone web upgrade subsystem.

Even the docs of ownCloud says it is an app:

[Upgrading ownCloud with the Updater App](https://doc.owncloud.com/server/10.13/admin_manual/maintenance/upgrading/update.html)
