### ISSUE TITLE
Updater deleted /cgi -> Update fails.

### ISSUE THREAD

**Issue by kaffeeringe** [owncloud/updater#72]
Hi all!

I just used the automatic updater for the update from 7.0.2 to 7.0.4 and it failed because the updater deleted the /cgi folder that I need in my all-inkl.com webspace to run higher PHP versions. After restoring it, the update went on fine …

Thank you for all the cool work! Owncloud rules!

**Comment by LukasReschke** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@kaffeeringe thanks for reporting, this is a known issue for OC7. 
Fixed for OC8 already
Closing as a duplicate of https://github.com/owncloud/updater/issues/64

**Comment by kaffeeringe** [comment]
Thank you! I checked for a previous bug in /core - I didn't check here…
