### ISSUE TITLE
Upgrade from 13.10.1.3 to 13.10.2 fails on Ubuntu.

### ISSUE THREAD

**Issue by sfadschm** [owncloud/updater#726]
**Steps to reproduce**
1. Run update via /.../updater/application.php

2. Error: upgrade:backupDBlb command is not implemented

3. Updater exits.

4. Run update via webUI admin panel.

5. Update is successfull, but aborts with error: upgrade:restartWebServer command is not implemented.

6. UI is stuck and upgrade appears to not be finished.

7. Actually, update was successful.

**Expected behaviour**
The upgrade runs smoothly...

**Actual behaviour**
The upgrade fails at the first step or is successfull but shows an error.

**Server configuration**
Operating system: Ubuntu 20.04.6 LTS

Web server: Apache

Database: MariaDB

PHP version: 7.4

ownCloud version: 10.13.1.3

Updated from an older ownCloud or fresh install: Updated.

**Comment by sfadschm** [comment]
Moved from https://github.com/owncloud/core/issues/41057#issue-1955849055.

**Comment by sfadschm** [comment]
This issue still persists with Core 10.13.3.4.

**Comment by sfadschm** [comment]
The reason is most likely this change:

https://github.com/owncloud/updater/blob/master/src%2FCommand%2FBackupDbCommand.php#L46

The method now returns 1 and stops the update. Before, it returned nothing.

Same for the restartwebserver command.

Ref.: #713

**Comment by sfadschm** [comment]
@phil-davis Maybe the methods should return 0, i.e., fail silently? At least this seems to be how it was handled before #711. At least we now have the output that the methods are not implemented.

**Comment by sfadschm** [comment]
> @phil-davis Maybe the methods should return 0, i.e., fail silently? At least this seems to be how it was handled before #711. For now, we have the output that the methods are not implemented, which is quite good to know for anyone using the updater.

**Comment by phil-davis** [comment]
PR #730 puts the behavior back, so that things that are not-yet-implemented will return command line status `0` (success), and not fail the upgrade. That should fix the problem.

It won't end up in a release until the next core release (some time in 2024, I suppose). Existing installations would need to apply that change "manually" if they want to use the updater.

**Comment by sfadschm** [comment]
Thanks!
As initially stated, the updater is actually still working when running from the webUI. There it only fails at the restartWebserver command, after the actual update is already finished. So for users who use this way, it should work to just update and ignore that error.

Running the updater from the command line will however not be possible as you described.
not sure if that might be worth an update note?

**Comment by sfadschm** [comment]
Fixed in core 10.15.
