### ISSUE TITLE
Update server error 7.0.3 --> 7.0.4 with data dir outside of document root

### ISSUE THREAD

**Issue by moritzthecat** [owncloud/updater#73]
Hello, 
so far I had little success using the updater app ... sometimes it is working sometimes not. But I appreciate the improved error handling. Updating from 7.0.2 --> 7.0.3 went ok. But when I tried updating to 7.0.4 using updater app I got the following error. Installation was not changed though ...
![update-server-error](https://cloud.githubusercontent.com/assets/3109519/5875653/f30291a8-a30f-11e4-93ce-a89e08eba265.JPG)
The log says:
[Fri Jan 23 11:04:10 2015] [error] [client xxx.yyy.zzz.aaa] File does not exist: /data/www/.../html/oc/data
[Fri Jan 23 11:06:44 2015] [error] [client xxx.yyy.zzz.aaa] Script timed out before returning headers: index.php, referer: https://<mysite/oc-dirname>/index.php/apps/updater/update.php

But this is fine, because I store the data files NOT under the html tree of the owncloud installation but somewhere else as defined in the config.php and recommended for security reasons in the owncloud documentation under advanced options.

**Comment by moritzthecat** [comment]
in addition to the issue described above the updater somehow kept the directory
.../www/owncloud/_oc-upgrade/<last-oc-version>
locked by a running process.
It was not possible to delete this directory - thus I had to ask the sys admin of my hoster to unlock/delete this directory - renaming was possible though.

**Comment by VicDeo** [comment]
Updater doesn't touch datadir explicitly. This entry is most likely related to the automated core check whether data dir is accessible from web:
>[Fri Jan 23 11:04:10 2015] [error] [client xxx.yyy.zzz.aaa] File does not exist: /data/www/.../html/oc/data

this check can be disabled by adding in your config.php
```
"check_for_working_htaccess" => false,
```

>Script timed out before returning headers
in addition to the issue described above the updater somehow kept the directory
.../www/owncloud/_oc-upgrade/
locked by a running process.

which means that you use fastcgi and PHP script is still running while you server thinks it's not.

Both issues are rather related to configuration

**Comment by VicDeo** [comment]
If you have an additional information please post it to https://github.com/owncloud/updater/issues/89 
Complete reports according to the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md are appreciated.

Closing
