### ISSUE TITLE
Release updater 1.1.1

### ISSUE THREAD

**Issue by phil-davis** [owncloud/updater#731]
to release the fix in PR #730 (issue #726 )
and the various PHP dependency bumps that have happened in the last few months.

Release needed (make a GitHub release with tag). And then make sure that the code gets into the tarball of the next core release.

Note: after PR #730 is merged, then a prepare-release PR will be needed like https://github.com/owncloud/updater/commit/ee951f01abf0b0734de7cde76de7215cc6f964db

### Product approval 

- [ ] Verify transifex commits (enterprise should update weekly, others daily): If folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...
- [ ] Check `info.xml` description and screenshot

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core))
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404327434/Apps+with+special+release+process) applies, and adapt this checklist.
   -  Only GitHub upload, not to be released on marketplace or portals.
   -  No notice to release-coordination list or updates channel.

### Documentation

- [ ] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new .

### Marketing

- [ ] ~Update https://kiteworks.atlassian.net/wiki/spaces/PROD/pages/403801090/Upcoming+Releases~
- [x] Check for any left over TODO's at https://kiteworks.monday.com/my_work (hide [x] done, empty)

### Build

All actions to be done on the release branch (`git pull; git checkout -b release-x.x.x`) from here:
- [x] Bump version in `appinfo/info.xml` (no version suffix)
- [x] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [ ] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] `git tag -s v${version}-rc.1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [x] Check buildlog for security reports
- [x] Check github security tab dependabot reports
    - [ ] -> if critical or high entries are reported: open a release blocker issue.
- [x] Upload as Github release using changelog entries
- [ ] Test and document in testplan + manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [ ] Do changelog tests
    - [x] Do regression tests
    - [ ] Watch out for untranslated strings when locale is de oder de_DE.
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [ ] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [ ] Upload tarball to marketplace (details https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404326697/Releasing+Apps)
- [ ] Publish tarball for customers `github/owncloud/QA/tools/portal_upload_app.sh` - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (details https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404326697/Releasing+Apps)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog `github/owncloud/QA/tools/release/oc_release.sh app:status`
- [ ] Copy email to rocket chat `#updates` channel (`remove all `https://` to avoid auto-expansions.)
- [ ] Submit mail-text as a Markting Request via https://kiteworks.monday.com/boards/5983659465/views/130504071
	- DONE: Send Email to Alias: release-coordination@owncloud.com
	- DONE: Send Rocket Chat (internal)
	- DONE: Post to GitHub
	- DONE: Post to ownCloud Marketplace

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [ ] Close the testplan issue
- [x] Check for any left over TODO's at https://kiteworks.monday.com/my_work (hide [x] done, empty)

**Comment by phil-davis** [comment]
PR #730 has been merged.
I have made PR #733 with the version bump.
That can be merged, and then a "release" tagged. That tagged code will get released along with the next oC10 core released (it is a "bundled" kind of thing, not a regular oC10 app)

**Comment by phil-davis** [comment]
Didn't happen in time for core 10.14.0

**Comment by sfadschm** [comment]
Any estimate when this will be finished?

**Comment by phil-davis** [comment]
@jnweiger do you have an estimate of when this can progress?

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] upgrade from 10.13.4 fails
* [ ]
