### ISSUE TITLE
No update for 7.0.4 to 8.0 

### ISSUE THREAD

**Issue by cdamken** [owncloud/updater#74]
### Expected Behavior
Open the updater and get the oC8 version

### Actual Behavior
Open the updater and says there is no new version.

### Steps to reproduce:
1.- Open the updater and run it.

### oC Version
7.0.4 Community edition

Thanks :smiley:

**Comment by HenningSchulz** [comment]
Same here.

**Comment by VicDeo** [comment]
+1

**Comment by karlitschek** [comment]
We have a few bad bugs in 8.0.0 So maybe we will delay the updater availability for some time before 8.0.1 is out. Sorry for the inconvenience.

**Comment by RealRancor** [comment]
Should be now fixed or am i wrong?

**Comment by karlitschek** [comment]
yes.
