### ISSUE TITLE
feature request : Occ need new command

### ISSUE THREAD

**Issue by cedrilou** [owncloud/updater#76]
Hi, we need a new command for occ.
-"update" for update the version automatically (all update process : download, backup, ...) . Same as the update center but in command line.
With this "update" command , it is necessary to have an option to keep the configuration (theme in particular)

Thank you for the quality of your work ;)
Cédric

**Comment by rakekniven** [comment]
That would be awesome. 
@VicDeo Are there any thoughts in this direction?

**Comment by cedrilou** [comment]
Is it possible for a module to add a command to occ? If this is not possible, ask the core to add this option.

**Comment by RealRancor** [comment]
@cedrilou
Yes, apps can add additional commands to occ. See the music app for example:

https://github.com/owncloud/music/blob/master/appinfo/register_command.php
https://github.com/owncloud/music/tree/master/command

You could also close the reported feature request in core: https://github.com/owncloud/core/issues/14252

**Comment by VicDeo** [comment]
@cedrilou  9.0 will have it. Not with occ but with own entrypoint https://github.com/owncloud/updater/blob/master/application.php

**Comment by VicDeo** [comment]
Implemented as `sudo -u wwwrun php /path/to/owncloud/updater/application.php upgrade:checkpoint --create`

**Comment by rakekniven** [comment]
@VicDeo Could you tell us why it is not an occ command?

**Comment by VicDeo** [comment]
@rakekniven because updater should be not connected with core according to the spec:
>New isolated updater, all code files are located in /updater, no interaction with the rest of ownCloud.
No code, configuration, database or anything else used from core is required. (- included with normal ‘required’ to make it isolated)

https://github.com/owncloud/core/issues/18721
It is _NOT_ an ownCloud app anymore, but a standalone app

**Comment by rakekniven** [comment]
Yeah, that really makes sense. 
Will check my beta 9.0 and see if it already included :+1:

**Comment by VicDeo** [comment]
@rakekniven should be there. Bugreports are welcome ;)
