### ISSUE TITLE
No Updates offered in Update Center in ownCloud 7.0.2

### ISSUE THREAD

**Issue by usrbin123** [owncloud/updater#78]
### Steps to reproduce
1. Log in into ownCloud, enter Admin panel, open Update Center

### Expected behaviour
OwnCloud should offer me to update from Version 7.0.2 to 7.0.4

### Actual behaviour
OwnCloud does not offer an update.
```Up to date. Checked on 20.02.2015 00:05:18```

### Server configuration
**Operating system:** Linux # 1 SMP Debian 3.2.65-1+deb7u1
**Machine Type:** x86_64
**Web server:** Apache
**Database:** MySQL
**PHP version:** 5.5.21 **PHP Integer Size:** 64 bits
**OwnCloud version:** 7.0.2 (stable)
**Updated from an older ownCloud or fresh install:** Fresh Install
**List of activated apps:**
- Files Move 0.7.2
- Dashboard 1.3.1
- Superlog 0.6.0

**Comment by karlitschek** [comment]
Strange. @VicDeo any idea?

**Comment by usrbin123** [comment]
### Config

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'Domain.com',
    1 => 'www.Domain.com',
  ),
  'datadirectory' => '/usr/www/users/dquolw/cloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dquolw_2',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'Domain.com',
  'mail_from_address' => 'cloud',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'mailDomain.de',
  'mail_smtpport' => '587',
  'mail_smtppassword' => '',
  'mail_smtpname' => 'cloud@Domain.com',
  'forcessl' => true,
  'loglevel' => '0',
  
  'updatechecker' => true,
  'check_for_working_htaccess' => true,
  'maintenance' => false,
  'singleuser' => false,

  
);

**Comment by VicDeo** [comment]
@usrbin123 
Can you post output for `php -m | grep curl` and `php -i | grep allow_url_fopen` ?

**Comment by VicDeo** [comment]
Ah, OC7 doesn't use curl for feed fetching yet. So I guess `allow_url_fopen` is off.

**Comment by usrbin123** [comment]
Hi @VicDeo 
as Owncloud is hosted on a managed server from Hetzner I cannot run ```php -m | grep curl``` or ```php -i | grep allow_url_fopen```

**Comment by RealRancor** [comment]
@usrbin123 
There are other ways of checking this like a phpinfo file put into your webroot. See your favorite search engine for some more infos.

**Comment by usrbin123** [comment]
allow_url_fopen is off, as you guessed.
```allow_url_fopen; Off; Off```

I copied the Curl info below:
```
cURL support	enabled
cURL Information	7.26.0
Age	3
Features
AsynchDNS	No
CharConv	No
Debug	Yes
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
NTLMWB	Yes
SPNEGO	No
SSL	Yes
SSPI	No
TLS-SRP	Yes
Protocols	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, pop3, pop3s, rtmp, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host	x86_64-pc-linux-gnu
SSL Version	OpenSSL/1.0.1e
ZLib Version	1.2.7
libSSH Version	libssh2/1.4.2
```

**Comment by VicDeo** [comment]
@usrbin123 unfortunately cURL is not used for feed fetching until OC 8
As a hotfix you can try to  replace this lines 94-101 in the file https://github.com/owncloud/core/blob/a3dcbe5bcee2df9706213deae24b892ae235e363/lib/private/updater.php#L94
with 
`$xml =  \OC_Util ::getUrlContent($url);`

**Comment by usrbin123** [comment]
@VicDeo I did as proposed, but still no change. Sorry for asking, but how can I do a manual update to OC 7.0.4. ? Can you paste me a manual ? 
And OC 8.0 is to experimental at this stage.

**Comment by RealRancor** [comment]
@usrbin123 
See: https://doc.owncloud.org/server/7.0/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure and just use the OC 7.0.4 instead of the OC 8.0.0 package.

**Comment by VicDeo** [comment]
@usrbin123 Do you have any news? 
I guess you just need to browse the admin page in about 30 minutes after patching the code for the feed data to refresh (it is cached for 30 minutes)

**Comment by usrbin123** [comment]
I left the OC installation as it was for a couple of days, as I was quite busy. This weekend, it suddenly offered me the update to 8.0.2. I backed up and upgraded directly from 7.0.2 to 8.0.2. Seems to work very well so far. Sorry for being late with the response.

**Comment by VicDeo** [comment]
@usrbin123 NP, thanks.
Closing as resolved
