### ISSUE TITLE
Update to 8.0.2

### ISSUE THREAD

**Issue by heartsaver** [owncloud/updater#88]
### Steps to reproduce
The error raised when trying to update from 8.0 to 8.0.2 using the owncloud Updater app.

### Expected behaviour
Tell us what should happen

Update to version 8.0.2.0

### Actual behaviour
Tell us what happens instead

updater is stuck at step 3.Replace with error:
Server error. Please check web server log file for details

Tried several times but with no success. Backup files are generated in the updater_backup directory: 
Sicherungen

Sicherungverzeichnis: /.../updater_backup/

Sicherung	Abgeschlossen am	 
8.0.0.7-1d5bdf09	March 11 2015 15:31:49	
8.0.0.7-25b2a165	March 11 2015 15:42:29	
8.0.0.7-ce5adbb3	March 11 2015 15:38:11	

### Server configuration

**Operating system**:
Ubuntu Server 14.04.2 LTS

**Web server:**
Apache/2.4.12 (Ubuntu)

**Database:**
MySQL Server 5.5.41-0ubuntu0.14.04.1

**PHP version:**
PHP 5.6.6-1+deb.sury.org~trusty+1 (cli) (built: Feb 20 2015 11:22:10)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo

**ownCloud version:** (see ownCloud admin page)

ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh installed 8.0.0

**List of activated apps:**
Activity 1.2.0
Bookmarks 0.4
Calendar 0.6.4
Contacts 0.3.0.18
Deleted files 0.6.2
Documents 0.9.0
External Sites 1.2
External storage support 0.2.3
External user support 0.4
File Locking 
First Run Wizard 1.1
Full Text Search 0.6.0
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.0
Text Editor 0.4
Video Viewer 0.1.3
WebDAV user backend 1.1.0.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 
  'passwordsalt' => 
  'secret' =>
  'trusted_domains' => 
  array (
    0 =>
    1 => 
  'datadirectory' => 
  'overwrite.cli.url' => 
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 
  'dbhost' => 'localhost',
  'dbtableprefix' => 
  'dbuser' => 
  'dbpassword' => 
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 1,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 
  'mail_domain' => 
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 
  'mail_smtpport' => '465',
  'mail_smtpname' => 
  'mail_smtppassword' =>
);

**Are you using encryption:** yes/no

yes, HTTPS enforced

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### LDAP configuration (delete this part if not used)

no LDAP

### Client configuration
**Browser:**

tried both Firefox 36 and Chromium 37

**Operating system:**

Ubuntu 12.04 & Windows 8.1

#### Web server error log
empty, only very old entries

#### ownCloud log (data/owncloud.log)
{"reqId":"7ab48523641d0a17c77e357434249063","remoteAddr":"93.232.7.124","app":"PHP","message":"Cannot redeclare class OC\\Security\\SecureRandom at \/var\/www\/html\/lib\/private\/security\/securerandom.php#24","level":3,"time":"2015-03-11T15:32:10+00:00"}
{"reqId":"3325a555d65a4046e1bd3213107085fc","remoteAddr":"93.232.7.124","app":"PHP","message":"Cannot redeclare class OC\\Security\\SecureRandom at \/var\/www\/html\/lib\/private\/security\/securerandom.php#24","level":3,"time":"2015-03-11T15:38:24+00:00"}
{"reqId":"e596f738eaf287643b2b6c3698416f2d","remoteAddr":"93.232.7.124","app":"PHP","message":"Cannot redeclare class OC\\Security\\SecureRandom at \/var\/www\/html\/lib\/private\/security\/securerandom.php#24","level":3,"time":"2015-03-11T15:42:47+00:00"}

**Comment by RealRancor** [comment]
@heartsaver 
As you already posted this in https://github.com/owncloud/updater/issues/86 feel free to close this duplicate report.
