### ISSUE TITLE
Updater Error (Upgrade to 8.0.2)

### ISSUE THREAD

**Issue by dcrdev** [owncloud/updater#91]
The updater throws an error at stage three - the log reveals this:
Cannot redeclare class OC\Security\SecureRandom at /xxx/xxx/xxx/htdocs/cloud/lib/private/security/securerandom.php#24

I've tried the suggested modification in https://github.com/owncloud/updater/issues/86#issuecomment-78503941

PHP Info: http://goo.gl/uswY27
MD5 Hashes: http://goo.gl/tlCRDb

### Expected behaviour
Tell us what should happen

Update to version 8.0.2.0

### Actual behaviour
Tell us what happens instead

updater is stuck at step 3.Replace with error:
Server error. Please check web server log file for details

Tried several times but with no success. Backup files are generated in the updater_backup directory:
8.0.0.7-xxxxxx
8.0.2.0.zip

### Server configuration
**Operating system**:
Apache/2.4.10 (Unix) OpenSSL/1.0.2 PHP/5.6.3

**Web server:**
Look at php info link...

**ownCloud version:** (see ownCloud admin page)

ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**

The error raised when trying to update from 8.0 to 8.0.2 using the owncloud Updater app.

**List of activated apps:**
External Storage

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

multiple smb shares on localhost

**Are you using encryption:** yes/no

yes, HTTPS enforced (self signed cert)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### LDAP configuration (delete this part if not used)

no LDAP

### Client configuration
**Browser:**

Chrome 40

**Operating system:**

Tiny Core Linux

#### Web server error log

[mpm_prefork:error] [pid 6566] AH00161: server reached MaxRequestWorkers setting

**Comment by VicDeo** [comment]
@dcrdev 
workaround: https://github.com/owncloud/updater/issues/86#issuecomment-78503941

closing as a duplicate

**Comment by dcrdev** [comment]
Actually as stated in my issue - that workaround does not work for me. I was asked in #86 to open a separate issue, as my problem is something else.

**Comment by VicDeo** [comment]
@dcrdev ok. reopening. Is 'server reached MaxRequestWorkers setting' the only entry in apache error log?

**Comment by dcrdev** [comment]
Yes it is... as I've mentioned above I've modified my apache config file as result to a fairly high value; unfortunately it hasn't made a difference.

**Comment by VicDeo** [comment]
ok, if I got it right logging should start before adjusting include path otherwise some core classes are resolved twice inside this loop: https://github.com/owncloud/core/blob/master/lib/autoloader.php#L102

@dcrdev please add the following line

```
App::log('Moving files', \OC_Log::INFO);
```

here:
https://github.com/owncloud/updater/blob/stable8/lib/updater.php#L23

and retry. Thanks

**Comment by VicDeo** [comment]
@dcrdev just to clarify: It seems you have an error and logging it breaks the update process.
Unlike the other reporters that are failing on success.
 So I think this change won't fix your issue right away but will  log the reason of failure properly.

**Comment by VicDeo** [comment]
@dcrdev can you test https://github.com/owncloud/updater/issues/101 ?
It should work just fine.

**Comment by VicDeo** [comment]
Fixed in 8.0.3 with https://github.com/owncloud/updater/pull/108
Which means this 8.0.3 to 8.0.4 should not have this bug. 
Please reopen if it is still reproducible
