### ISSUE TITLE
Update to 8.0.2 stuck

### ISSUE THREAD

**Issue by SamEliotFisher** [owncloud/updater#92]
### Steps to reproduce
1. Try automatic update via oc website
2. Workaround bug https://github.com/owncloud/updater/issues/86 doing https://github.com/owncloud/updater/issues/86#issuecomment-78503941 
3. Click on "upgrade database" and "Start update"
4. Get message "CSRF attack. Connection will be closed."
5. Reload the page. 
6. Try manually setting maintenance to false will bring you back to step 4

### Expected behaviour
Click on update. Update successful.

### Actual behaviour
Update process gets stuck displaying this message:
"This ownCloud instance is currently being updated, which may take a while. This page will refresh itself when the ownCloud instance is available again. Contact your system administrator if this message persists or appeared unexpectedly. Thank you for your patience."

### Server configuration
**Operating system**: Ubuntu 14.10

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.0.0.7

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:** all recommended.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc8ab27a8968',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'mydomain.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://mydomain.com',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ocuser',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'abc',
  'mail_smtpmode' => 'php',
  'mail_domain' => abc.com',
  'maintenance' => true,
  'theme' => '',
  'forceSSLforSubdomains' => true,
  'loglevel' => 1,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 36.0.1

**Operating system:** Wind 8 

#### Web server error log
```
No relevant error logs.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"2f1a8d6b8e9a9a3153058917dcb53ed4","remoteAddr":"xx.xxx.xxx.xxx","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(77): OC_App::loadApp('files_sharing')\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/util.php(75): OC_App::loadApps(Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/base.php(766): OC_Util::setupFS()\n#3 \\/var\\/www\\/owncloud\\/index.php(36): OC::handleRequest()\n#4 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/app.php\",\"Line\":96}","level":4,"time":"2015-03-12T18:49:50+00:00"}
```

**Comment by LukasReschke** [comment]
Sorry to bother again. Can you reopen in core? Now it's a bug there. - I know it's confusing ;)

**Comment by SamEliotFisher** [comment]
Re-opnend: https://github.com/owncloud/core/issues/14842

**Comment by eleith** [comment]
for those that find this, one workaround is to run './occ upgrade' manually. that works without hitting the CSRF error which seems to stop the upgrade.

it does say you can do this in the error page itself, but i thought i would at least say that it does work.

**Comment by deg0nz** [comment]
I had the same issue, that OC was stuck in update mode.
calling './occ upgrade' manually from terminal did it for me!
