### ISSUE TITLE
Provide option to not update to next major version

### ISSUE THREAD

**Issue by RealRancor** [owncloud/updater#95]
On OC 7.0.4 for example the updater is currently offering only an update to 8.0.2 but not to 7.0.5. Seems some people still want to stay with the OC 7 branch:

https://forum.owncloud.org/viewtopic.php?f=29&t=27009

so it could be useful to provide an option to stay with the current branch rather than upgrade to the next major version.

**Comment by craigarno** [comment]
Here's another Update proposal https://forum.owncloud.org/viewtopic.php?f=29&t=27092&p=82159#p82159

**Comment by shellshocker** [comment]
A choice would be great. Some people don't want to upgrade / some people can't upgrade. I prefer to update the 7.x branch.

**Comment by rakekniven** [comment]
Upgrading of major versions is not an option sometimes. Some of my apps are still not ready for 8.x and I want to stay with 7.x series. Updater cannot used for my needs. Would be grade if updater can get this enhanced feature.

**Comment by phxyz12** [comment]
Hi

from reading the current OwnCloud Administrator's Manual, I come to the conclusion that this issue is not an "enhancement" but simply a bug. Check chapter "Maintenance":

"The Updater app automates many of the steps of updating an ownCloud installation to the next point release. [...] Updating and upgrading your ownCloud installation are two different tasks. Updating means updating to the next point release, which is indicated by third digit of the version number. [...] The Updater app is not for upgrades;"
Link: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/update.html

So for me this means, that the Updater App should in fact offer version 7.0.5 and never 8.0.x on a 7.0.x system.

**Comment by mandawah** [comment]
Hi there,

I completely agree with what phxyz12 said, this has confused me as well.

Does any of you have an idea how to hack 7.0.4 updater into forcing it to update to 7.0.5? 

I didn't find from where Updater is getting it's version number to update to. Would it be possible for me to hardcode it somewhere directly and temporary solve the issue?

Thanks in advance!

**Comment by craigarno** [comment]
After attempting an update to 8.0.2, I just downloaded 7.0.5, unpacked and copied my config.php.  Then it worked again.

```
mv owncloud owncloud802
tar xjf owncloud-7.0.5.tar.bz2
chown -R wwwrun:www owncloud
cp -a owncloud802/config/config.php owncloud/config
```
At this point everything would run again except I had to unpack Mozilla-Sync into owncloud/apps and re-enable as admin.

I'm hoping my database isn't messed up, I'm guessing not.  When I get more time I'll look into installing 8.0.2 from a download package for a full **Upgrade**.

**Comment by wikimas** [comment]
I'm really annoyed with owncloud nagging "ownCloud 8.0.2 is available. Get more information on how to update.", getting stuck while updating, and then, when I update and -grade manually, it tells me, HEY your PHP isnt up to date...

Of course downgrading corrupted my files.

Come one, it's only one if-statement to check the installed version of php, to hide the 8.02 update nag!

**Comment by craigarno** [comment]
I put this in my ../config/config.php file to stop the nagging on my OwnCloud 7.x system... 

```/**
 * Check if ownCloud is up-to-date and shows a notification if a new version is
 * available.
 */
  'updatechecker' => false,
```

**Comment by RealRancor** [comment]
Hi,

unfortunately you also won't get updates for OC 7.0.x shown so thats not a real solution in my opinion.

**Comment by craigarno** [comment]
Yeah, I agree, but at least it got rid of the bright yellow banner on the top of my site telling me to do something I can't do anything about right now.  It is a *real world* solution as opposed to a *perfect world* solution.  So now the onus is on me to occasionally check for 7.0.x updates.  It's a tradeoff I can accept until the OwnCloud Update code writers come up with a usable solution.  Hopefully they'll tell us when a solution -**is**- available.

**Comment by VicDeo** [comment]
@craigarno 
>Yeah, I agree, but at least it got rid of the bright yellow banner on the top of my site telling me to do something I can't do anything about right now. 

this is unrelated to updater app. See https://github.com/owncloud/core/pull/16017
