### ISSUE TITLE
Update 7.0.4.2 => 8.0.2 (via Update Center) failed!

### ISSUE THREAD

**Issue by Mr-HeBo** [owncloud/updater#96]
### Steps to reproduce
1. open ownCloud and login as Admin
2. start update with Updater (Update Center)
3. check & update: successfully
4. download & extract: The update failed. Please check the logs on the Administration page and report this problem to the ownCloud community.

### Expected behaviour
start and install update from 7.0.4.2 to 8.0.2

### Actual behaviour
update failed

### Server configuration
**Operating system**: Linux

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 5.6.6

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install: update from 7.0.2

**List of activated apps:
	Bookmarks
	Calendar
	Contacts
	Deleted Files
	External Sites
	External storage support
	External user support
	First Run Wizard (group admin only)
	Full Text Search
	Mail Template Editor (group admin only)
	ownCloud dependencies info (group admin only)
	PDF Viewer
	Pictures
	Share Files
	Text Editor
	Updater (group admin only)
	Version
	Video Viewer
	Antivirus App for files (0.4.2)
	Dashboard (1.3.1)
	
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ0e632c675',
  'passwordsalt' => '7713f545b91bf44e233c4c6bfa93d',
  'trusted_domains' => 
  array (
    0 => 'domain.de',
    1 => 'www.domain.de',
  ),
  'datadirectory' => '/var/www/vhosts/www.domain.de/html/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'db_name',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'db_user',
  'dbpassword' => 'db_password',
  'installed' => true,
  'forcessl' => true,
  'defaultapp' => 'ocDashboard',
  'theme' => '',
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.de',
  'mail_smtpname' => 'SMTP_name',
  'mail_smtppassword' => 'SMTP_password',
  'loglevel' => '0',
  'maintenance' => false,
  'secret' => 'b523a20671d511a0cc329858804d11c51134a2b687ac8fac3d72fd87205a826b68b35d735db09b189debccfcb52849c6',
);

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO (but, files are partially encrypted with PGP.)

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
Firefox 36.0.1
Internet Explorer 11.0.9

**Operating system:**
Windows 7 Prof. 64 Bit

#### ownCloud log (data/owncloud.log)
Error 	PHP Cannot modify header information - headers already sent at Unknown#0 	2015-03-13T22:21:02+00:00
Error 	PHP Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#219 	2015-03-13T22:21:02+00:00
Error 	PHP Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#216 	2015-03-13T22:21:02+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#219	2015-03-13T22:24:33+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#216	2015-03-13T22:24:33+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#203	2015-03-13T22:24:33+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#198	2015-03-13T22:24:33+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/response.php#197	2015-03-13T22:24:33+00:00
Error	PHP	Cannot modify header information - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/base.php#233	2015-03-13T22:24:33+00:00
Error	PHP	session_start(): Cannot send session cache limiter - headers already sent at /var/www/vhosts/www.domain.de/html/owncloud/lib/private/session/internal.php#21

**Comment by RealRancor** [comment]
Hi,

to be safe disable all 3rd party apss as well as the calendar and contacts app. Then remove the:

'defaultapp' => 'ocDashboard',

and try again.

**Comment by Mr-HeBo** [comment]
Hi,

thanks for your quickly support.

All apps are disabled and also I have changed the config.php. But the 
update can not be installed (the same error messages).

Regards Heiko


Am 2015-03-14 08:34, schrieb RealRancor:

> Hi,
> 
> to be safe disable all 3rd party apss as well as the calendar and 
> contacts app. Then remove the:
> 
> 'defaultapp' => 'ocDashboard',
> 
> and try again.
> 
> --
> Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/owncloud/updater/issues/96#issuecomment-80076351

**Comment by VicDeo** [comment]
@Mr-HeBo My crystall ball said this is a duplicate of https://github.com/owncloud/updater/issues/56
and you need to add the line  `always_populate_raw_post_data = -1` to your php.ini

**Comment by Mr-HeBo** [comment]
Thank you. I'll try it and give feedback about the result.

**Comment by Mr-HeBo** [comment]
Hello,
php.in is changed.
Now, when I start the update I recieve during the first of three steps (Check & Backup) the message:

   Make sure that your web server has write access to the following files and directories:
   /var/www/vhosts/www.domain.de/html/owncloud/info.php

What is the correct chmode for the directories and files? Currently, there is 755.

Thanks a lot.

**Comment by RealRancor** [comment]
Hi,

i thinknsuch questions about permissions are better placed in the forums or the mailinglist.

**Comment by Mr-HeBo** [comment]
I have not changed the permissions :(
The permissions were not changed. The system ran so far and is still running. The update from 7.0.2 to 7.0.4 was successful. But the update to 8.0.2 failed. 

**1st:** update failed on Step 2. (Please check the logs on the Administration page and report this problem to the ownCloud community.) 
*=> I disabled all apps and delete dashboard from config.php*
**2nd**: update failed on Step 2. (Please check the logs on the Administration page and report this problem to the ownCloud community.) 
*=> I changed php.ini*
**now:** Make sure that your web server has write access to the following files and directories:
/var/www/vhosts/www.domain.de/html/owncloud/info.php
*=> I haven't more ideas*

**Comment by karlitschek** [comment]
@VicDeo any idea why an old update worked but this one not?

**Comment by VicDeo** [comment]
yes, because `/var/www/vhosts/www.domain.de/html/owncloud/info.php` is not owned by www-data user

**Comment by Mr-HeBo** [comment]
what can or must I do :(?

**Comment by RealRancor** [comment]
Change the owner to the correct one or remove the file completely.

**Comment by Mr-HeBo** [comment]
**you are great! Thanks a lot for your help and support!**

info.php deleted => update to 8.0.2 was successfull!!
