### ISSUE TITLE
Error when updating to owncloud 8.0.2

### ISSUE THREAD

**Issue by mredlancelot** [owncloud/updater#98]
the error i get in the log is:

Error	PHP	Cannot redeclare class OC\Security\SecureRandom at /usr/local/www/owncloud/lib/private/security/securerandom.php#24	2015-03-17T15:42:38+00:00
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2015-03-17T15:42:38+00:00

**Comment by karlitschek** [comment]
@LukasReschke this is a duplicate, right?

**Comment by LukasReschke** [comment]
Looks like that to me.

@mredlancelot Can you please try the workaround at https://github.com/owncloud/updater/issues/86 and report back if it works?

**Comment by mredlancelot** [comment]
@LukasReschke this has done the trick, thank you for your help.

**Comment by mredlancelot** [comment]
in case it helps... now my log is displaying the following entries:

Error	PHP	Only variables should be passed by reference at /usr/local/www/owncloud/lib/private/cache/fileglobalgc.php#50	2015-03-18T08:21:16+00:00
Error	PHP	Array to string conversion at /usr/local/www/owncloud/lib/private/l10n/string.php#75	2015-03-18T08:21:15+00:00
Error	PHP	Array to string conversion at /usr/local/www/owncloud/lib/private/l10n/string.php#75	2015-03-18T08:16:19+00:00
Error	PHP	Array to string conversion at /usr/local/www/owncloud/lib/private/l10n/string.php#75	2015-03-18T08:16:19+00:00

**Comment by RealRancor** [comment]
The fileglobal messages looks like a dup of: https://github.com/owncloud/core/issues/14932

The array to string conversion like a dup of: https://github.com/owncloud/core/issues/14714

**Comment by VicDeo** [comment]
@RealRancor thanks, this is a core stuff indeed. Not related to the updater
